### ISSUE TITLE
Payer Information

### ISSUE THREAD

**Issue by romenrg** [paypal/PayPal-node-SDK#105]
Hi,

I'm trying to get the payer's information (specially the country) and I haven't figured up how to do so using this SDK for Paypal's REST API.

In the responses I get once executing "payment.get" or "payment.execute" there is a "payer_info" object that usually looks like this:

```javascript
"payer_info": {
    "email":"xxx@yoyyy.com",
    "first_name":"test",
    "last_name":"buyer",
    "payer_id":"XXXXXX"
}
```

As you can see, the "payer_info" object only includes an email, the name + surname and a payer_id...

How can I get the country and address of the payer?

Kind regards,
Romén

**Comment by avidas** [comment]
Do you notice any difference in this behavior when using paypal vs credit card as payment method? Also, are you getting this in sandbox or live environments?

**Comment by tomwhipple** [comment]
@romenrg you can use the identity API if you first get the user's consent (via the login in with PayPal OAuth2 experience) to gather this information. 

Alternately if you are looking for shipping address, you should examine the payment response.

**Comment by romenrg** [comment]
@avidas I'm using "paypal" as payment method and this was in "sandbox" envirnonment. I haven't performed a purchase in the "live" envirnoment yet. I was asuming I was getting the same structure in both environment, as expected...

**Comment by romenrg** [comment]
@tomwhipple I don't see any shipping address in the response I got (as I replied to @avidas, I'm using "paypal" as payment method and the "sandbox" environment.

**Comment by romenrg** [comment]
Follow-up: I just made a real purchase in "live" environment to test it. Although the payment method I'm setting in the SDK is "paypal" when users go to the billing page of paypal from my site it allows users to pay with debit/credit cards, so in this particular test I paid with a debit card in the billing page of Paypal.

However, I got the same result I was getting yesterday. Actually, even if I go to Paypal's site and check the transaction there (through the website), I can't see the buyer details either. I can just see the buyer's name with a comment "(The sender of this payment is Non-U.S. - Unregistered)" and the email... No country, no shipping address...

As I said yesterday, I need to know the exact country of the buyer for accountig purposes... I can't beleive such a basic information of the purchase is not being sent to the seller. Does it make any sense? I guess most sellers need that information, so I assume there must be a way to get it using this SDK and the REST API.

Any help will be welcomed.

Regards,
Romén

**Comment by avidas** [comment]
@romenrg Were you able to find the answers to your questions here or do you still have some of those issues?

**Comment by romenrg** [comment]
Hi @avidas. Nobody ever replied to me before you, so sadly I haven't received any answers to my questions posted here in August.

**Comment by ppmtscory** [comment]
@romenrg I understand this thread is fairly dated and also can tell you that there was a time last year when there was a bug preventing the address from being returned.  HOWEVER, all of those days are behind us now.  Below is what I get (for `payer_info`) when i call a GET on the payment resource after buyer approval but before execute.  Keep in mind, you'd also get the same address info in the execute response.
```
"payer_info":{"email":"test121212@test.com","salutation":"Mr.","first_name":"test","last_name":"testerson","payer_id":"Q5B7CK6NKTRAL","shipping_address":{"recipient_name":"Frank Enstien","line1":"111 Main St","line2":"Apt. 4","city":"Omaha","state":"NE","postal_code":"68112","country_code":"US"}
```
