### ISSUE TITLE
Insecure and broken dependency used (node-uuid)

### ISSUE THREAD

**Issue by joepie91** [paypal/PayPal-node-SDK#106]
Just a quick heads-up; the [`node-uuid`](https://www.npmjs.com/package/node-uuid) module is broken and insecure (using an unreliable random source), and should be replaced by the [`uuid`](https://www.npmjs.com/package/uuid) fork.

I've listed more details at broofa/node-uuid#118.

**Comment by avidas** [comment]
@joepie91 thanks for reporting this! We will look into this.

**Comment by avidas** [comment]
Our use case for node-uuid does not require a crypotographically secure uuid at this point, so this may not be an issue for us right now. However if that changes, we will definitely refer back to this.

**Comment by joepie91** [comment]
Would it not be advantageous to replace the dependency anyway, given that it should be a drop-in replacement?

Otherwise, once the usecase changes, it's possible that the implementor forgets to replace the dependency - they may not be aware of the issue, or it may simply have escaped their attention. That would seem like an unnecessary risk to take.

**Comment by avidas** [comment]
That is definitely a valid point. My concern with going to the fork route is that you cannot file issues against it and adoption is not clear. Have you tried submitting a PR to the node-uuid repo/ know if the fork might get merged at some point?

**Comment by joepie91** [comment]
According to [npm statistics](https://www.npmjs.com/package/uuid), adoption is sufficient. I have not submitted a PR (as I don't maintain the fork, and there's no point duplicating effort), but I *have* created the referenced ticket - no response has been given to it, and the author of `node-uuid` seems to have gone incommunicado entirely, judging from his [contribution graph](https://github.com/broofa).

It's not clear to me why the fork doesn't allow for filing issues. I'll try to contact the author about that later today.

**Comment by avidas** [comment]
Thanks, we do really appreciate you doing that. Let us know when you have an update.

**Comment by joepie91** [comment]
The maintainer of the fork has responded; it was apparently an oversight, and issues are now enabled on it :)

**Comment by avidas** [comment]
That does look encouraging, both from the owner's responsiveness and usage on npm. I am leaning in favor of the migration now :)

**Comment by avidas** [comment]
Reopening to keep of this.

**Comment by avidas** [comment]
Closing as resolved with 1.6.3 release

**Comment by joepie91** [comment]
Excellent, thanks!
