### ISSUE TITLE
How do I utilize the Webhooks sample?

### ISSUE THREAD

**Issue by bomanimc** [paypal/PayPal-node-SDK#107]
My friend and I are hoping to work on building a systems that automatically gets transaction events from Paypal and logs it into Quickbooks. Seemingly, using some sort of a webhook would be really useful for capturing the events in real-time. I came across the Webhooks sample, but I'm not sure how to set it up, get it running, and tracking events from our Paypal account. Do you have any advice on how I can get this up and running?

**Comment by avidas** [comment]
Hey @bomanimc , 
1. I would get started with reading the docs here https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/ . This explains how to set up a webhook, what kind of events are currently supported and the format in which results come in. 

2. Basically you can register one or more urls in the developer portal which PayPal will post notifications to and you can select which events you want to get notified on. Once you have that set up, you can create e.g. a [paypal payment authorization against sandbox , approve and execute the payment](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/execute.js) and see what notifications you get.

2. If you don't have a server running yet that can receive webhooks, you can use a service such as ngrok or http://requestb.in/ initially to test sandbox webhooks.

3. The full webhook docs are here https://developer.paypal.com/docs/api/#notifications and fully supported by the node sdk. https://github.com/paypal/PayPal-node-SDK/tree/master/samples/notifications/webhooks

4. Once you start receiving webhook events, you should verify that the events are actually from PayPal and intended for you. See the [webhook entry in the usage section](https://github.com/paypal/PayPal-node-SDK#usage) for the docs on that.

**Comment by avidas** [comment]
Closing, reopen if you have further questions.
