### ISSUE TITLE
Payment email is missing from execute response

### ISSUE THREAD

**Issue by madextreme** [paypal/PayPal-node-SDK#108]
Hi
Sometimes after execution of approved payments the email field is missing from response in "payer_info". Instead of email there is "billing_address" field there.

The issue is that we don't require user to signup and login in the website in order to make a purchase. So after the purchase we're just sending generated code to buyer's email, and when the email field is missing we can't send the email.

Can you please help or give any advice?
Probably It's related to API itself, and not the client, but I couldn't find any docs about this in rest API reference. (https://developer.paypal.com/docs/api/#payerinfo-object)

Thanks
Gevorg

**Comment by avidas** [comment]
@madextreme Is this happening for payment method paypal or credit card? Also did it start happening recently or has it always been this way?

**Comment by madextreme** [comment]
@avidas In both cases there is "payment_method":"paypal" field.
Here is the response type we usually get (I removed the IDs and personal data)
```
{
   "paymentExecuteResponse":{
      "id":,
      "intent":"sale",
      "state":"approved",
      "cart":,
      "payer":{
         "payment_method":"paypal",
         "payer_info":{
            "email":,
            "first_name":,
            "last_name":,
            "payer_id":,
            "phone":,
            "country_code":
         }
      }
      ... some other stuff...
   }
}
```
And this is the response when the email field is missing
```
{
   "paymentExecuteResponse":{
      "id":,
      "intent":"sale",
      "state":"approved",
      "cart":,
      "payer":{
         "payment_method":"paypal",
         "payer_info":{
            "first_name":,
            "last_name":,
            "payer_id":,
            "phone":,
            "country_code":,
            "billing_address":{
               "line1":,
               "line2":,
               "city":,
               "state":,
               "postal_code":,
               "country_code":
            }
         }
      },
       ... some other stuff...
   }
}
```
So instead of "email" there is "billing_address" field. Looks like credit card response, but payment_method is "paypal" in both cases.

**Comment by louiecaulfield** [comment]
I'm afraid this is not related to the node implementation. I'm experiencing exactly the same issue with some payments using the [ruby sdk](https://github.com/paypal/PayPal-Ruby-SDK). I've dropped a support request with paypal.

**Comment by davidofferman** [comment]
This issue exists even when calling the REST API directly without the SDK. Sometimes the e-mail address is missing from the lookup and sometimes from the payment execute. I've been getting this issue a lot lately.

Payment Lookup (Before execute)
```
payer_info
(
   [email] => 
   [first_name] => PayPal Israel
   [last_name] => Buyer
   [payer_id] => AAAAAAAAA
   [phone] => 050-000-0000
   [country_code] => IL
)
```
Payment Execute
```
payer_info 
(
   [email] => paypal-il-buyer@example.com
   [first_name] => PayPal Israel
   [last_name] => Buyer
   [payer_id] => AAAAAAAAA
   [phone] => 050-000-0000
   [country_code] => IL
)
```

**Comment by avidas** [comment]
@louiecaulfield you are right, this is an issue with the api. What is happening is that during the guest checkout flow, when instead of logging into the paypal account, the user actually puts in their credit card information the email field is currently not being returned as part of the REST response. @louiecaulfield you mentioned that you sent a support request to paypal, did they give you any tracking/ticket number of any sort?

**Comment by avidas** [comment]
We filled an internal issue [PPPLMER-5257] to keep track of this issue.

**Comment by louiecaulfield** [comment]
I haven't heard back from paypal.

Where did you file the issue? I didn't receive any tracking information for my issue.

**Comment by louiecaulfield** [comment]
I filed the issue again on paypal-techsupport.com and received the following response (thusfar)

>Thank you for contacting PayPal Merchant Technical Support.
>
>I've ran a test REST API payment and noticed that the email address is not returned in the payer_info structure in the response of a payment.execute(). I will further follow up regarding this issue on my end and will update this ticket again with additional details. 
>
> If you have any further questions/concerns, please reply back directly to this ticket.
>
> Sincerely,
> Venkata
> Merchant Technical Support
> PayPal

**Comment by avidas** [comment]
I filled it against Merchant Technical Support. You reply and ask if there is an issue tracking number they can share, but that is not absolutely necessary.

**Comment by madextreme** [comment]
@avidas Thanks a lot for you help. Let's see how it goes :)

**Comment by louiecaulfield** [comment]
I got this response after mentioning the github issue

>Thanks for the information. I did not file a new internal issue, instead, I will keep monitoring PPPLMER-5257(which was opened by Avi Das) and will make sure this bug is fixed ASAP. 
>
>Thanks,
>Venkata

**Comment by louiecaulfield** [comment]
Any update from your side? I haven't heard anything back from paypal.

**Comment by avidas** [comment]
The issue has been identified and there is ongoing work currently to make sure that we can provide a solution in a way that is compatible. We will keep updating here.

**Comment by louiecaulfield** [comment]
It's been 3 months now, have you heard anything?

How come this issue is not big enough for them to fix? Would there be a way then to circumvent it?

**Comment by prashshah** [comment]
The fix is being worked on and we expect to release it soon. We will update as soon as we hear more.

**Comment by prashshah** [comment]
The fix has been deployed and the email is not being returned.

**Comment by madextreme** [comment]
Thanks a lot for your help!

**Comment by louiecaulfield** [comment]
We're seeing this issue quite often again. Anyone else on this discussion noticing the same?

**Comment by johannesstricker** [comment]
I'm having the exact same issue. On credit card checkouts, the API response does not include an email field.

**Comment by mvallerie** [comment]
Same issue here. No email in response following a CC checkout on live environment.

**Comment by johannesstricker** [comment]
@Skai @mvallerie Maybe [this](https://github.com/paypal/PayPal-REST-API-issues/issues/268#issuecomment-440993875) helps?

I'm doing the `payment.execute()` client-side, so I just pass the email from the response (it's included in there, somehow) to my backend and if the email field is missing for the `payment.get()` call, then I just use the one that was passed in instead.

**Comment by mvallerie** [comment]
@johannesstricker Yep I ended up doing that way. Thanks for the information :) .

**Comment by Skai** [comment]
@johannesstricker @mvallerie Thank you for info! 👍
