### ISSUE TITLE
Suggestion on which method to use for this flow

### ISSUE THREAD

**Issue by andrewvmail** [paypal/PayPal-node-SDK#110]
I'm building a system where a users can pay them self out of credits they acquired from doing some offer in an app. Currently I have everything working using batch payment except when paying out the user when the user  if the user enter in a not valid paypal I will get an error back from the api. Is there a way I can check if a given email address is a correct paypal email address ?

Thanks
Andrew

**Comment by pp-randy** [comment]
Hi Andrew,

I am not familiar with a way to check if an email address is valid with the REST API. The error from your payout indicates that the email address is invalid?  Could you leverage this error response for your purposes? What are your plans for when the user does not have a PayPal email address? 

REST Options: Login with PayPal could be used to obtain a users PayPal email address. 

With the Classic Adaptive Account API you possibly could also leverage https://developer.paypal.com/docs/classic/api/adaptive-accounts/GetVerifiedStatus_API_Operation/.  This could have some vetting for its application request that would need to be considered.

**Comment by andrewvmail** [comment]
I could do that but I prefer doing it before that method hits.

I think thats a good idea I can get them to login via paypal first to
obtain the paypal email address.

Thanks so much

Andrew

**Comment by avidas** [comment]
Closing, reopen if you have further questions.
