### ISSUE TITLE
Approval url for express checkout is not for sandbox if I am in sandox mode

### ISSUE THREAD

**Issue by henev** [paypal/PayPal-node-SDK#111]
Hi

When I am in sandbox mode and I send payment create request for paypal express checkout, in the links object in the response, for approval_url I get an url that is redirecting to paypal, not to sandbox.paypal.

When I open that url it says "Your session has ended", but if I add sandbox to the url it opens just fine.

Any ideas?

Thanks in advice :)

**Comment by thirtified** [comment]
Hi,

this is a current issue with PayPal's Sandbox environment, not with the Node SDK. The issue has been raised internally and the teams are working on a fix. Please check again later – and sorry not to have better news for you at the moment.

\- Julian

**Comment by jaypatel512** [comment]
The fix has been released, and now it should be back to normal. Closing the issue.
