### ISSUE TITLE
No details when error "Response Status : 400" is thrown

### ISSUE THREAD

**Issue by wallslide** [paypal/PayPal-node-SDK#112]
We are using a two-step authorization and capture workflow to capture customer payments (of payment type ```paypal```). I've been seeing ```Response Status : 400``` errors pop up occasionally when we try to run ```payment.execute```.  Unfortunately the error object has no additional information beyond that message. I explicitly log ```error.information_link``` and ```error.details```, but they are both undefined in the log. I should mention that for the majority of our customers, everything works fine.

Today I was able to investigate further since I was able to associate a paymentId with one of the errored transactions. I used curl against this endpoint:  ```https://api.paypal.com/v1/payments/payment/<PAYMENT-ID>```, and discovered that the payment had the following properties:
```javascript
"intent": "authorize",
  "state": "failed",
```
It looks like paypal refused to authorize a payment for a customer, and then threw an error when we tried to verify that authorization. It would really help if the error object contained some message regarding the reason for the 400 error.

**Comment by avidas** [comment]
Hey @wallslide , could you possibly post the curl command that you used and the full response that you received? (Please do not post any private information such as card details or client id/secret).

**Comment by wallslide** [comment]
curl Command:
```
curl -v -X GET https://api.paypal.com/v1/payments/payment/<Payment-ID> \
  -H "Content-Type:application/json" \
  -H "Authorization: Bearer <Access Key>"
```

curl Response:
```json
{
  "id": "<Payment-ID>",
  "intent": "authorize",
  "state": "failed",
  "cart": "<Cart-ID>",
  "payer": {
    "payment_method": "paypal",
    "status": "UNVERIFIED",
    "payer_info": {
      "email": "<Customer Email>",
      "first_name": "<Customer First Name>",
      "last_name": "<Customer Last Name>",
      "payer_id": "<Payer-ID>",
      "phone": "<Customer Phone>",
      "country_code": "US"
    }
  },
  "transactions": [
    {
      "amount": {
        "total": "20.51",
        "currency": "USD"
      },
      "payee": {
        "email": "<Company Email>"
      },
      "description": "<Description>",
      "related_resources": [],
      "notify_url": "<Notify URL>",
      "coupled_group": 0
    }
  ],
  "create_time": "2015-10-06T02:57:22Z",
  "update_time": "2015-10-06T02:57:22Z",
  "links": [
    {
      "href": "https://api.paypal.com/v1/payments/payment/<Payment-ID>",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.paypal.com/v1/payments/payment/<Payment-ID>/execute",
      "rel": "execute",
      "method": "POST"
    },
    {
      "href": "https://www.paypal.com//cgi-bin/webscr?cmd=_express-checkout&token=<Token>",
      "rel": "approval_url",
      "method": "REDIRECT"
    }
  ]
}
```

**Comment by wallslide** [comment]
In some cases we also immediately capture payment from a customer. Today I found a situation in which we tried to immediately capture payment, only to get the `Response Status : 400` error that I've been seeing occasionally. When I followed up with the curl command, I got the following response:

curl command: 
```
curl -v -X GET https://api.paypal.com/v1/payments/payment/<Payment-ID> \
  -H "Content-Type:application/json" \
  -H "Authorization: Bearer <Access Key>"
```

response:
```json
{
  "id": "<Payment-ID>",
  "intent": "sale",
  "state": "failed",
  "cart": "<Cart-ID>",
  "payer": {
    "payment_method": "paypal",
    "status": "VERIFIED",
    "payer_info": "<Payer Info Obj {}>"
  },
  "transactions": [
    {
      "amount": {
        "total": "10.22",
        "currency": "USD"
      },
      "payee": {
        "email": "<Company Email>"
      },
      "description": "<Description>",
      "related_resources": [],
      "notify_url": "<Notify Url>",
      "coupled_group": 0
    }
  ],
  "create_time": "2015-10-07T17:57:59Z",
  "update_time": "2015-10-07T17:57:59Z",
  "links": [
    {
      "href": "https://api.paypal.com/v1/payments/payment/<Payment-ID>",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.paypal.com/v1/payments/payment/<Payment-ID>/execute",
      "rel": "execute",
      "method": "POST"
    },
    {
      "href": "https://www.paypal.com//cgi-bin/webscr?cmd=_express-checkout&token=<Token>",
      "rel": "approval_url",
      "method": "REDIRECT"
    }
  ]
}
```

**Comment by tomwhipple** [comment]
@wallslide given that this is happening only occasionally, I think your best course of action is to make sure the response (with headers, notably 'PayPal-Debug-Id') is being logged. Then please work with [PayPal Merchant Support](https://www.paypal-techsupport.com/app/ask) to track down the specific issue.

Unfortunately the SDK team does not have the ability to look up account specific information.

**Comment by wallslide** [comment]
My guess is that every time a payment authorization or sale fails, I am getting a "Response Status : 400" error. I only occasionally see the error, because customers' authorizations/payments only fail occasionally. Since the errors fail to include any details however, I don't know that this is absolutely the case. The problem is that the error object contains no details other than the very generic message "Response Status : 400".

Is there a way to log the headers without setting the NODE_ENV environmental variable to 'development'?

**Comment by avidas** [comment]
Hey @wallslide setting NODE_ENV to development is the current best way to get access to the headers at an sdk level, although with the sdk being open source you can certainly modify it to add logging temporarily.

**Comment by wallslide** [comment]
I've resolved the problem. It was because in some places in my code, I didn't realize that the `details` and `information_link` related to an `error` are located at `error.response.details` or `error.response.information_link`. Now I am able to get the specific error message being thrown, and can write code that responds accordingly.  Thank you for your time. Hopefully someone else can learn from my mistake :)
