### ISSUE TITLE
Return URL

### ISSUE THREAD

**Issue by hamidsani** [paypal/PayPal-node-SDK#115]
I'm trying to add paypal here sdk to my android app and wanted to use this on heroku as mid-tier server. Now i'm a bit confused as the whole process works and some clarification on the variables would be greatly appreciated. Just to double check I have root url set to the heroku server address (http://example.herokuapp.com), the APP_REDIRECT_URL is set to (appname://ouath). Then I created an app in the paypal developer websites and set the return url to heroku server address (http://example.herokuapp.com). 

With these parameters my app tries to login and gets the following error "Relying Party Validation error: redirect_url provided in the request.." I assume that is caused by the redirect and return url matching but I don't exactly understand how that works. I know normally in a webapp the return url would point to a webpage but I how would take work on an android app?

**Comment by ppmtscory** [comment]
@hamidsani are you simply trying to use the mid-tier server for the authentication piece?  If so, there's a specific Node sample server for that located [here](https://github.com/paypal/paypal-retail-node) and it even comes complete with it's own "Deploy to Heroku" button.  Please post any issues you have, specific to that, on that repo.

**Comment by hamidsani** [comment]
Okay, Thank you.
