### ISSUE TITLE
Delete or cancel created payment before execution

### ISSUE THREAD

**Issue by bolau** [paypal/PayPal-node-SDK#118]
Hi,
I'm integrating PayPal Plus with my custom shop using the Node SDK. If a customer wants to go to checkout, I create a payment in order to get the PPPlus payment wall. Now, if the customer wants to make changes to the cart before executing the payment, she can go back and do that. 
This invalidates the payment, since PATCH cannot update the cart (is that correct?)
When the customer is fine with the changes, she goes back to checkout, and I create a new payment. But what happens with the old one? How can I delete or invalidate this, or should I just leave it floating around?

Thanks for any help
Boris

**Comment by ppmtscory** [comment]
You are correct that you can only PATCH a Payment prior to redirecting to the `approval_url` so creating a new payment would be accurate here.  The "EC-xxxxxxxx" token that's included in the `approval_url` is only valid for 3 hours so it can just be left floating around.  There's no API call to cancel or invalidate said token anyway, that I'm aware of.
