### ISSUE TITLE
Getting error while using node paypal sdk "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by mukulgupta2507** [paypal/PayPal-node-SDK#119]
Hi @ppmtscory @avidas,

I'm getting following error while using sample examples mentioned here: https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_plans/create.js. 

```
	        return callback(null, billingPlan.id);
	               ^
TypeError: undefined is not a function
    at /home/mukul/scrub/server/payments/paypal/paypal.controller.js:241:17
    at IncomingMessage.<anonymous> (/home/mukul/scrub/node_modules/paypal-rest-sdk/lib/client.js:131:13)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
Following is my code:

```
function createBillingPlan(planDesc, planAmount, planFrequency, planName, planCurrency, callback) {	
	var billingPlanAttributes = {
	    "description": planDesc,
	    "merchant_preferences": {
	        "auto_bill_amount": "yes",
	        "cancel_url": CANCEL_URL,
	        "initial_fail_amount_action": "continue",
	        "max_fail_attempts": "1",
	        "return_url": RETURN_URL
	    },
	    "name": planName,
	    "payment_definitions": [
	        {
	            "amount": {
	                "currency": "USD",
	                "value": 25
	            },
	            "charge_models": [
	                {
	                    "amount": {
	                        "currency": "USD",
	                        "value": 2
	                    },
	                    "type": "SHIPPING"
	                },
	                {
	                    "amount": {
	                        "currency": "USD",
	                        "value":27
	                    },
	                    "type": "TAX"
	                }
	            ],
	            "cycles": "0",
	            "frequency": frequency,
	            "frequency_interval": "1",
	            "name": planName,
	            "type": "REGULAR"
	        },
	        {
	            "amount": {
	                "currency": "USD",
	                "value": "0"
	            },
	            "cycles": "1",
	            "frequency": "MONTH",
	            "frequency_interval": "1",
	            "name": "Trial",
	            "type": "TRIAL"
	        }
	    ],
	    "type": "INFINITE"
	};

	paypal.billingPlan.create(billingPlanAttributes, function (error, billingPlan) {
	    if (error) {
	    	console.log(error);
	        return callback(error);  // This is causing error
	    } else {
	        console.log("Create Billing Plan Response");
	        console.log(billingPlan);
	        return callback(null, billingPlan.id); // this is causing error
	    }
	});
}
```

Any idea how can I resolve the issue ?

Thanks

**Comment by avidas** [comment]
Hey @mukulgupta2507, I am going to take a look at this issue soon and get back to you

**Comment by mukulgupta2507** [comment]
@avidas I'll be waiting for your response on this. Also, the repo examples which you have shared, it doesn't use any callback. I think examples should be modified so as to handle callback because in common scenarios, people generally use functions for modularity and as such they will surely want to return their results to the caller function.

**Comment by mukulgupta2507** [comment]
@avidas Just one quick question. Is this a bug in my code or in the node package ?

**Comment by avidas** [comment]
What version of node are you on as well @mukulgupta2507 ?

**Comment by mukulgupta2507** [comment]
I'm on node v0.12.4 but didn't get it. What does version has to do with this ?

**Comment by mukulgupta2507** [comment]
ok..so I'm able to solve the above issue but ran into another problem..While using create billing agreement, I'm getting following error:

```
Agreement start date is required, should be valid and greater than the current date. Should be consistent with ISO 8601 Format
```

Following are my response:

```
{ [Error: Response Status : 400]
  response: 
   { name: 'VALIDATION_ERROR',
     details: [ [Object] ],
     message: 'Invalid request - see details',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR',
     debug_id: '7a7beae680cd7',
     httpStatusCode: 400 },
  response_stringified: '{"name":"VALIDATION_ERROR","details":[{"field":"start_date","issue":"Agreement start date is required, should be valid and greater than the current date. Should be consistent with ISO 8601 Format"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"7a7beae680cd7","httpStatusCode":400}',
  httpStatusCode: 400 }
```

Following is my code:

```
function createBillingAgreement(billingPlanId, callback) {

	var startDate = new Date();
	startDate.setHours(startDate.getHours() + 24); // PayPal expects start date to be after current date in ISO8601 Date Format
	console.log(startDate.toISOString());
	var billingAgreementAttributes = {
	    "name": "Payment Agreement",
	    "description": "Agreement for payment on XYZ",
	    "start_date": startDate.toISOString(),
	    "plan": {
	        "id": billingPlanId
	    },
	    "payer": {
	        "payment_method": "paypal"
	    }
	};

    paypal.billingAgreement.create(billingAgreementAttributes, function (error, billingAgreement) {
        if (error) {
            return callback(error);
        } else {
            console.log("Create Billing Agreement Response");
            var approvalUrl = undefined;
            var paymentToken = undefined;

            for (var index = 0; index < billingAgreement.links.length; index++) {
                if (billingAgreement.links[index].rel === 'approval_url') {
                    approvalUrl = billingAgreement.links[index].href;
                    console.log("For approving subscription via Paypal, first redirect user to");
                    console.log(approvalUrl);

                    console.log("Payment token is");
                    paymentToken = url.parse(approvalUrl, true).query.token;
                    console.log(paymentToken);
                    req. session.paymentToken = paymentToken;
                }
            }

            return callback(null, { 'redirectUrl': approvalUrl});
        }
    });
}
```

This is my start_date: 2015-11-07T18:17:33.535Z Can anyone please tell me what is the actual issue over here ?

**Comment by ppmtscory** [comment]
@mukulgupta2507 you need to remove the milliseconds from your value.  If you pass just up to the seconds, you should be good.  `"start_date": "2015-11-07T18:17:33Z"`

**Comment by mukulgupta2507** [comment]
@ppmtscory 
Thanks that worked like a charm :) I'm using a sandbox test account but the balance is 0 USD. Is there anyway by which I can test the actual payment flow ? 

What I'm able to do so far:
1. Create billing plan
2. Activate the billing plan
2. Create billing agreement

Now, once payment is successful, paypal should redirect to my return url but somehow it's getting redirected to cancel_url. Any idea why is it so ? May be because test sandbox accounts are with 0 USD balance ?

Please suggest a work around to complete payment flow.

Thanks

**Comment by ppmtscory** [comment]
Yes please try a sandbox account with balance and/or other funding sources.  If you run into issues such as that afterwards, our [Merchant Tech Support](https://paypal-techsupport.com/app/ask) team would probably be best able to help you since this issue is not specific to the SDK.  They'll be able to look at the logs for your attempt to determine what may be going wrong.  When contacting them, be sure to provide the accounts you are using in the sandbox as well as relevant API request/responses.

**Comment by mukulgupta2507** [comment]
One last doubt, how can I add balance to my sandbox account ??

**Comment by ppmtscory** [comment]
The easiest way would be to simply create a new sandbox account from within the developer portal and add a balance to it during the creation process.

**Comment by mukulgupta2507** [comment]
@ppmtscory Merchant Tech support link is not working for me. Can you please check the link again ?

**Comment by ppmtscory** [comment]
Ah, that's my bad, I failed to include the www.  Go [here](https://www.paypal-techsupport.com/app/ask).

**Comment by mukulgupta2507** [comment]
@ppmtscory @avidas 

I was following this sample code for cancelling a billing agreement https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/cancel.js

But don't know why is it not working. Once an agreement is cancelled, an api call for fetching the current status of billing agreement results in an error:

https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/cancel.js#L21

I get an Invalid template Id error. any idea what can be the possible issue ?

**Comment by mukulgupta2507** [comment]
Also, I want to add company name/logo on the paypal payment page. I saw this https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment_experience/web_profile/create.js

Any idea how can I use this api to serve my purpose ? Also, if I use above mentioned api, do i need to call it for each of the payment redirection ? or is this called one time ? Also, is there anyway which I can use in dashboard to make this happen ?

Looking forward for your response

**Comment by avidas** [comment]
Hey @mukulgupta2507, you can display your logo and customize checkout using payment experience APIs. I would recommend looking at https://developer.paypal.com/docs/integration/direct/rest-experience-overview/ . You only need to create the experience profile once by calling the API, and on subsequent payment create calls pass in the experience_profile_id to ensure custom checkout for users.

**Comment by avidas** [comment]
Closing as the original issue has been resolved.
