### ISSUE TITLE
Webhook event verification

### ISSUE THREAD

**Issue by Gargol** [paypal/PayPal-node-SDK#125]
Hi guys. Have a question about webhook verification behavior. I am trying to test batch payout hook  in sandbox environment and am getting invalid resource id response all the time, when verifying request through `notification.webhookEvent.getAndVerify` method. This is the response that is being received: 
```json
{ 
    "name":"INVALID_RESOURCE_ID",
    "details":[],
    "message":"Resource id is invalid","httpStatusCode":404
}
```

Is this a correct behavior? Or I'm missing something? Thanks!

**Comment by bluk** [comment]
The new recommended way to verify webhook event data is [documented here](https://github.com/paypal/PayPal-node-SDK/wiki/Webhook-Validation). The next release should deprecate the `getAndVerify` function.

In some cases, the webhook event data may be sent slightly before it can be GET from the webhook event API. In this scenario, the recommendation is for your webhook event handler to respond with a 503 response status code. Then, the PayPal service will retry your webhook again at a later time. The documentation linked has a more detailed example. Hope that helps! If you have any further questions, please leave a comment. Thanks.

**Comment by Gargol** [comment]
Thanks you!

**Comment by Gargol** [comment]
Just tested with a method described on the wiki page and tried verification with `paypal.notification.webhookEvent.get` method. It only return 404  ` Error: Response Status : 404` and the hook is never called back for retry. Tried both responses 503 as in the wiki and 400, both give the same result. Any thoughts?

**Comment by bluk** [comment]
The event retry call is not immediate (it's based off a backing off algorithm). If you don't see a retry within the hour, please comment back.

**Comment by Gargol** [comment]
3 hours after the hook did a first call, didn't call again.

**Comment by bluk** [comment]
Looking into this. Thanks for reporting back.

**Comment by bluk** [comment]
The webhook retries should be fixed now in PayPal API sandbox (live production should have worked all the time). If the webhook returns a non-2xx HTTP response code, then there should be a series of retries. In my test app, the first retry occurs within a few minutes. If it still isn't working, please leave a comment. Thanks!
