### ISSUE TITLE
Use for "digital goods"

### ISSUE THREAD

**Issue by whitecolor** [paypal/PayPal-node-SDK#126]
Can this module be use for creating "digital goods" payments?

**Comment by bluk** [comment]
You should be able to accept payments for "digital goods" (vs. "physical goods") using this SDK.

**Comment by whitecolor** [comment]
@bluk It tried to create payment with custom profile with `input_fields.no_shipping` (as it stated in docs) set to `1`. It doesn't work, can not open payment for created token using client DGFlow library for processing digital goods (when windows is opened that there is an error that payment can not be processed, though it can be using standard express checkout way). Payment created using old NVP/SOAP API works (if to set item category to `digital`).

Do you have any suggestions on that?

**Comment by bluk** [comment]
Ahh. I see that you meant the [Digital Goods for Express Checkout](https://developer.paypal.com/docs/classic/express-checkout/digital-goods/IntegratingExpressCheckoutDG/).

The node SDK is meant for the REST API (not the NVP/SOAP API). Unfortunately, it isn't supported with the `Digital Goods for Express Checkout`. You can try the [Integration Wizard](https://devtools-paypal.com/integrationwizard/) for some help generating the Java/PHP code you would need.

**Comment by whitecolor** [comment]
Ok, I use NVP/SOAP api currently, do you know when support with REST API can be expected?

**Comment by bluk** [comment]
I don't have any timeline to share unfortunately.

Is there a particular feature about the Digital Goods flow that you need which is not present in the REST API today?

If you're looking for a JavaScript drop-in, you may want to check out [Braintree Payments](https://www.braintreepayments.com) which is part of PayPal. They have the ability to accept payments using a PayPal account and many other payment methods as well.

**Comment by whitecolor** [comment]
@bluk Yes I know, I believe paypal is not in a hurry with such things because of braintree, but we don't have it available in our country yet.
