### ISSUE TITLE
Iam using PayPal sample application. it gives UNKOWN_ERROR with card number 5555555555554444 , please suggest what to do??

### ISSUE THREAD

**Issue by AnkushJaral** [paypal/PayPal-node-SDK#127]

**Comment by bluk** [comment]
I assume you are referring to the [rest-api-sample-app-nodejs](https://github.com/paypal/rest-api-sample-app-nodejs) sample application. I tried running the sample and the MasterCard test card number `5555555555554444` seemed to work. I used mastercard as the type, random 3 digit CVV2, and a future expire month and year.

Are you able to use any other test cards such as VISA's `4242424242424242`?

**Comment by AnkushJaral** [comment]
No, this is also not working.

**Comment by AnkushJaral** [comment]
Iam using Android sdk sample app.

**Comment by AnkushJaral** [comment]
It is giving error using Pay with Card But the transaction completes via Pay with PayPal option.

**Comment by avidas** [comment]
There have been issues in the past with sandbox from most common card numbers, the discussion here could be useful to you http://stackoverflow.com/questions/21537295/test-credit-card-numbers-for-use-with-paypal-sandbox

**Comment by pp-randy** [comment]
The common testing card numbers do tend to usually not work in the sandbox.  However, a fake credit card number should work as long as it passes the luhn algorithm.

**Comment by pp-randy** [comment]
You can find a Credit Card number here https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413

Scroll to item 4 in the above FAQ and click the Generate CC Number button.

**Comment by pp-randy** [comment]
@AnkushJaral If you have any issues using a generated card from the link in my previous response please let me know; otherwise, I am closing this issue for now.

**Comment by AnkushJaral** [comment]
Sir ,
Iam using Sandbox account .The onActivityResult() method of paypal Android sdk returns JSONObject with create time 2014-02-12 which is far past from current date. is it ok???

**Comment by pp-randy** [comment]
@AnkushJaral Would you be able to re-post your question under the android sdk you are using?
