### ISSUE TITLE
Plan ID is missing from retrieve agreement response

### ISSUE THREAD

**Issue by fuwaneko** [paypal/PayPal-node-SDK#128]
Subject. Docs state that ID must be there. REST API is so inconsistent.
UPD: plan.payment_definitions.name is missing too.

**Comment by ppmtscory** [comment]
There are plans to update the documentation to specifically say this (so stay tuned for that), but there are many objects that are shared among different REST API sets.  Therefore, even though the object is used, not all of the specific values may be populated.  With that being said, this Plan object is one of them that is shared.  If you look at the sample [response](https://developer.paypal.com/docs/api/#retrieve-an-agreement) of retrieving an agreement, it shows that what's included are essentially the payment details of the Plan that was used to create said agreement.

Again, there's plans to update the documentation to state this, as there are other shared objects as well.  Hopefully that will alleviate some of the confusion with what should/shouldn't be returned.
