### ISSUE TITLE
Retrieving payout payment details by transaction_id

### ISSUE THREAD

**Issue by Gargol** [paypal/PayPal-node-SDK#129]
Hi guys. Have a question about API for payments that are created from batch payouts. Is there a way to retrieve payment details by `transaction_id` in payout item like it was provided in old API ([PaymentDetails API Operation](https://developer.paypal.com/docs/classic/api/adaptive-payments/PaymentDetails_API_Operation/)) ? Or the payout items are only retreivable by it's `payout_id`?
Thanks!

**Comment by ppmtscory** [comment]
@Gargol at this time, it's not possible to use the `transaction_id` to retrieve payment details of a payout item.  You will need to use the `payout_item_id` to look up individual payout items.

**Comment by Gargol** [comment]
In that case is there some way to traverse all of my payouts and search for given transaction_id ?

**Comment by Gargol** [comment]
I'm asking because the current dev view is limited to only last 30 days, and I would like to check batches that are couple months older (but only have a transaction_id).

**Comment by ppmtscory** [comment]
You can try to use [Mass Payments Reporting](https://developer.paypal.com/docs/classic/mass-pay/integration-guide/MassPayReporting/) from within your sandbox account.  You could also attempt to use the Classic [GetTransactionDetails](https://developer.paypal.com/docs/classic/api/merchant/GetTransactionDetails_API_Operation_NVP/) API to look up the status of the specific `transaction_id`.  Keep in mind that is a Classic API call so you'll use different API credentials when making the call.

**Comment by Gargol** [comment]
Thanks mate!

**Comment by boboci9** [comment]
Hi @Gargol,

Did you try to use the Classic GetTransactionDetails API? If yes how did you use it? I am trying to achieve the same thing, getting the transaction details based on a transaction_id? Did you have any luck?

**Comment by Gargol** [comment]
Hey @boboci9! I ended up populating my `payout_item_id` fields instead, didn't want to waste time on the old API as it doesn't play that well with NodeJS.
