### ISSUE TITLE
Paypal Subscription

### ISSUE THREAD

**Issue by rajinderodz** [paypal/PayPal-node-SDK#130]
Hi,

I am implementing node-paypal.sdk for subscriptions on node js . But its not working. When i am redirect on paypal sandbox site then its showing blank page.
https://api.sandbox.paypal.com/v1/payments/billing-plans/P-4RT838856L637441AEZMRU4I
I am using following parameters.

PAYPAL_ID=AelynDATJcAAm6Mj1neyA64lP8L4IkifMmi9pPf42jBrVRYIZilHF9V49H0ZONn2uPwmsqBAyTfoYwC1
PAYPAL_SECRET=EK92ssXKYCqih4qmbJIdXlxTyKcu41vtLDpDCKzGb_sN6QEDf7Qnq678Q6QtigVSXMSDwZc2Kq5A0Evs

paypal.configure({
    mode: 'sandbox',
    client_id: process.env.PAYPAL_ID,
    client_secret: process.env.PAYPAL_SECRET
  });
  console.log(process.env.PAYPAL_ID);
  console.log(process.env.PAYPAL_SECRET);
  var billingPlanAttributes = {
		"name": "T-Shirt of the Month Club Plan",
		"description": "Template creation.",
		"type": "fixed",
		"payment_definitions": [
			{
				"name": "Regular Payments",
				"type": "REGULAR",
				"frequency": "MONTH",
				"frequency_interval": "2",
				"amount": {
					"value": "100",
					"currency": "USD"
				},
				"cycles": "12",
				"charge_models": [
					{
						"type": "SHIPPING",
						"amount": {
							"value": "10",
							"currency": "USD"
						}
					},
					{
						"type": "TAX",
						"amount": {
							"value": "12",
							"currency": "USD"
						}
					}
				]
			}
		],
		"merchant_preferences": {
			"setup_fee": {
				"value": "1",
				"currency": "USD"
			},
			"return_url": 'http://localhost:3000/subscription/success',
			"cancel_url": 'http://localhost:3000/subscription/cancel',
			"auto_bill_amount": "YES",
			"initial_fail_amount_action": "CONTINUE",
			"max_fail_attempts": "0"
		}
	};
	
    
   
	paypal.billingPlan.create(billingPlanAttributes, function (error, billingPlan) {
		if (error) {
			console.log(error);
			throw error;
		} else {
			req.session.paymentId = billingPlan.id;
			var BillingID = billingPlan.id;
			var links = billingPlan.links;
			console.log("Create Billing Plan Response");
			console.log(billingPlan);
			for (var i = 0; i < links.length; i++) {
				if (links[i].rel === 'self') {
					res.render('paypal', {
						approvalUrl: links[i].href
					});
				}
			}
		}
	});

**Comment by bluk** [comment]
The `self` is not the approval HTML web page that should be presented from the billing plan.

You can see a [billing agreement/plan creation full example](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/create.js).

You can see the documentation for [billing plan creation](https://developer.paypal.com/docs/integration/direct/create-billing-plan/) (be sure to activate it) and [billing agreement creation/approval](https://developer.paypal.com/docs/integration/direct/create-billing-agreement/).

**Comment by bluk** [comment]
Basically, need to create a billing plan once, activate it, and then create a billing agreement for each user which will have the billing approval URL.

**Comment by rajinderodz** [comment]
When i have created billing plan and billing agreement then i got approval URL. When i am using that approval URL for payment then payment done successfully but not showing in pay-pal account in buyer or business account. Please let me know what is the reason behind this. i am doing testing on sandbox.

**Comment by bluk** [comment]
@rajinderodz After you created the billing agreement and the buyer approved it, did you get the payment token and execute the billing agreement? There is a [billing agreement execute sample](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/execute.js). You get the payment token as a query parameter on the redirect back to your site (you have the redirect URL in your prior example code set to `http://localhost:3000/subscription/success` which may work locally but will not work on a real site).

**Comment by rajinderodz** [comment]
@bluk Thanks your response. But i want to confirm from you if payment done on pay-pal site and redirect on success page. Then we need to run execute URL for displaying transaction in pay-pal account. or need other way to display transaction in pay-pal account?

**Comment by bluk** [comment]
After executing, the transactions should show up in your test account (in sandbox.paypal.com using your test personal buyer account). For instance, after executing the examples in the documentation, you should see something like:

![screen shot 2016-01-12 at 10 38 15 am](https://cloud.githubusercontent.com/assets/94150/12269815/dcb55dca-b918-11e5-906d-02fa7bd96568.png)

**Comment by rajinderodz** [comment]
@bluk Thank you very much for your help. its working now.

**Comment by bluk** [comment]
Great! Glad it works!
