### ISSUE TITLE
PayPal billing agreements REST API - how to start immediately

### ISSUE THREAD

**Issue by rajinderodz** [paypal/PayPal-node-SDK#131]
Hi,

 Please let me know how we can start subscription immediately in paypla rest api in node js billing Plan.

Thanks

**Comment by bluk** [comment]
An [example for creating a billing plan and then agreement](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/create.js) is in the samples repository. If you set the [start_date](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/create.js#L98), and then execute the billing agreement (after the consumer approves the billing agreement for PayPal payments) , the subscription should start appropriately.

**Comment by bluk** [comment]
You can also see the issue at https://github.com/paypal/PayPal-PHP-SDK/issues/180 for further information (and some potential limitations and workarounds). Please leave a comment if there is still a question/issue. Thanks.

**Comment by clarkejm** [comment]
@bluk even if you set the start_date and the customer (or sandbox account) approves immediately then it seems Paypal doesn't allow the start_date to be anything other than the next UTC 08:00 time with the next_billing_date at UTC10:00. 
Even sending PATCH requests doesn't change it. Surely this is a bug?

**Comment by pp-randy** [comment]
My findings on start_date here might be helpful: https://github.com/paypal/PayPal-Java-SDK/issues/207#issuecomment-255794267

**Comment by igorbelykh86** [comment]
I'm using setup fee to charge user immediately and set the start date +1 month from now
