### ISSUE TITLE
Sir Iam using paypal sandbox account with android sdk . Its onActivityResult function return JSONObject with old date time like 12-02-2014 which is far past from current date. is it ok??? 

### ISSUE THREAD

**Issue by AnkushJaral** [paypal/PayPal-node-SDK#132]

**Comment by bluk** [comment]
is there a particular action/flow you are using? Also, what field in the JSONObject has the old date?

You may also want to post your issue to https://github.com/paypal/PayPal-Android-SDK/issues since there may be other people who have encountered this issue who may be able to help.

**Comment by AnkushJaral** [comment]
[{"client":{"environment":"mock","paypal_sdk_version":"2.1.0","platform":"Android","product_name":"PayPal-Android-SDK"},"response":{"create_time":"2014-02-12T22:29:49Z","id":"PAY-6RV70583SB702805EKEYSZ6Y","intent":"sale","state":"approved"},"response_type":"payment"}]

**Comment by AnkushJaral** [comment]
this response is generated every time

**Comment by bluk** [comment]
I would check to see if you're using the `PayPalConfiguration.ENVIRONMENT_NO_NETWORK` in your `PayPalConfiguration`. The response seems to indicate it's the mock environment which returns a stubbed response every time.

You should use the `PayPalConfiguration.ENVIRONMENT_SANDBOX` for sandbox. Check the [Android mSDK Sample Code](https://github.com/paypal/PayPal-Android-SDK/blob/master/docs/single_payment.md#sample-code) for more information.

**Comment by AnkushJaral** [comment]
Thank you ..

**Comment by AnkushJaral** [comment]
soo much sir
