### ISSUE TITLE
Billing Plan IPN

### ISSUE THREAD

**Issue by funnybones** [paypal/PayPal-node-SDK#133]
Hello,

I am building an app with subscription, but payment through credit cards, not paypal. I have read on the documentation that 'execute' step is automatically done for these payments. I have configured in my account the IPN Listener, however, whenever I make a payment in sandbox nothing is sent to my server. Can I configure dynamic the IPN ? Currently I get an error when I am sending the 'notify_url' for the billing plan. If not, how can I test in sandbox since the sandbox ipn simulator does not have recurring payments ?

Thanks,
Alex.

**Comment by bluk** [comment]
@funnybones I'm not sure what is possible, so please contact [Merchant Technical Support](https://www.paypal-techsupport.com) to find out the best way to integrate.
