### ISSUE TITLE
node js paypal rest sdk 401 error

### ISSUE THREAD

**Issue by Zhairgling** [paypal/PayPal-node-SDK#140]
Hi I'm using nodejs and paypal-rest-sdk "^1.6.0" with express 4.13.1 .

When i make live payement i have this error :

 { [Error: Response Status : 401]
  response:
   { error: 'invalid_client',
     error_description: 'Client Authentication failed',
     httpStatusCode: 401 },
  httpStatusCode: 401 }
But when i use the sandebox host, I don't have any error.

does anybody have an odea of what i doing wrong ?

ps: sorry for my bad english, i do my best ;)

**Comment by bluk** [comment]
Are you using the correct credentials for the live production site? Be sure you are using the correct client ID and secret which is usually what's wrong for 401s.

Also, if you set the `NODE_ENV=development` environment variable and run your script, can you get a PayPal-Debug-ID?

**Comment by Zhairgling** [comment]
I'm using the credentials givern in the dashboard in the section 'live'.

when i set the NODE_ENV=development environment variable and run my script, i get a paypal-debug id.

**Comment by bluk** [comment]
Sorry, can you give the value of the PayPal-Debug-ID for your request? The PayPal-Debug-ID is used to identify request/responses.

**Comment by Zhairgling** [comment]
paypal-debug-id: e50862eee9950

thanks for help

**Comment by bluk** [comment]
The `e50862eee9950` request seems to be hitting Sandbox to login. Are you sure that your configuration is something like:

```
paypal.configure({
  'mode': 'live', //sandbox or live
  'client_id': 'your live client id',
  'client_secret': 'your live client secret'
});
```

(Please do *not* share your real client ID and client secret).  Just wanted to make sure that you have `live` specified as the mode (with the live client ID and live client secret).

**Comment by Zhairgling** [comment]
np, i was using that 

var config = {
  "port" : 3000,
  "api" : {
    "host" : "api.paypal.com",
    "port" : "",            
    "client_id" : "",  
    "client_secret" : "" 
  }
}
paypal.configure(config.api);


it's working now.

thank you a lot man :)

**Comment by SumanSingh4** [comment]
Hii Zhairgling,

I am also using paypal with nodejs.When I move from sandbox to live, me also getting same error. Any help how you have fixed your issue??

Its urgent, please reply as fast as possible.

Thanks.

**Comment by Zhairgling** [comment]
Sorry I haven't achieve to get this working, I have canceled my try

**Comment by SumanSingh4** [comment]
Ok Thanks
