### ISSUE TITLE
Can't access sandbox - Client Authentication failed

### ISSUE THREAD

**Issue by RayKahn** [paypal/PayPal-node-SDK#141]
Hi,
I am trying to integrate paypal-rest-sdk with my node application. The following is my code:

`var paypal = require('paypal-rest-sdk');`
`paypal.configure(Config.paypal_info.api);`

Where api is:

`'api': {`
`'host' : 'api.sandbox.paypal.com',`
`'mode': 'sandbox',`
`'client_id' : 'my client id based on Business-Pro account ',`
`'client_secret' : 'client secret here'`
`}`

And my payment object is:

`var paymentJSON = {`
`"intent": "sale",`
`"payer": {`
 ` "payment_method": "paypal"`
 ` },`
` "redirect_urls": {`
 ` "return_url": Config.paypal_info.return_url,`
` "cancel_url": Config.paypal_info.cancel_url`
` },`
`"transactions": [{`
`"item_list": {`
`"items": [{`
`"name": "Activation",`
`"sku": pProviderID,`
`"price": Config.paypal_info.price,`
`"currency": "USD",`
`"quantity": 1`
`}]`
`},`
`"amount": {`
`"currency": "USD",`
`"total": Config.paypal_info.price,`
`},`
`"description": ""`
`}]`
`};`
`paypal.payment.create(paymentJSON, function (error, payment) {...});`

Yet I keep getting the following error:
{"error":"invalid_client","error_description":"Client Authentication failed"}

The rest of error message is: 
{"Authorization":"Basic cmF5LmthaG4tZmFjaWxpdGF0b3JfYXBpMS52b29temkuY29tOjVHS0RKTTZYREhGN1dCS1k=","Accept":"application/json","Content-Type":"application/x-www-form-urlencoded","Content-Length":29,"PayPal-Request-Id":"33a71ad3-c2e5-4ce8-af58-a367b70a8d5b","User-Agent":"PayPalSDK/PayPal-node-SDK 1.6.8 (node v4.2.2-x64-darwin; OpenSSL 1.0.2d)"}'
'grant_type=client_credentials'
paypal-debug-id: 56c2c2b7647f9, 56c2c2b7647f9

Can't figure out what the issue is.

Thanks in advance.

**Comment by pp-randy** [comment]
You are using your sandbox credentials? Also no extra characters in your config string?

**Comment by RayKahn** [comment]
I am using the sandbox credentials. And I don't see any extra characters in
my config either.

**Comment by RayKahn** [comment]
I was able to resolve the issue. 
It's not enough to have a developer account; I had to also create an app account (of course this is NOT clear at all). After I created an app account I used the client_id and client_secret to create a payment. Although my "app" is a web application, I think what I have done is correct. Unless someone says otherwise.

**Comment by pp-randy** [comment]
Yes you need to Create REST API app here: https://developer.paypal.com/developer/applications/

**Comment by RayKahn** [comment]
Thanks for your help.

**Comment by ompurwar** [comment]
**Use the below code in helper.js make sure to change** 

> process.env.NODE_ENV 

Reference:
[https://developer.paypal.com/docs/checkout/integrate/#replace-sandbox-credentials-with-live-credentials](url)
[https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/](url)


```

'use strict';

const checkoutNodeJssdk = require('@paypal/checkout-server-sdk');


function client() {
    return new checkoutNodeJssdk.core.PayPalHttpClient(environment());
}


function environment() {
    let clientId = process.env.PAYPAL_CLIENT_ID;
    let clientSecret = process.env.PAYPAL_CLIENT_SECRET;
    let productionBaseUrl = 'https://api.paypal.com';

    if (process.env.NODE_ENV === 'x' || process.env.NODE_ENV === 'q') {
        return new checkoutNodeJssdk.core.SandboxEnvironment(
            clientId, clientSecret
        );
    }
    if (process.env.NODE_ENV === 'p') {
        return new checkoutNodeJssdk.core.PayPalEnvironment(
            clientId, clientSecret,productionBaseUrl
        );
    }
}

async function prettyPrint(jsonData, pre = "") {
    let pretty = "";
    function capitalize(string) {
        return string.charAt(0).toUpperCase() + string.slice(1).toLowerCase();
    }
    for (let key in jsonData) {
        if (jsonData.hasOwnProperty(key)) {
            if (isNaN(key))
                pretty += pre + capitalize(key) + ": ";
            else
                pretty += pre + (parseInt(key) + 1) + ": ";
            if (typeof jsonData[key] === "object") {
                pretty += "\n";
                pretty += await prettyPrint(jsonData[key], pre + "    ");
            }
            else {
                pretty += jsonData[key] + "\n";
            }

        }
    }
    return pretty;
}

module.exports = { client: client, prettyPrint: prettyPrint };

```
