### ISSUE TITLE
Can I use paypal sdk to access payment in india ?

### ISSUE THREAD

**Issue by just4give** [paypal/PayPal-node-SDK#142]
I was able to integrate paypal sdk for a website which accepts USD ( eCommerce website in USA). I am planning to build another eCommerce website for a client in India. Website will accept payment in INR using credit cards. Wondering if I can leverage this SDK to integrate payment for an Indian eCommerce website.

**Comment by bluk** [comment]
The REST API does not currently accept direct credit card payments for India. You can find out more about which currency/country support in the [PayPal Developer site](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments).
