### ISSUE TITLE
"payment_method":"credit_card" Failing

### ISSUE THREAD

**Issue by wfayeBerman** [paypal/PayPal-node-SDK#146]
The "payment_method":"credit_card" isn't working with this nor is it working with cURL.  Here are the steps to reproduce with cURL (and by proxy this plugin)

### do an access token request

    curl https://api.sandbox.paypal.com/v1/oauth2/token \
    -H "Accept: application/json" \
    -H "Accept-Language: en_US" \
    -u "<Client-Id>:<Secret>" \
    -d "grant_type=client_credentials"

### do a payment using payment\_method:paypal

    curl -v https://api.sandbox.paypal.com/v1/payments/payment \
    -H "Content-Type:application/json" \
    -H "Authorization: Bearer <Access-Token>" \
    -d '{
      "intent":"sale",
      "payer":{
        "payment_method":"paypal"
      },
      "redirect_urls": {
        "return_url": "http://return.url",
        "cancel_url": "http://cancel.url"
      },
      "transactions":[
        {
          "amount":{
            "total":"7.47",
            "currency":"USD",
            "details":{
              "subtotal":"7.41",
              "tax":"0.03",
              "shipping":"0.03"
            }
          },
          "description":"This is the payment transaction description."
        }
      ]
    }'

### now do a payment using payment\_method:credit_card and this is the part that's not working

    curl -v https://api.sandbox.paypal.com/v1/payments/payment \
    -H "Content-Type:application/json" \
    -H "Authorization: Bearer <Access-Token>" \
    -d '{
      "intent":"sale",
      "payer":{
        "payment_method":"credit_card",
        "funding_instruments":[
          {
            "credit_card":{
              "number":"4417119669820331",
              "type":"visa",
              "expire_month":11,
              "expire_year":2018,
              "cvv2":"874",
              "first_name":"Betsy",
              "last_name":"Buyer",
              "billing_address":{
                "line1":"111 First Street",
                "city":"Saratoga",
                "state":"CA",
                "postal_code":"95070",
                "country_code":"US"
              }
            }
          }
        ]
      },
      "transactions":[
        {
          "amount":{
            "total":"7.47",
            "currency":"USD",
            "details":{
              "subtotal":"7.41",
              "tax":"0.03",
              "shipping":"0.03"
            }
          },
          "description":"This is the payment transaction description."
        }
      ]
    }'

**Comment by pp-randy** [comment]
Can you provide the error you are receiving in your response?

**Comment by wfayeBerman** [comment]
Yes, the response is here:
{"name":"INTERNAL_SERVICE_ERROR","information_link":"https://api.sandbox.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"6bdd4b6e54097"}

A few things to note:
- if you go to that information_link, you'll realize that URL doesn't exist
- if you go to the correct URL https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR it tells you to contact Merchant Technical Support
- if you call PayPal, you will be put on hold for up to 1 hour 15 minutes or more
- the PayPal engineers will tell you that they can replicate the problem and that they'll get back to you (they never call you back)

**Comment by pp-randy** [comment]
Can you test a different CC number?  You can generate one here using Step 4 at https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true

**Comment by pp-randy** [comment]
PPPLPAYPT-7022 for internal tracking with the current card number you are using

**Comment by wfayeBerman** [comment]
I finally got through to customer support (after 90 mins on hold) and I also generated a new card nubmer using the URL that you provided. 4232133287816699 for visa gave me a response and getting a random number from Get Credit Card Numbers (http://www.getcreditcardnumbers.com/generated-credit-card-numbers) also worked.

Not sure what happened (or even if the issue is resolved) but it seems to be working now.

Thanks for the investigation @pp-randy

**Comment by pp-randy** [comment]
Its a problem with how sandbox is handling that particular card number.

**Comment by wfayeBerman** [comment]
But I tried with multiple credit card numbers yesterday. Even from PayPal's
website here:
https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

Maybe add a warning to documentation?

**Comment by pp-randy** [comment]
The commonly used cards have the issue, you wouldn't face it in production however.
