### ISSUE TITLE
BillingAgreement Id not returned after creation

### ISSUE THREAD

**Issue by jchapelle** [paypal/PayPal-node-SDK#150]
Hello,

The billingAgreement id is not returned after a creation.

The api documentation specify that the id of the billingAgreement is included in the response !
https://developer.paypal.com/docs/api/#create-an-agreement

**Comment by juwlee** [comment]
Hi @jchapelle thanks for reporting. It sounds like [a known issue](https://github.com/paypal/PayPal-Ruby-SDK/issues/66). We can track it there.
