### ISSUE TITLE
samples/payment/create_with_credit_card.js broken

### ISSUE THREAD

**Issue by hofan41** [paypal/PayPal-node-SDK#154]
### General Information

- Mode (Sandbox/Live): sandbox
- PayPal-Debug-ID(s) (from any logs): dc5d3af6b7ed3
- Version of node.js used: 5.8.0
- SDK Version: 1.6.8

### Issue Description

If you run `node samples/payment/create_with_credit_card.js` you will get an error:

```
   { name: 'UNKNOWN_ERROR',
     message: 'An unknown error has occurred',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR',
     debug_id: 'dc5d3af6b7ed3',
     httpStatusCode: 400 },
  httpStatusCode: 400 }
```

**Comment by hofan41** [comment]
After further testing, it seems the test Credit Card number is the cause behind the error. When I use a real credit card number in its place, the sample creates the payment successfully. 

I tried all of the visa test credit card numbers listed at https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm and they all failed with INTERNAL_SERVICE_ERROR.

```
   { name: 'INTERNAL_SERVICE_ERROR',
     information_link: 'https://api.sandbox.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR',
     debug_id: 'b48bfc3aa708d',
     httpStatusCode: 503 },
   { name: 'INTERNAL_SERVICE_ERROR',
     information_link: 'https://api.sandbox.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR',
     debug_id: 'af3ccddd165b0',
     httpStatusCode: 503 },
   { name: 'INTERNAL_SERVICE_ERROR',
     information_link: 'https://api.sandbox.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR',
     debug_id: '1a71525e23493',
     httpStatusCode: 503 },
```

**Comment by wenbinke** [comment]
Hello, any updates on this? I got the same error.

**Comment by pp-randy** [comment]
Linking to https://github.com/paypal/PayPal-NET-SDK/issues/165

**Comment by pp-randy** [comment]
I apologize an error was encountered. You can use the Credit Card generator here on step 4 https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true&locale=en_US. Any credit card that passes Luhn algorithm can be used, so you could also use code to generate a test card number.
