### ISSUE TITLE
All config parameters?

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#159]
Where do you hide all config parameters?

In your example we see:

```
// Create config options, with parameters (mode, client_id, secret).
paypal.configure({
  'mode': 'sandbox', //sandbox or live
  'client_id': 'EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM',
  'client_secret': 'EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM'
});
```

Now I open the very first [example](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/openid_connect/openid-connect.js#L20) and suddenly I discover some other parameter `openid_redirect_uri`:

```
//set configs for openid_client_id and openid_client_secret if they are different from your
//usual client_id and secret. openid_redirect_uri is required
paypal.configure({
    'mode': 'sandbox',
    'openid_client_id': 'CLIENT_ID',
    'openid_client_secret': 'CLIENT_SECRET',
    'openid_redirect_uri': 'http://example.com'
});
```

You ignore to provide **FULL LIST** of parameters. Where to find them?

**Comment by ppmtscory** [comment]
Those are it.  Those are just samples that show that there can be two different configs for two different samples.  It's possible that you may use one set of credentials to handle your Log In With PayPal (openidconnect) stuff whereas you may use a different set of credentials to handle the other REST APIs.  If you use the same credentials, then that's fine as well.  The Log In With PayPal flow, however, has an additional parameter needed which is the redirect_uri.
