### ISSUE TITLE
PayPal Express Checkout - How to add billing type and billing description?

### ISSUE THREAD

**Issue by avmurshid** [paypal/PayPal-node-SDK#160]
### General Information

- Mode (Sandbox):
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used:
- SDK Version:

### Issue Description

Hi,
 I am trying to create paypal express checkot token.  am getting token starting with "PAY-" for example (PAY-8BH845240T6776127K5RF6QY) , My requirment is token starting with EC. Please reply on this. Thanks in advance.

**Comment by Michael-Hamburger** [comment]
See #158 
You can extract the EC-Token from the approval_url.

**Comment by avmurshid** [comment]
Thanks @Michael-Hamburger : 
My i need to add billing type and billing description in the same request.  please comment on this.

**Comment by pp-randy** [comment]
@avmurshid can you provide more details about the type of request you are making? Is this for a Billing Agreement or a Payment?

**Comment by ppmtscory** [comment]
Billing Plans and Billing Agreements are their own sets of APIs via REST and are not included within the Create a Payment requests.
