### ISSUE TITLE
Does the sdk have an API for checking status of payment ?

### ISSUE THREAD

**Issue by tc214** [paypal/PayPal-node-SDK#162]
### General Information
Does the sdk have an API for checking status of payment ?

- Mode (Sandbox/Live):
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used:
- SDK Version:

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by ppmtscory** [comment]
If you do a GET call on the payment (sample [here](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/get.js)) then you would get the status in the response.

**Comment by tc214** [comment]
Yeah, I know the response from paypal's server  after call on the payment, but I want to check the status by calling an API freely.

**Comment by ppmtscory** [comment]
You can do the GET call on the payment at any time - you wouldn't have to only get the status from the payment response itself.  Also, you can make this call via API freely outside of the SDK as well.  [Here](https://developer.paypal.com/docs/api/) is a list of REST APIs that are available for use.

**Comment by tc214** [comment]
@ppmtscory Thank you verymuch! Just as you say, do the Get call can get the status of payment.
