### ISSUE TITLE
function about paypal.payment.execute()

### ISSUE THREAD

**Issue by tc214** [paypal/PayPal-node-SDK#163]
PayPal-node-SDK-master\PayPal-node-SDK-master\samples\payment\execute.js:
```node
paypal.payment.execute(paymentId, execute_payment_json, function (error, payment) {
    if (error) {
        console.log(error.response);
        throw error;
    } else {
        console.log("Get Payment Response");
        console.log(JSON.stringify(payment));
    }
});
```
---
I really confused with this function. Does it means that the payment has been completed when this function is called? 
Look forward to your reply.

- Mode (Sandbox/Live):
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used:
- SDK Version:

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by jaypatel512** [comment]
You can read a bit more about creating and executing payments in our [developer docs](https://developer.paypal.com/docs/api/payments/#payment_create).

This code will basically execute (complete) the payment, once the buyer has approved the payment from his side.
