### ISSUE TITLE
INVALID_RESOURCE_ID

### ISSUE THREAD

**Issue by tc214** [paypal/PayPal-node-SDK#164]
###
error_log:
{ [Error: Response Status : 404]
  response: 
   { name: 'INVALID_RESOURCE_ID',
     message: 'The requested resource ID was not found',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID',
     debug_id: 'e639ba9e22a06',
     httpStatusCode: 404 },
  httpStatusCode: 404 }

- Mode (Sandbox/Live):
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used:
- SDK Version:

###
Hi! I have received the problem  when  calling  the method paypal.payment.execute() to pay.  Do anybody have the same problem?
 

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by tc214** [comment]
I have soled this problem which result from argument error.
paypal.payment.execute(arg.payment_id,...     ---shoud be paypal.payment.execute(arg.paymentId,...

**Comment by gbairi19** [comment]
‏في السبت، ٩ يوليو، ٢٠١٦, tc214 <notifications@github.com> كتب:

> Closed #164 <https://github.com/paypal/PayPal-node-SDK/issues/164>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/paypal/PayPal-node-SDK/issues/164#event-717755661>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AH7IrpKugfOVT75mjHX-oTjz9ABSLJu6ks5qT2wBgaJpZM4JH9FH>
> .
>


-- 
0506017008
