### ISSUE TITLE
error_description: 'Invalid authorization code'

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#167]
What's that? Whole Paypal API documentation doesn't have anything close to this error (https://developer.paypal.com/search/?q=%22Invalid+authorization+code%22). There is just no `error_description: 'Invalid authorization code'` in docs. Since I use `PayPal-node-SDK`, it is your custom error wrapper. 
What does this error mean? 
Which API error does it match? 
Where is full list of `PayPal-node-SDK` errors?
How to handle this error?

```
response:
   { error_description: 'Invalid authorization code',
     error: 'access_denied',
     correlation_id: '...',
     information_link: 'https://developer.paypal.com/docs/api/#errors',
     httpStatusCode: 400 },
  httpStatusCode: 400 }
```

**Comment by ppmtscory** [comment]
The authorization code is returned when you're getting permissions from a user via Login With PayPal and can be found in the [openid-connect.js](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/openid_connect/openid-connect.js) sample of this SDK.  More information on Login with PayPal, and it's functionality, can be found [here](https://developer.paypal.com/docs/integration/direct/identity/button/).  The authorization code is only valid for about 3 minutes so, if you're utilizing this flow, you'll want to make sure that you're using that code to generate the refresh token within that timeframe.

**Comment by pp-randy** [comment]
Closing this issue, if you need further help @wzup please let up know
