### ISSUE TITLE
Payment created with `intent` set to "authorize" does not return an authorization ID

### ISSUE THREAD

**Issue by zenweasel** [paypal/PayPal-node-SDK#168]
### General Information

- Mode (Sandbox/Live):
Sandbox

- PayPal-Debug-ID(s) (from any logs):

- Version of node.js used:
6.3.0

- SDK Version:
1.6.9

### Issue Description
I am trying to create a payment for later capture. According to the docs [here](https://developer.paypal.com/docs/integration/direct/capture-payment/#authorize-the-payment) if I set the `intent` to "authorize" I should get back an "authorization" object which contains an ID that I can then use to capture the payment. However I do not receive any "authorization" object, therefore the payment can never be captured.

Below is the test case code I am using. The `create_payment` payload is taken from the documentation.

``` javascript
var paypal = require('paypal-rest-sdk');

paypal.configure({
  'mode': 'sandbox', //sandbox or live
  'client_id': '<client_id>',
  'client_secret': '<client_secret>'
});
var create_payment_json = {
    "intent":"authorize",
    "payer":{
      "payment_method":"credit_card",
      "funding_instruments":[
        {
          "credit_card":{
            "number":"5493022963692972",
            "type":"mastercard",
            "expire_month":12,
            "expire_year":2018,
            "cvv2":874,
            "first_name":"Betsy",
            "last_name":"Buyer",
            "billing_address":{
              "line1":"111 First Street",
              "city":"Saratoga",
              "state":"CA",
              "postal_code":"95070",
              "country_code":"US"
            }
          }
        }
      ]
    },
    "transactions":[
      {
        "amount":{
          "total":"7.47",
          "currency":"USD",
          "details":{
            "subtotal":"7.41",
            "tax":"0.03",
            "shipping":"0.03"
          }
        }
      }
    ]
};

var payment_id;

paypal.payment.create(create_payment_json, function (error, payment) {
    if (error) {
        throw error;
    } else {
        console.log("Create Payment Response");
        console.log(JSON.stringify(payment, null, 4));
        console.assert(payment.transactions.related_resources);
    }
});
```

**Comment by ppmtscory** [comment]
@zenweasel I'm able to reproduce this with the SDK but when using the REST API directly, the full `related_resources` object is blank.  I will work with the team internally to see what's happening here and get a fix pushed out.  I notice that the GET call against the Pay-ID also isn't returning it.

**Comment by sankarbhavanib** [comment]
@zenweasel @ppmtscory I am looking into this issue will update you soon

**Comment by zenweasel** [comment]
@sankarbhavanib Thanks so much. If it's of any value I also tested with the Python SDK and got the same results (no related resources)

**Comment by jaypatel512** [comment]
@ppmtscory @zenweasel On further investigation, this is what I found.

- When using this credit card `4619590530147250` (Master Card), the response object has a `state` value as `created`. 
- However, if you use any other Master Card, the response object has a `state` value as `approved`. 
- The related resources are only showing up when the state has been approved. 
- In your case, for some reason the payment is not getting approved in time, and so it returns back with only `created` status. 

The possible explanation could be of excessive use of that test credit card number. We have faced such issues when a single credit card is used extensively for testing. This may be causing this error to happen.

@zenweasel ! Can you try to use any other credit card by using [Step 4 of credit card generator]( https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413&viewlocale=en_US&direct=en) and see if you are getting the correct response back ?

**Comment by jaypatel512** [comment]
Changing this to API bug.

**Comment by zenweasel** [comment]
As stated in the docs, this payment method can be used with any card which passes a MOD10 check. Trying with numerous other credit card numbers produces the same error.

**Comment by jaypatel512** [comment]
Can you please pass those other credit cards that are failing. I wish to check if my theory is correct or not.

**Comment by zenweasel** [comment]
**Visa**
4242424242424242.
4012888888881881

**MasterCard*
5555555555554444

**Comment by zenweasel** [comment]
Also, didn't @ppmtscory say that "but when using the REST API directly, the full related_resources object is available." So how would using a different credit card come into play here?

**Comment by jaypatel512** [comment]
Thanks for the reply. I will investigate further with these numbers and get back to you. However, in the mean time, can you please make sure that any credit card generated from [Step 4 of credit card generator]( https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413&viewlocale=en_US&direct=en) are working for you ? Are you getting the same error on all the credit cards ? Or are you getting this error in few of these ?

Also, are you seeing any similar error in live, where using any credit card gives you an error back ?

**Comment by zenweasel** [comment]
1. When using the card I created following your instructions I get the proper response back.
2. I get that error on any of those cards. Running them through other processors (Stripe) works fine.
3. We are an eCommerce platform, we don't have a "Live" environment. I don't have any customer reports yet of any issues, but I don't know how many are using Payflow Pro.
