### ISSUE TITLE
OTP verification 

### ISSUE THREAD

**Issue by uditkumawat** [paypal/PayPal-node-SDK#171]
### General Information

- Mode  - Live
- SDK Version:Paypal node sdk 

### Issue Description

can I use Paypal REST API node sdk in making transactions in INDIA ?

does it need OTP verification at any step ?

**Comment by pp-randy** [comment]
@uditkumawat this question would best be answered by a business support or a sales team with knowledge of India integration options.  You should be able to get assistance at the Merchant page here: https://www.paypal.com/in/webapps/mpp/merchant/
