### ISSUE TITLE
Error 500 on payment execution

### ISSUE THREAD

**Issue by strideynet** [paypal/PayPal-node-SDK#172]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): aedba0d07fa9, 	8cc333d86754b, 28ca4aff7be77
- Version of node.js used: 4.4.5
- SDK Version: 1.6.9

### Issue Description

Using in combination with express. Payment creation and redirection goes completely fine however when it comes to executing it we error out with a 500.

**Comment by ApricumMedia** [comment]
Having the same issue. When sending "intent":"sale", it remains in a "created" state, execution is not possible. When sending "authorize" and then "execute", it seems to be working but the money is never transferred.

**Comment by dongzhi-yang** [comment]
I am having the same issue even ifI call the web services directly. I suspect something is wrong with the sandbox of paypal today.

**Comment by ApricumMedia** [comment]
Interesting, thanks @dongzhi-yang. I've been having issues with their Developers section since I started. Couldn't create working accounts fromt the dashboard, took me a day to do it manually. Integrated transaction "sale" and "execute", worked twice yesterday, not once today.

**Comment by dongzhi-yang** [comment]
@ApricumMedia , you are welcome. I tried again just now, and the the execute api is working. 
I guess there may be some server maintenance going on for paypal sandbox during the weekend.

**Comment by ApricumMedia** [comment]
<img width="1432" alt="screen shot 2016-08-08 at 11 08 02" src="https://cloud.githubusercontent.com/assets/7656669/17474876/78ce625e-5d58-11e6-8942-0073a4af3b2b.png">
No changes on my side. Creating a transaction of "intent":"sale" works absolutely fine, execution always fails.

**Comment by bluk** [comment]
Sorry for the late reply. This sandbox error should be fixed now. There is one intermittent error under specific conditions that may be run into, but sandbox should work again for the vast majority of developers. See https://github.com/paypal/PayPal-iOS-SDK/issues/440 . If you still have an issue, please leave a comment. Thanks!
