### ISSUE TITLE
500 Internal Service Error when creating a payment

### ISSUE THREAD

**Issue by joseaomedes** [paypal/PayPal-node-SDK#173]
### General Information

- Mode (Sandbox/Live): SandBox
- PayPal-Debug-ID(s) (from any logs): bf8c7ce6d4fea
- Version of node.js used: 0.10.46
- SDK Version:  'paypal-rest-sdk': '1.6.9'

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

Payment Info:

'{"intent":"sale","redirect_urls":{"return_url":"http://localhost:3000/paypal-complete","cancel_url":"http://localhost:3000/paypal-cancel"},"payer":{"payment_method":"paypal"},"transactions":[{"amount":{"total":"5","currency":"USD"},"description":"Credit top up"}]}'

Asnwer received from Server:

'{"date":"Thu, 11 Aug 2016 10:51:18 GMT","server":"Apache","proxy_server_info":"host=slcsbplatformapiserv3002.slc.paypal.com;threadId=256","paypal-debug-id":"bf8c7ce6d4fea","correlation-id":"bf8c7ce6d4fea","content-language":"*","connection":"close, close","x-slr-retry":"500","x-slr-retry-api":"/v1/payments/payment/","set-cookie":["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D2790829143%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Thu, 11 Aug 2016 11:21:18 GMT; domain=.paypal.com; path=/; Secure; HttpOnly","X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"],"vary":"Authorization","content-length":"209","content-type":"application/json"}'

 '{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"bf8c7ce6d4fea"}'

Three days ago, the same code was 100% working.

I can perform other operations such storing credit cards on the vault with no issues.

**Comment by pp-randy** [comment]
@joseaomedes I see your most recent request worked for you. To me this appears to have been a temporary issue as I do not see that your API request has changed.

**Comment by pp-randy** [comment]
I have confirmed the issue was with the sandbox and should be resolved.

**Comment by joseaomedes** [comment]
Thanks a lot for your help. I will be closing this issue then.
