### ISSUE TITLE
Does paypal node accept debit card in paypal.payment.create()?

### ISSUE THREAD

**Issue by kacak9229** [paypal/PayPal-node-SDK#174]
### General Information

- Mode (Sandbox/Live):
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used:
- SDK Version:

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by pp-randy** [comment]
@kacak9229 if the Debit Card is on the Visa or MasterCard rails then it should work. 
https://developer.paypal.com/docs/api/payments/#definition-credit_card

**Comment by kacak9229** [comment]
Thanks
