### ISSUE TITLE
Express checkout in node

### ISSUE THREAD

**Issue by kacak9229** [paypal/PayPal-node-SDK#175]
My goal is to add an express checkout button, but I don't know how to do it on the serverside

On clientside I managed to put this code

```
<form id="myContainer" method="post" action="/checkout">
          <script>
          window.paypalCheckoutReady = function() {
            paypal.checkout.setup('merchant id', {
              environment: 'sandbox',
              container: 'myContainer'
            });
          };
          </script>
          <script src="//www.paypalobjects.com/api/checkout.js" async></script>
         
        </form>

```

It shows the button and so on. But i assume that i need to create a checkout URL for posting

I already installed the paypal rest-sdk

```
var paypal = require('paypal-rest-sdk');

paypal.configure({
  'mode': 'sandbox', //sandbox or live
  'client_id': 'id',
  'client_secret': 'secret',
});

```

```
app.post('/checkout', function(req, res, next) {
   // What should I put in here?
});
```
The price of the item will be generated by mongoose, just to let you guys know

```
app.post('/checkout', function(req, res, next) {
   var price = book.price;
   // What should I put in here?
});

```

Regards

**Comment by jaypatel512** [comment]
You can follow the sample code provided here : https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/create_with_paypal.js

to understand how to do single payments using paypal.
