### ISSUE TITLE
Subscription Payments + Payment Experience can work together?

### ISSUE THREAD

**Issue by mayconjcm** [paypal/PayPal-node-SDK#177]
Hello,
I have some question. 

I'm trying to use the Subscription Payments plus Payment Experience API, but isn't working.
I can do this using the Simple Payment API! 

Can i do that or is not released yet?

Nice repo, thanks!

**Comment by pp-randy** [comment]
I apologize for the delay @mayconjcm, I see you are on the PHP thread, so I will close this issue.  We will provide updates here: https://github.com/paypal/PayPal-PHP-SDK/issues/119
