### ISSUE TITLE
A json sample with ALL possible options for Create Payment config?

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#178]
First off, is is difficult to use official API docs (https://developer.paypal.com/docs/api/payments) when you create a payment. Unfriendly user interface and experience.

Here I found a minimal sample for create payment json https://devtools-paypal.com/hateoas/index.html
```
{
    "intent": "sale",
    "payer": {
        "payment_method": "paypal"
    },
    "transactions": [
        {
            "amount": {
                "currency": "USD",
                "total": "110.54"
            },
            "description": "This is the payment transaction description."
        }
    ],
    "redirect_urls": {
        "return_url": "http://www.ebay.com",
        "cancel_url": "http://www.milo.com"
    }
}
```

However, I want the same but with **ALL** possible `key: values`. Where can I find it? Can you provide it somewhere?

**Comment by pp-randy** [comment]
@wzup the API documentation is where to go, but it does require a bit of drilling down. If you started at [Create Payment](https://developer.paypal.com/docs/api/payments/#payment_create_request) you would then drill down into [Transactions object](https://developer.paypal.com/docs/api/payments/#definition-transaction) and so fourth.
