### ISSUE TITLE
how to send payment amount to other user paypal account using REST API

### ISSUE THREAD

**Issue by uditkumawat** [paypal/PayPal-node-SDK#182]
### General Information

- Mode  - Sandbox
- Version of node.js used: latest
- SDK Version: latest

### Issue Description

I am beginner in using Paypal node sdk.How can we transfer amount to user paypal account using RESTAPI ?

**Comment by pp-randy** [comment]
@uditkumawat you can use this SDK with Payouts API. 

Documentation: https://developer.paypal.com/docs/integration/direct/payouts/

Sample: https://github.com/paypal/PayPal-node-SDK/tree/master/samples/payout

Please let me know if you have further questions.

**Comment by uditkumawat** [comment]
@pp-randy payouts API is giving error with LIVE credentials like this :

{
	"status": 403,
	"duration_time": 123,
	"body": {
		"message": "Authorization error occurred",
		"debug_id": "1559c48ff33c8",
		"information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
		"name": "AUTHORIZATION_ERROR"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "188",
		"Content-Language": "*",
		"Date": "Thu, 29 Sep 2016 07:40:34 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "1559c48ff33c8",
		"PROXY_SERVER_INFO": "host=dcg11javapapi3114.dcg11.slc.paypalinc.com;threadId=370",
		"Content-Type": "application/json"
	}
}

**Comment by pp-randy** [comment]
Have you requested Payouts to be enabled on your account?https://developer.paypal.com/docs/integration/direct/payouts/#enable-payouts

**Comment by uditkumawat** [comment]
Can you please help me in providing steps for enabling payouts ? I will be very thankful to you

**Comment by pp-randy** [comment]
The guide has some details but it also says you can reach out to PayPal Customer Service here: https://www.paypal.com/selfhelp/home

**Comment by uditkumawat** [comment]
I have already raised a request at technical support but didn't got their mail .

**Comment by pp-randy** [comment]
You need PayPal Custom Service, I do not believe PayPal Technical Support can make account changes.
