### ISSUE TITLE
MALFORMED_REQUEST error is not informative

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#183]
What error message is this? How can I know what is "MALFORMED" in my JSON?

```
 { 
     name: 'MALFORMED_REQUEST',
     message: 'Incoming JSON request does not map to API request',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST',
```

I have huge `payment_json` config and I want to know exactly what fields are "MALFORMED". Tell me what fields are "MALFORMED" here. How can I know it from your error message?

```
 { intent: 'sale',
  payer:
   { payment_method: 'paypal',
     payer_info:
      { salutation: 'Hi there! This is a salutation string.',
        first_name: 'John',
        last_name: 'Doe' } },
  transactions:
   [ { reference_id: 'Foo Services',
       amount: { currency: 'USD', total: '100' },
       description: 'Description of what is being paid for.',
       note_to_payee: 'Note to the recipient of the funds in this transaction.',
       custom: 'free-form field for the use of clients.',
       invoice_number: 'invoice number to track this payment.',
       payment_options: { allowed_payment_method: 'IMMEDIATE_PAY' },
       item_list:
        { items:
           [ { sku: 'fooItem',
               name: 'Foo Item Name',
               description: 'Foo Item description',
               quantity: '1',
               price: 20,
               currency: 'USD',
               url: 'http://example.com:3000/buy/foo' } ] },
       notify_url: 'http://example.com:3000/notify_url',
       order_url: 'http://example.com:3000/buy/foo' } ],
  note_to_payer: 'free-form field for the use of clients to pass in a message to the payer.',
  redirect_urls:
   { return_url: 'http://example.com:3000/complete_payment',
     cancel_url: 'http://example.com:3000/cancel_payment' } }
```

Please do us a favour, create human readable, understandable error message!

**Comment by pp-randy** [comment]
Salutation is read only, so you should not set a value for it. 

https://developer.paypal.com/docs/api/payments/#definition-payer_info

![image](https://cloud.githubusercontent.com/assets/6819909/18314832/5b3c8a60-74da-11e6-91a5-b057710813ce.png)

**Comment by Shadowstep33** [comment]
I think what @wzup is trying to infer is that the error message does not at all explain what field was incorrect or expound upon what is missing or malformed. I'm hitting the same problem and have been stuck on it for days

**Comment by xiaoleih41** [comment]
@Shadowstep33  You are correct, this is not a SDK issue but the API issue. Unfortunately we cannot make it more specific when it comes to this error. If you can submit a new issue with your code under [REST API issue repository](https://github.com/paypal/PayPal-REST-API-issues/issues), we can try to look into this for you. I am locking this thread as the original issue was solved.
