### ISSUE TITLE
[Payments API] "payer -> payer_info -> salutation" field throws MALFORMED_REQUEST error

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#184]
Continue for this https://github.com/paypal/PayPal-node-SDK/issues/183

Why do you include `salutation` in your docs if this doesn't go with your system? If it breaks your system

```
salutation: 'Hi there! This is a salutation string.',
```

**Comment by pp-randy** [comment]
Closing this issue, will track here: https://github.com/paypal/PayPal-node-SDK/issues/183
