### ISSUE TITLE
"Show payment details to buyer" step doesn't work

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#185]
There is an optional step you promote in your docs - **Show payment details to buyer** https://developer.paypal.com/docs/integration/direct/express-checkout/show-payment-details/

The questions are:

1) how does it go with **Advanced In-Context JavaScript settings** https://developer.paypal.com/docs/classic/express-checkout/in-context/javascript_advanced_settings/? 

2) How does it suppose work?

There is a In-Context JavaScript pop up window after user has approved the payment. And what's next? How do I/do you "load" payment details in that window to show them to buyer? An example of the step would be very appreciated.

**Comment by pp-randy** [comment]
Per https://github.com/paypal/PayPal-node-SDK/issues/186.  PayPal Technical Support will be able to assist you with integrating In-Context.
