### ISSUE TITLE
Will anybody from Paypal ever bother to answer questions on Stackoverflow?

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#186]
Does Paypal have any developer support? Why send people on Stackoverflow if there is no any support there? It is getting worse and worse to work with Paypal. Small processing companies have much more dynamic support.

http://stackoverflow.com/questions/39371310/in-context-checkout-no-response-handler-found-for-post-message-response-error
http://stackoverflow.com/questions/39343560/how-to-check-if-paypal-checkout-setup-has-already-been-called
http://stackoverflow.com/questions/39335045/in-context-checkout-uncaught-securityerror-blocked-a-frame-with-origin-checko

**Comment by pp-randy** [comment]
PayPal Technical Support can be reached here: https://www.paypal-techsupport.com/app/ask
