### ISSUE TITLE
Requested resource ID was not found when doing payment.get

### ISSUE THREAD

**Issue by sargsyantaron** [paypal/PayPal-node-SDK#188]
### General Information

- Mode :Sandbox
- PayPal-Debug-ID(s) (from any logs):ff343198cbbe3
- Version of node.js used: 4.3.2
- SDK Version: 1.6.9

### Issue Description

I'm doing basic payment check and need to get payment by id to check if payment has been authorized or not, but getting 404 resource not found error.

below is the output from sdk
{ [Error: Response Status : 404]
  response:
   { name: 'INVALID_RESOURCE_ID',
     message: 'Requested resource ID was not found.',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID',
     debug_id: '4280a38525706',
     httpStatusCode: 404 },
  httpStatusCode: 404 }

**Comment by pp-randy** [comment]
@sargsyantaron are you still having an issue?  If so, can you provide the complete URL the request is going to?  A new debug id would be helpful since I can't find the logs for your previous attempts currently. 

I have seen some cases where the payment was in sandbox and the lookup was going to live, so something worth checking.

**Comment by sargsyantaron** [comment]
@pp-randy will be doing some tests this week and if it still there will let you know details.

thanks

**Comment by pp-randy** [comment]
Thank you @sargsyantaron let me know what you find out.  If you don't see this anymore, we have had some recent sandbox issues that have been resolved.

**Comment by Jason32g** [comment]
Can u create a payment for me to receive to add money to my PayPal.

**Comment by Jason32g** [comment]
Good job.!

**Comment by sargsyantaron** [comment]
ok tested just now 

name: 'INVALID_RESOURCE_ID',
message: 'Requested resource ID was not found.',
information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID',
debug_id: '4eba8613945d8',
httpStatusCode: 404

**Comment by sargsyantaron** [comment]
path i was trying to reach is /v1/payments/payment/PAY-1CH415761F1235919KIQMTGY

**Comment by pp-randy** [comment]
@sargsyantaron  I'm not seeing your logs for that attempt, so I need to get some more information from you. 

Can you give the Paypal-Debug-Id from the header of your Create Payment response?  What is the full URL your payment lookup and does it match the link value from when you created the payment?

**Comment by sargsyantaron** [comment]
I'm getting this error when i try to get payment to create payment

**Comment by sargsyantaron** [comment]
here is response from create payment on android client 

`{
                                                                        "response": {
                                                                            "state": "approved",
                                                                            "id": "PAY-1CH415761F1235919KIQMTGY",
                                                                            "create_time": "2014-02-12T22:29:49Z",
                                                                            "intent": "sale"
                                                                        },
                                                                        "client": {
                                                                            "platform": "Android",
                                                                            "paypal_sdk_version": "2.0.2",
                                                                            "product_name": "PayPal-Android-SDK",
                                                                            "environment": "mock"
                                                                        },
                                                                        "response_type": "payment"
                                                                    }`

**Comment by sargsyantaron** [comment]
my user flow is the following 

1. user makes payment from android device 
2. once payment is approved android app send payment id back to backend system for verification 

and the error i see is when i try to get payment by id based on paymentid received from android device.

**Comment by sargsyantaron** [comment]
seems i found the issue, let me check something and i will update the ticket or close it.

**Comment by sargsyantaron** [comment]
the issue was with mobile client creating payment in different environment
