### ISSUE TITLE
What is a "cart" field in "Show payment details" response object?

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#189]
Here a sample https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/get.js

```
paypal.payment.get(paymentId, function (error, payment) { ... })
```

The response `payment` object has a field that is not documented in API. It is some `cart` field:
```
{
    id: 'PAY-94L519775J697601XT7IXOWA',
    intent: 'sale',
    state: 'created',
    cart: '2DJ63392J3708305U', // <=== What is this?
    payer: {
        payment_method: 'paypal',
        status: 'VERIFIED',
        payer_info: { ....
```

**Comment by pp-randy** [comment]
Cart is the id of the cart being used to execute the payment. In the context of a PayPal payment it is Express Checkout token minus  the "EC-" string in front of the value of cart.  If you look at the end of approval_url in the create payment response you will see EC- followed by the cart value.  Together this "EC-" + cart value is the Express Checkout Token.

**Comment by wzup** [comment]
@pp-randy,

Why do we need it? Is this such a necessary information that as many as a top-level field in a payment response object was allocated to it? 

What is so important about `cart` value?
What are usecases for `cart` value?

**Comment by pp-randy** [comment]
It is part of the buyer approval for PayPal as indicated earlier it is used in the redirect to PayPal.  Once your payment has executed find I do not think you would need to hold on to it long term.
