### ISSUE TITLE
Sandbox Credit Card payment always returns INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by webmasterkarthi** [paypal/PayPal-node-SDK#190]
### General Information

- Mode  : Sandbox
- PayPal-Debug-ID(s) : a93515f621560, a93515f621560 
- Version of node.js used: v4.4.4
- SDK Version: 1.6.9

### Issue Description

> PayPal payments were working fine. But when i submit test credit card details auto created from paypal it returns `{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"a93515f621560"}`

**Comment by nkhine** [comment]
I have the same issues and looking at the logs, i have:

```
problem with request: getaddrinfo ENOTFOUND api.paypal.com api.paypal.com:443
{ [Error: getaddrinfo ENOTFOUND api.paypal.com api.paypal.com:443]
  cause: 
   { [Error: getaddrinfo ENOTFOUND api.paypal.com api.paypal.com:443]
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'api.paypal.com',
     host: 'api.paypal.com',
     port: 443 },
  isOperational: true,
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.paypal.com',
  host: 'api.paypal.com',
  port: 443 }
PAYPAL_ERROR {
  "cause": {
    "code": "ENOTFOUND",
    "errno": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "api.paypal.com",
    "host": "api.paypal.com",
    "port": 443
  },
  "isOperational": true,
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "api.paypal.com",
  "host": "api.paypal.com",
  "port": 443
}
```

it looks like PayPal's end points are no longer working!

**Comment by Jason32g** [comment]
How to add money to paypal

**Comment by webmasterkarthi** [comment]
UPDATE: I resolved this problem by changing client_id and secret. Actually, i created sandbox account and paypal app from my personal paypal account. Not sure whether any settings on my app caused this error. When i use merchant account client_id and secret it worked fine.

**Comment by pp-randy** [comment]
@webmasterkarthi you could be seeing an issue in the sandbox for your credit card payments which is described in more detail here: https://github.com/paypal/PayPal-PHP-SDK/issues/639.  To sum it up payment_card funding instrument is working and credit_card is having issues in the sandbox.

**Comment by pp-randy** [comment]
@nkhine can you reach out to PayPal Technical Support here: https://www.paypal-techsupport.com/app/ask

It appears you may be having a DNS issue, or similar issue, that PayPal Technical Support would be better able to assist you with.
