### ISSUE TITLE
payment.create: approval_url always session has ended

### ISSUE THREAD

**Issue by jasoncheng** [paypal/PayPal-node-SDK#193]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): PAY-6PB56377WL3102457K7QOWUY
- Version of node.js used: 0.12.13
- SDK Version:1.6.8

### Issue Description

I can get all function work but today, when i redirect to PayPal, it's always show 

"Your session has ended. Your PayPal account hasn't been charged. Please go back to the merchant's site and check out with PayPal."

`{

      "href": "https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-5XT81504M83128807",

      "rel": "approval_url",

      "method": "REDIRECT"

}`

any help?

**Comment by bluk** [comment]
Thank you for reporting this sandbox issue. We currently have an internal ticket PPPLMER-20280 to track this.

Please see https://github.com/paypal/PayPal-NET-SDK/issues/193#issuecomment-248335995 .

**Comment by pp-randy** [comment]
This issue is resolved at this time.  I apologize for any inconvenience.
