### ISSUE TITLE
INTERNAL_SERVICE_ERROR when creating a payment

### ISSUE THREAD

**Issue by arielmcm** [paypal/PayPal-node-SDK#194]
### General Information

- Mode: Sandbox
- PayPal-Debug-ID(s): 2d37b50170ceb
- Version of node.js used: 6.3.1
- SDK Version: 1.6.9

### Issue Description

When I try to create a payment in my Loopback API, the service always returns: 

'{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/web
apps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"2d37b50170ceb"}'

That only happens when using **credit_card_token** in **funding_instruments**, when I use **credit_card** (deprecated) instead, it does work.

This is my payload for the payment:
```
{
    'intent': 'sale',
    'payer': {
      'payment_method': 'credit_card',
      'funding_instruments': [
        {
          'credit_card_token': {
            'credit_card_id': creditCardId,
            'payer_id': payerId,
          },
        },
      ],
    },
    'transactions': [
      {
        'amount': {
          'total': price.toString(),
          'currency': 'USD',
        },
        'description': description,
        'invoice_number': orderId,
      },
    ],
}
```

**Comment by bluk** [comment]
@arielmcm Sorry for the late reply. Can you please try again now? There were a few sandbox service deployments that may have fixed this in sandbox.

I was able to successfully invoke this transaction in sandbox using something like:

```
{
  "intent": "sale",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card_token": {
          "credit_card_id": "CARD-0VU17823CS696092UK7Z4ETR",
          "payer_id": "Y6SC5GMPEH9DB"
        }
      }
    ]
  },
  "transactions": [
    {
      "amount": {
        "total": "4.01",
        "currency": "USD"
      }
    }
  ]
}
```

I would also verify that the `payerId` is correct by GETting the vaulted payment `https://api.sandbox.paypal.com/v1/vault/credit-cards/<vaulted credit card id>`.

**Comment by arielmcm** [comment]
Yes, it is working right now. Thanks!
