### ISSUE TITLE
BillingAgreement.execute() failed twice for a specific user -- other users fine

### ISSUE THREAD

**Issue by yitz-jacob** [paypal/PayPal-node-SDK#195]
### General Information

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs):  none appeared (? which is part of the diagnostic issue)
- Version of node.js used: 0.10.46
- SDK Version: 1.6.1

### Issue Description

running under node/express, we use the node API to allow users to sign up for either recurring or one-time payments to our site. This case is a recurring once yearly payment. A number of users have signed up successfully w/ this exact same code. One particular user has tried twice, and failed both times w/ a 500 error. (The Billing plan and billing agreement was created and updated to active successfully in all cases, even this error case)  (The user was on safari/macOS which shouldn't make a difference because this was a call failure between our backend and paypal's REST API, her session info at the time was fine, everything intact, the call was placed with the correct EC Token) 

    paypal.billingAgreement.execute(token, {}, function (error,  billingAgreement) {
                        if (error) {
    ...
    console.log(JSON.stringify(error));
    ...

when I logged the JSON.stringify(error), this is what was logged: 
{"response":{"httpStatusCode":500},"httpStatusCode":500}

It didn't have any debug-id which to me seemed suspect, but I seem to have ruled out anything other than Paypal REST API or the node wrapper for the API as the source of this error. Is it possible that this error is really coming back from Paypal, but only for a specific user? This was their second attempt (first was Aug 30, second Sep 20th, between those two dates I had no problem following the exact same steps and completing the transaction -- many other people have over the past year, and failures for any other reason have always returned useful data, this seemed like a weird case where something about this one user's paypal account is causing paypal to fail w/ a 500. (And also not returning a debug-id or more info?)

**Comment by yitz-jacob** [comment]
From reading up more in other issues and the read me, it seems that I'm not getting a debug-id back because this is our production server..  and we're working against paypal live. Is there a way to turn on debugging for a particular request somehow, or tell the paypal-node-sdk to be in debug mode without the whole server running in debug mode? It would be impractical to run the whole prod server that's live in debug mode for a case that fails only for a single user. 

I can ask the user to attempt to complete transaction against a separate instance of the server that's in dev mode but that seems very unprofessional, are there any other alternatives? 

thanks in advance!

**Comment by bluk** [comment]
@yitz-jacob There could be an issue with the user's account which could be causing this issue. Since this is a live production issue, can you please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/ask)?

We will look into making the debug process easier.
