### ISSUE TITLE
How do I remove a “Ship to” section from Checkout Popup?

### ISSUE THREAD

**Issue by wzup** [paypal/PayPal-node-SDK#196]
Is there any option, when creating a payment with Paypal API, that allows to remove a "Ship to" section from Checkout popup? I mean just not to displayit in popup. **OR** how to disable an option to change shipping address? To display an address, just disable `Change` arrow button.

I do not use a `shipping_address` option anywhere in `payment_json` object when creating a configuration for a Payment.create API call. But the section still persists.

This question on SO: http://stackoverflow.com/questions/39653753/how-do-i-remove-a-ship-to-section-from-checkout-popup

![paypal checkout - review your payment - google chrome 2016-09-23 14 32 12](https://cloud.githubusercontent.com/assets/3880497/18776614/0d12ec2e-819d-11e6-93b3-2e4dc37ea957.png)

Wrong repo to post such questions? Show me a correct one.

**Comment by thirtified** [comment]
Yes, this is probably the wrong place to ask such a general API question, and it has [now been answered on SO](http://stackoverflow.com/a/39712308/170132).

**Comment by pp-randy** [comment]
Closing as this has been answered on StackOverflow.
