### ISSUE TITLE
Error while using LIVE credentials with REST API

### ISSUE THREAD

**Issue by uditkumawat** [paypal/PayPal-node-SDK#197]
### General Information

- Mode (Live):
- PayPal-Debug-ID(s) (from any logs): 1559c48ff33c8
- Version of node.js used: 4.4.7
- SDK Version:

### Issue Description

> I am using REST API for creating payment using credit card and payouts.But it was working fine with  sandbox credentials but for Live credentials it was giving errors like this :

{
	"status": 403,
	"duration_time": 123,
	"body": {
		"message": "Authorization error occurred",
		"debug_id": "1559c48ff33c8",
		"information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
		"name": "AUTHORIZATION_ERROR"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "188",
		"Content-Language": "*",
		"Date": "Thu, 29 Sep 2016 07:40:34 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "1559c48ff33c8",
		"PROXY_SERVER_INFO": "host=dcg11javapapi3114.dcg11.slc.paypalinc.com;threadId=370",
		"Content-Type": "application/json"
	}
}

{
	"status": 401,
	"duration_time": 49,
	"body": {
		"message": "Unauthorized payment.",
		"debug_id": "eabb84d3ef438",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT",
		"name": "UNAUTHORIZED_PAYMENT"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "191",
		"Content-Language": "*",
		"CORRELATION-ID": "eabb84d3ef438",
		"Date": "Thu, 29 Sep 2016 11:48:50 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "eabb84d3ef438",
		"PROXY_SERVER_INFO": "host=dcg12javapapi7866.dcg12.slc.paypalinc.com;threadId=704",
		"Content-Type": "application/json"
	}

Please help me in resolving this issue.

**Comment by bluk** [comment]
Is payouts enabled for your live account ( https://developer.paypal.com/developer/accountStatus/ )?

![screen shot 2016-09-30 at 10 33 53 am](https://cloud.githubusercontent.com/assets/94150/18997316/780ad846-86f9-11e6-8314-b030080e52b8.png)

**Comment by uditkumawat** [comment]
Direct credit card and payouts option is not enable.....it was showing that ' we need some more information to enable' . what's that more informatuon ?

**Comment by uditkumawat** [comment]
I request customer support to please enable these services for my account

**Comment by bluk** [comment]
@uditkumawat [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) is the best way to resolve this since it's a live account issue. The SDK team doesn't have access to live credentials, so you will have to resolve this with tech support. Hope that helps.
