### ISSUE TITLE
INTERNAL_SERVICE_ERROR while making payments with saved credit card

### ISSUE THREAD

**Issue by ankit-clicklabs** [paypal/PayPal-node-SDK#198]
- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 49b9550e54cef
- Version of node.js used: v6.2.2
- SDK Version:1.6.9

I am getting "INTERNAL_SERVICE_ERROR" whenever I try to make any payments.This error  comes up rather infrequently , so I am unable to find out what I may be doing wrong.

**Comment by bluk** [comment]
@ankit-clicklabs I don't think it's anything you're doing wrong. There was an internal error in one of the services that caused this specific error. If this keeps happening, please leave a comment or open a new issue.
