### ISSUE TITLE
UNAUTHORIZED ERROR with LIVE credentials

### ISSUE THREAD

**Issue by uditkumawat** [paypal/PayPal-node-SDK#201]
General Information

Mode (Live):
PayPal-Debug-ID(s) (from any logs): 1559c48ff33c8
Version of node.js used: 4.4.7
SDK Version:
Issue Description

I am using REST API for creating payment using credit card and payouts.But it was working fine with sandbox credentials but for Live credentials it was giving errors like this :
{
"status": 403,
"duration_time": 123,
"body": {
"message": "Authorization error occurred",
"debug_id": "1559c48ff33c8",
"information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
"name": "AUTHORIZATION_ERROR"
},
"additional_properties": {},
"header": {
"Content-Length": "188",
"Content-Language": "*",
"Date": "Thu, 29 Sep 2016 07:40:34 GMT",
"Connection": "close",
"Paypal-Debug-Id": "1559c48ff33c8",
"PROXY_SERVER_INFO": "host=dcg11javapapi3114.dcg11.slc.paypalinc.com;threadId=370",
"Content-Type": "application/json"
}
}

{
"status": 401,
"duration_time": 49,
"body": {
"message": "Unauthorized payment.",
"debug_id": "eabb84d3ef438",
"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT",
"name": "UNAUTHORIZED_PAYMENT"
},
"additional_properties": {},
"header": {
"Content-Length": "191",
"Content-Language": "*",
"CORRELATION-ID": "eabb84d3ef438",
"Date": "Thu, 29 Sep 2016 11:48:50 GMT",
"Connection": "close",
"Paypal-Debug-Id": "eabb84d3ef438",
"PROXY_SERVER_INFO": "host=dcg12javapapi7866.dcg12.slc.paypalinc.com;threadId=704",
"Content-Type": "application/json"
}

Please help me in resolving this issue.

Even when I click on enable button in account eligibility ,it shows these error.

![screen shot 2016-10-04 at 11 57 31](https://cloud.githubusercontent.com/assets/7333127/19064266/e0b7bf34-8a29-11e6-8711-cde3b93fef4f.png)

**Comment by bluk** [comment]
@uditkumawat Please see the [supported countries list](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments) (basically UK Pro accounts) and ensure that your account's country is eligible for direct credit card transactions with the REST APIs.

If it is not supported, you may want to check out [Braintree Payments](https://www.braintreepayments.com) to see if your country is supported in production there.
