### ISSUE TITLE
Errors while trying to retrieve payment informations on live

### ISSUE THREAD

**Issue by terehov** [paypal/PayPal-node-SDK#202]
### General Information

- Mode (Sandbox/Live): live
- PayPal-Debug-ID(s) (from any logs):
paypal-debug-id: 5cbaa6677e22c, 5cbaa6677e22c
paypal-debug-id: fd92c206189c5, fd92c206189c5

- Version of node.js used: 6.4
- SDK Version:1.6.9

Error while trying to list all payment transactions: 
paypal-debug-id: 5cbaa6677e22c, 5cbaa6677e22c
paypal-debug-id: fd92c206189c5, fd92c206189c5
List Payments Response
`{"count":0,"httpStatusCode":200}`

Code: 
```
paypal.payment.list(function (error, payment) {
    if (error) {
        throw error;
    } else {
        console.log("List Payments Response");
        console.log(JSON.stringify(payment));
    }
});
```

But actually I would need the information of one particular payment.
From the client I got the paykey e.g. "AP-123456789..."

When doing: 
```
paypal.payment.get('AP-123456789...', function (error, payment) {
    if (error) {
        throw error;
    } else {
        console.log("List Payments Response");
        console.log(JSON.stringify(payment));
    }
});
```

I get: 
paypal-debug-id: cdddd56a95752, cdddd56a95752
paypal-debug-id: aa03821693982, aa03821693982
...
Error: Response Status : 404

Do you have any tips? 

Thanks :-)

**Comment by bluk** [comment]
@terehov Are you trying to lookup a payment that was made using Adaptive Payments? If so, you cannot directly lookup the payment via the REST API.

Please see the [documentation](https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-parallelPayment-curl-etc/) for how to look up an adaptive payment info. You may want to use an [Adaptive Payments SDK](https://developer.paypal.com/docs/classic/api/nvpsoap-sdks/) but unfortunately no Node.js version.
