### ISSUE TITLE
"INTERNAL_SERVICE_ERROR" when trying to execute payment

### ISSUE THREAD

**Issue by vatex** [paypal/PayPal-node-SDK#207]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 9cec3d41b0cf3
- Version of node.js used:v6.3.1
- SDK Version: 1.6.9

### Issue Description

> I trying to execute payment but it fails :/ yesterday I tried with same code and yesterday was working correctly...

**Comment by bluk** [comment]
Please see https://github.com/paypal/PayPal-PHP-SDK/issues/676 . Internal issue PPPLMER-21356 is being used to track this. My apologies for the inconvenience.

**Comment by vatex** [comment]
@bluk Why you closed this issue? Is it fixed? I don't understand why it was happened... Can I continue testing in sandbox?

**Comment by bluk** [comment]
@vatex PayPal is currently experiencing a sandbox issue internally (there isn't anything wrong with your integration). Please see the linked issue for status updates. It is to help keep track and everyone updated at the same time.

**Comment by vatex** [comment]
@bluk Thank you!

**Comment by bluk** [comment]
This should be fixed now. I was able to execute a payment earlier. If you're still encountering an issue, please open a new issue with a `PayPal-Debug-ID` if possible. Thanks for your patience and our apologies for the issue.
