### ISSUE TITLE
500 Internal server error for execute payment

### ISSUE THREAD

**Issue by vldkrt** [paypal/PayPal-node-SDK#210]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): ed0dd37ba4d6f
- Version of node.js used: 5.0.0
- SDK Version:  1.6.9

### Issue Description
I get a 500 error when I try to finalize a payment

**Comment by pp-randy** [comment]
Thank for reporting the issue.  This is a PayPal system issue, please follow the issue in our PHP issue repository here https://github.com/paypal/PayPal-PHP-SDK/issues/685 for further updates.
