### ISSUE TITLE
IPN URL

### ISSUE THREAD

**Issue by tc214** [paypal/PayPal-node-SDK#211]
### General Information
Do anybody know IPN URL setting?

- Mode (Sandbox/Live):Sandbox
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used:
- SDK Version:

### Issue Description
Hi! Our online shop has integrated paypal-node-sdk and it works greatly. However, we have some servers at different countries: one at America, one at China, one at Japan ,etc. All the servers will run a online shop system at the same time, so each server need a different IPN URL. But I  can set only one IPN URL at the paypal site.  I should set a different  IPN URL for each server. How can I sovle this problem?     Tks.

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by bluk** [comment]
Please see https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNSetup/ . The IPN Listener can be dynamically set for specific integrations. If you are using the REST API, you can also look into setting up multiple webhooks. There are other possible solutions (like forwarding the event yourself which you can find on StackOverflow/searches) but are outside the scope of this SDK.

**Comment by tc214** [comment]
@bluk Tks.  Maybe webhooks can help me solve the problem.
