### ISSUE TITLE
Not able to transact with paypal future payments

### ISSUE THREAD

**Issue by ankit-daffodil2** [paypal/PayPal-node-SDK#213]
### Issue Description

I am using Android and Node JS for paypal integration for automatic payment from one account to another.(Future Payment)

I have got access to paypal account from buyer and passed the ```Authorization Code``` and ```MetaData Id``` from my android app onto my node server.

I have fetched ```refresh token``` and ```access token``` from the Authorization Code and created a future payment and capture the payment using following code:

	var future_payment_config = {
	    "PayPal-Client-Metadata-Id": metaId,
	    "Authorization": refresh_token
	};
	//Set up payment details
	var create_payment_json = {
	    "intent": "authorize",
	    "payer": {
	        "payment_method": "paypal"
	    },
	    "transactions": [{
	        "amount": {
	            "currency": "USD",
	            "total": "1.88"
	        },
	        "description": "future of sauces"
	    }]
	};

	var pay_id = "";

	var url = "";

	//Create future payment
	paypal.payment.create(create_payment_json, future_payment_config, function(error, payment) {
	    if (error) {
	        console.log(error.response);
	        throw error;
	    } else {
	        console.log("Authorization Object : " + JSON.stringify(payment));
	        pay_id = payment.id;
	        for (var index = 0; index < payment.transactions[0].related_resources[0].authorization.links.length; index++) {
	            //Redirect user to this endpoint for redirect url
	            if (payment.transactions[0].related_resources[0].authorization.links[index].rel === 'capture') {
	                // console.log(payment.links[index].href);
	                url = payment.transactions[0].related_resources[0].authorization.links[index].href;

	                var execute_payment_json = { "amount": { "currency": "USD", "total": "1.50" }, "is_final_capture": true }

	                var payer_id = payment.payer.payer_info.payer_id;
	                // var paymentId = { "paymentId" : pay_id};

	                // paymentId = {
	                //     "PayPal-Client-Metadata-Id": metaId,
	                //     "Authorization": refresh_token
	                // };
	                // console.log(execute_payment_json, paymentId);

	                paypal.authorization.capture(payment.transactions[0].related_resources[0].authorization.id, execute_payment_json, function(error, payment) {
	                    if (error) {
	                        console.log(error.response);
	                        throw error;
	                    } else {
	                        console.log("Get Payment Response");
	                        console.log(JSON.stringify(payment));
	                    }
	                });

	            }
	        }
	    }
	});

I am not able to do transaction. I want to know, if I need to do something more for transaction. I have also tried to use ```paypal.execute``` (shown below) :

	function executePayment(paymentId, payerId) {
	    var details = {
	        "payer_id": payerId,
	        "transactions": [{
	            "amount": {
	                "currency": "USD",
	                "total": "1.88"
	            },
	            "description": "future of sauces"
	        }]
	    };
	    paypal.payment.execute(paymentId, details, function(error, payment) {
	        if (error) {
	            console.log("Error :", error);
	        } else {
	            console.log("Result : ",payment);
	        }
	    })
	}

The error I am getting on ```paypal.execute``` is this: 

	Error : { [Error: Response Status : 400]
	  response: 
	   { name: 'INTERNAL_SERVICE_ERROR',
	     message: 'An internal service error has occurred',
	     information_link: 'https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR',
	     debug_id: 'a544d3865cd51',
	     httpStatusCode: 400 }

I want to know, if I am on the right track! I want the Buyer to subscribe to future payments and the Facilitator will deduct the payment automatically.

Thanks in Advance.

**Comment by bluk** [comment]
@ankit-daffodil2 You shouldn't need to execute the payment using `paypal.payment.execute`. What is the error you get for the `paypal.payment.create`? Do you have a PayPal-Debug-ID for that?

**Comment by ankit-daffodil2** [comment]
I am able to successfully create the payment. After creating the payment, I am capturing the payment as you can see in code and as mentioned in docs.

What to do after that is not mentioned in the docs. As I am not able to see any transaction in my Sandbox account upto this step.

If there is no need to use ```paypal.payment.execute``` then what to do after ```paypal.authorization.capture``` to make transaction?

**Comment by bluk** [comment]
@ankit-daffodil2 Parallel/chained payments are supported under the Adaptive Payments platform which doesn't have a node.js SDK, and I believe does require a UI authentication in the flow.

**Comment by ankit-daffodil2** [comment]
I have done it without UI authentication using payout.

I want to know I am paying 4.2% transaction fee during transfer from buyer to Facilitator and paying 2% transaction fee from facilitator to seller.

Is there any way to save transaction fee amount?

**Comment by bluk** [comment]
You should contact [PayPal Support](https://www.paypal.com/us/selfhelp/home). They know more about the fee structure and what is the best path for your business.
