### ISSUE TITLE
Payment API response object doesn't return payer's billing_address

### ISSUE THREAD

**Issue by jaankoppe** [paypal/PayPal-node-SDK#216]
### General Information

- Mode (Sandbox/Live): Both
- PayPal-Debug-ID(s) (from any logs): 83cb4044dcd13
- Version of node.js used: sandbox: 4.6, live: 4.4.6
- SDK Version: 1.68

### Issue Description

The payment response object has no information about payers billing address when executing a payment ( `payment.payer.payer_info.billing_address` is undefined when doing `paypal.payment.execute` )

This produces an TypeError when I need to use these values and the application will restart and paypal trigger's PAYMENT_ALREADY_DONE (the debug id mentioned above refers to this error)

From one day suddenly this error appeared without updating my code.

My current workaround is that I'm checking if the billing_address exists and if not, replace all fields inside the object with "N/A".

**Comment by bluk** [comment]
Can you please contact [PayPal Support](https://www.paypal.com/us/selfhelp/home) regarding this issue? It seems to be an account specific issue. You may also want to mention internal issue PPPLPAYPT-13584 which seems to be related. Thanks.

**Comment by jaankoppe** [comment]
No, not an account specific issue. I can't receive billing addresses from any account. Also the payer country code is showing only merchant's code. This was correct before. It look's to me that the API has changed but it's not described in the documentation.
