### ISSUE TITLE
Can't moved to production mode from sandbox

### ISSUE THREAD

**Issue by vatex** [paypal/PayPal-node-SDK#218]
I'm in developer.paypal.com and here's toggle (sandbox/live) when I click live, it doesn't make sense and after refresh, it returns to sandbox mode.

**Comment by bluk** [comment]
@vatex Can you describe your issue in more detail? I was able to login and view live credentials in Chrome, Firefox, and Safari. Are you not seeing credentials at all?

**Comment by vatex** [comment]
Everything is ok.
