### ISSUE TITLE
'mode': 'sandbox' configuration in READ.ME returns an error

### ISSUE THREAD

**Issue by jumbosushi** [paypal/PayPal-node-SDK#220]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): none
- Version of node.js used: v6.4.0
- SDK Version: 1.7.0

### Issue Description

Configure returns an error if I follow the READ.ME.
When I try:
`
paypal.configure({
    'mode': 'sandbox',
    'client_id': PAYPAL_ID,
    'client_secret': PAYPAL_SECRET
  });
`
I get:
`
Uncaught Error: Invalid value for opts.mode
`

Had to change the mode to 'default' for the configuration to go through

**Comment by bluk** [comment]
Are you able to run the samples? Also, is there anything more in the error's backtrace that you can share? Thanks.

**Comment by jumbosushi** [comment]
I could not run the samples :/
That error message is the only msg I got. 

With that being said, Chrome Dev tool pumped out the following error in the source so I changed to default based on if statements in the source

![screen shot 2016-11-07 at 10 21 16 am](https://cloud.githubusercontent.com/assets/9669739/20070072/f3b8aa8e-a4d3-11e6-8871-16557a90ca80.png)

**Comment by bluk** [comment]
Please see https://github.com/paypal/PayPal-node-SDK/issues/149#issuecomment-214805395 . It seems that you are trying to run this code in the browser which may be a security problem. If the user has access to your credentials or have an access token, they can do anything that you can do as a merchant (e.g. create more payments, refund people money, etc.).

**Comment by jumbosushi** [comment]
You're totally right 😱 
I'm glad I caught before going further haha
