### ISSUE TITLE
INTERNAL_SERVICE_ERROR while creating payment

### ISSUE THREAD

**Issue by wudong** [paypal/PayPal-node-SDK#221]
### General Information

- Mode (Sandbox):
- PayPal-Debug-ID(s) (a9fbdeca9aca0):
- Version of node.js used: 4.2.3
- SDK Version: 1.7.0

### Issue Description

I cannot create payment at the moment with the sandbox
payload looks like (return urls omitted): 

```
  var paypalPayment = {
        "intent": "sale",
        "payer": {
            "payment_method": "paypal"
        },
        "transactions": [{
            "amount": {
               "total": "100",
                "currency": "GBP"
            }
        }]
    };

```
Response got: 

`{"response":{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"a9fbdeca9aca0","httpStatusCode":500},"httpStatusCode":500}`

Also, how can I see the details of the debug_id? I couldn't see any in the sandbox transaction.

**Comment by pp-randy** [comment]
The debug helps PayPal Technical Support to troubleshoot issues.

I am tracking the current issue with intermittent 500 errors in the sandbox here: paypal/PayPal-PHP-SDK#707 please follow this issue for further updates.
