### ISSUE TITLE
Internal Service Error when creating Payout on sandbox

### ISSUE THREAD

**Issue by benliu01** [paypal/PayPal-node-SDK#224]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 50d5336963ca1, 46c6e5f8ce5b1
- Version of node.js used: 4.6.0
- SDK Version: 1.7.0

### Issue Description
I'm attempting to create a simple test Payout on the sandbox, but I always receive an internal service error.  I've pretty much followed this [example](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payout/create_single_payout.js).
Here is my code leading up to the payout creation:

                var paypal = require('paypal-rest-sdk');
                paypal.configure({
                  'mode': 'sandbox', //sandbox or live
                  'client_id': 'myid',
                  'client_secret': 'mysecret'
                });
                var sender_batch_id = Math.random().toString(36).substring(9);

                var create_payout_json = {
                    "sender_batch_header": {
                        "sender_batch_id": sender_batch_id,
                        "email_subject": "You have a payment"
                    },
                    "items": [
                        {
                            "recipient_type": "EMAIL",
                            "amount": {
                                "value": 10,
                                "currency": "USD"
                            },
                            "receiver": "replaced-email@gmail.com",
                            "note": "Thank you.",
                            "sender_item_id": "item_3"
                        }
                    ]
                };

                var sync_mode = 'true';

                paypal.payout.create(create_payout_json, sync_mode, function (error, payout) {
                    if (error) {
                        console.log(error.response);
                        throw error;
                    } else {
                        console.log("Create Single Payout Response");
                        console.log(payout);
                    }
                });
  
The log prints out as:
    { 
      name: 'INTERNAL_ERROR',
      message: 'An internal service error has occurred.',
      debug_id: '46c6e5f8ce5b1',
      information_link: 'https://developer.paypal.com/docs/api/payments.
      httpStatusCode: 500 
    }

I'm not sure if this is related to https://github.com/paypal/PayPal-PHP-SDK/issues/707.  But that issue is closed so I figured I'd open an one in case it's separate.

Let me know if there's any other info that would help.  Thanks!

**Comment by bluk** [comment]
Thanks for the error report. For internal tracking, I've opened internal issue PPPLPAYPT-14603 to help resolve this. It should not be related to the other issue.

**Comment by benliu01** [comment]
Thanks for the response!  Let me know if there's anything else you need from me.

**Comment by bluk** [comment]
This should have been resolved earlier today (or late last night depending on your time zone). If you still encounter this issue, please leave a comment or open a new issue. Thanks!

**Comment by benliu01** [comment]
Thank you! I am able to get a sandbox payout through now just fine.
