### ISSUE TITLE
paypal.payment.create() DUPLICATE_REQUEST_ID

### ISSUE THREAD

**Issue by xylon01** [paypal/PayPal-node-SDK#225]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 796b16bb1fc49
- Version of node.js used: 4.2.2
- SDK Version: 1.6.9

### Issue Description

Following is my code.

`var create_payment_json = {
    "intent": "sale",
    "payer": {
        "payment_method": "credit_card",
        "funding_instruments": [{
            "credit_card": {
                "type": req.body.type,
                "number": req.body.credit_card,
                "expire_month": req.body.expire_month,
                "expire_year": req.body.expire_year,
                "cvv2": req.body.cvv,
                "first_name": req.body.first_name,
                "last_name": req.body.last_name
            }
        }]
    },
    "transactions": [{
        "amount": {
            "total": "50",
            "currency": "USD",
        },
        "description": "This is the payment transaction description."
    }]
};

paypal.payment.create(create_payment_json, function (error, payment) {
    if (error) {
        return res.json({
                        success: false,
                        message: error,
                    });
    } else {
        console.log("Create Payment Response");
        console.log(payment);
        return res.json({
                        success: true,
                        message: payment,
                    });
    }
});`

for the first few calls it worked perfectly fine. Then I tried to do a failed payment to check the response it fails. Then I tried to do a proper call and I started getting the follow error response from payapl

{
  "success": false,
  "message": {
    "response": {
      "name": "DUPLICATE_REQUEST_ID",
      "message": "PayPal-Request-Id header was already used.",
      "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_REQUEST_ID",
      "debug_id": "796b16bb1fc49",
      "httpStatusCode": 400
    },
    "httpStatusCode": 400
  }
}

**Comment by bluk** [comment]
Hi, the underlying error seems to indicate the domestic transaction is unsupported. Please ensure that [your account is supported for credit card transactions](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/). Usually this is because the sandbox merchant account is located in an unsupported country. Note that currently, only UK merchant accounts are fully supported for direct credit card transactions in the REST API.
