### ISSUE TITLE
regular TRANSACTION_REFUSED errors

### ISSUE THREAD

**Issue by leemhenson** [paypal/PayPal-node-SDK#228]
### General Information

- Mode: Live
- PayPal-Debug-ID(s) (from any logs): `a9ffa660586f4`, `4809141778f7 `, `121268b64dd91 `, ...
- Version of node.js used: 6.9
- SDK Version: 1.7

### Issue Description

We're seeing regular responses from paypal that look like this:

```json
{
  "name": "TRANSACTION_REFUSED",
  "details": [],
  "message": "The request was refused",
  "information_link": "https://developer.paypal.com/docs/api/#TRANSACTION_REFUSED",
  "debug_id": "121268b64dd91",
  "httpStatusCode": 400
}
```

The information_link doesn't actually show you any information about the error message. Can you give me some extra info to aid debugging why we get these responses? We make lots of successful charges through paypal express through the same code path, so there must be something unique to these particular transactions.

**Comment by bluk** [comment]
For these errors and since they are on production, please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com). The SDK team does not have access to live account information.
