### ISSUE TITLE
No amount is being deducted from paypal on successful payment. 

### ISSUE THREAD

**Issue by bluerid** [paypal/PayPal-node-SDK#232]
### I am not sure what can be causing the issue, but on successful payment no amount is being deducted from my account. I tried this with both live account and sandbox account. 

- Mode (Live):
- PayPal-Debug-ID(s) (not sure):
- Version of node.js used: v5.6.0
- SDK Version: 1.7.1 

### Issue Description

> When I submit to paypal with success and cancel urls the payment is being shown as successful one (even with live client_id) and I am receiving success response with token, PayerID, paymentId etc, but no amount is being paid to the account for client id and no amount is being deducted from payer account.

Receiving PayPal A/c: Indian

**Comment by bluerid** [comment]
Issue is resolved now. I was not executing the payment from SDK. So I had to call the _paypal.payment.execute_ method after redirection to success url.

**Comment by ppmtscory** [comment]
@bluerid thank you for the update and don't hesitate to let us know if you run into any other issues.  For errors that are not actually issues with the SDK itself, feel free to reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team as well.
