### ISSUE TITLE
Create Billing Agreement By Card Id

### ISSUE THREAD

**Issue by nguyenhose** [paypal/PayPal-node-SDK#233]
hi, I just wonder if we can create billing agreement by stored card id .
Use case: I let user input their card information and store card_id to db. When create billing agreement, I want to use payer as "credit_card" method, but I don't know if it's necessary to retrieve card information or just using card_id (like stripe api)

**Comment by ppmtscory** [comment]
Unfortunately this isn't an option right now, but the enhancement is being tracked [here](https://github.com/paypal/PayPal-Python-SDK/issues/60) so keep an eye over there for any updates.
