### ISSUE TITLE
Using payout without asking for client_id and secret

### ISSUE THREAD

**Issue by devconcept** [paypal/PayPal-node-SDK#235]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used: 6.9.2
- SDK Version: 1.7.1

### Issue Description

I'm trying to implement payouts but unlike simple payments there is no login/approve flow to ask for user authorization.

I tried to get a token using the identity API and tried to pass it in a headers configuration like this

    config = {
        headers: {
            Authorization: Bearer <token>
        }
    }

which didn't work because this block of code where calls are made

https://github.com/paypal/PayPal-node-SDK/blob/master/lib/api.js#L142

    if (http_options.client_id in token_persist && !utils.checkExpiredToken(token_persist[http_options.client_id]) && !http_options.refresh_token) {
        http_options.headers.Authorization = "Bearer " + token_persist[http_options.client_id].access_token;
        client.invoke(http_method, path, data, http_options, function (error, response) {
            // Don't reprompt already authenticated user for login by updating Authorization header
            // if token expires
            if (error && error.httpStatusCode === 401 && http_options.client_id && http_options.headers.Authorization) {
                http_options.headers.Authorization = null;
                updateToken(http_options, cb, retryInvoke);
            } else {
                cb(error, response);
            }
        });
    } else {
        updateToken(http_options, cb, retryInvoke);
    }

makes `client_id` usage mandatory. Also later I read that Identity tokens are for other use case like using PayPal as your OpenId provider.

So if this is the case using payout is useless when you are trying to implement a payment from a customer to several merchants at the same time, because prompting a user for its secret credentials doesn't seem the right way to me.
 Is there something I'm missing here or payouts are intended to be used only with client_id & secret combination? Is there any other way to execute this call with something like a login and a redirect?

PD: I'm aware that a OAuth token is obtained before making any calls but the client_id & secret are required to obtain the token.

**Comment by bluk** [comment]
The Payouts API should require a client ID/secret that you obtain from the [REST applications dashboard](https://developer.paypal.com/developer/applications/) (you may have to login). This API could be used to pay out funds from a merchant account to other PayPal accounts.

You should contact [PayPal Support](https://www.paypal.com/us/selfhelp/home) to help find a solution that meets your needs (e.g. you can set the [`payee`](https://devblog.paypal.com/setting-payee/) in a payment which may solve some use cases).
