### ISSUE TITLE
billingPlan.update rejects some forms of valid RFC 6902 patches

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [paypal/PayPal-node-SDK#239]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 7b824f74bd455
- Version of node.js used: 6.2.2
- SDK Version: 1.7.1
- References: RFC 6902 - https://tools.ietf.org/html/rfc6902 and PayPal Common JSON Patch https://developer.paypal.com/docs/api/payments.billing-plans#definition-common_json_patch:v1
- Other Relevant Libraries used: https://github.com/Starcounter-Jack/JSON-Patch

### Issue Description

billingPlan.update does not correctly process some forms of valid RFC 6902 patches. The major issue is we attempt to use a popular library to generate JSON patches based on local changes in the document and then submit the patches to PayPal. Library generates them in the non-working form.

working
          patch = 
```json
[
  {
    "op": "replace",
    "path": "/",
    "value": {
      "state": "ACTIVE"
    }
  }
]
```
not working
          patch = 
```json
[
  {
    "op": "replace",
    "path": "/state",
    "value": "ACTIVE"
  }
]
```

**Comment by MichaelLeeHobbs** [comment]
Also, neither of these work:
[
   {
     "op": "replace",
     "path": "/payment_definitions/0/name",
     "value": "Premium - Monthly"
   }
 ]
OR
[
   {
     "op": "replace",
     "path": "/payment_definitions/0",
     "value": {
       "name": "Premium - Monthly"
     }
   }
 ]

The only error you ever get is:

I20170301-11:21:17.629(-5)? {
I20170301-11:21:17.629(-5)?   "error": {
I20170301-11:21:17.629(-5)?     "response": {
I20170301-11:21:17.629(-5)?       "name": "BUSINESS_VALIDATION_ERROR",
I20170301-11:21:17.629(-5)?       "details": [
I20170301-11:21:17.630(-5)?         {
I20170301-11:21:17.630(-5)?           "field": "validation_error",
I20170301-11:21:17.630(-5)?           "issue": "Invalid Path provided."
I20170301-11:21:17.630(-5)?         }
I20170301-11:21:17.630(-5)?       ],
I20170301-11:21:17.630(-5)?       "message": "Validation Error.",
I20170301-11:21:17.630(-5)?       "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#BUSINESS_VALIDATION_ERROR",
I20170301-11:21:17.630(-5)?       "debug_id": "32e7d3917f7a7",
I20170301-11:21:17.631(-5)?       "httpStatusCode": 400
I20170301-11:21:17.631(-5)?     },
I20170301-11:21:17.631(-5)?     "response_stringified": "{\"name\":\"BUSINESS_VALIDATION_ERROR\",\"details\":[{\"field\":\"validation_error\",\"issue\":\"Invalid Path provided.\"}],\"message\":\"Validation Error.\",\"information_link\":\"https://developer.paypal.com/webapps/developer/docs/api/#BUSINESS_VALIDATION_ERROR\",\"debug_id\":\"32e7d3917f7a7\",\"httpStatusCode\":400}",
I20170301-11:21:17.631(-5)?     "httpStatusCode": 400
I20170301-11:21:17.631(-5)?   },
I20170301-11:21:17.631(-5)?   "response": null
I20170301-11:21:17.631(-5)? }

**Comment by pp-randy** [comment]
We will follow up with further with feature requests and some documentation updates.  I tried patching payment_definitions and received an error that patch is not supported.  From my testing only status at this time seems to work which should be more clear in the documentation. 

```
[{
    "path": "/",
    "op": "replace",
    "value": {
      "payment_definitions": [{
          "amount": {
            "currency": "USD",
            "value": 11
          }
        }
      ]
    }
  }
]
```
The error 
`{"name":"BUSINESS_VALIDATION_ERROR","details":[{"field":"payment_definitions","issue":"patch is not supported for this field."}]...`

**Comment by pp-randy** [comment]
I do apologize for the delay in following up with you as well.

**Comment by pp-randy** [comment]
For the state patching format issue please follow here: https://github.com/paypal/PayPal-REST-API-issues/issues/50

**Comment by pp-randy** [comment]
This might explain my issue when trying to patch payment_definitions, I will do more testing https://github.com/paypal/PayPal-REST-API-issues/issues/40

**Comment by MichaelLeeHobbs** [comment]
Thanks for the update.

For anyone else, here is a temporary fix that works about 95% of the time.

    function paypalPatchPathAndValue(path, value) {
      let pathArr = path.split('/')
    
      pathArr.shift()
      if (pathArr[0] > '') {
        let result = {}
        result.value = {}
        result.value[pathArr.pop()] = value
        result.path = '/' + pathArr.join('/')
        return result
      } else {
        return {path: '/', value}
      }
    }
    
    export const paypalPatchFixer = (patches) => {
      return patches.map((patch)=> {
        if (patch.op === "remove") {
          return patch
        }
    
        if ('object' !== typeof patch.value) {
          let newValues = paypalPatchPathAndValue(patch.path, patch.value)
          return {
            "op": patch.op,
            "path": newValues.path,
            "value": newValues.value
          }
        }
        return patch
      })
    }

**Comment by pp-randy** [comment]
Thank you for the example.

Closing this issue out and will track further with these:
https://github.com/paypal/PayPal-REST-API-issues/issues/50
https://github.com/paypal/PayPal-REST-API-issues/issues/40
