### ISSUE TITLE
Getting 500 status code when creating a payment

### ISSUE THREAD

**Issue by davidjtorres** [paypal/PayPal-node-SDK#241]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): No debug id provided by the API
- Version of node.js used: 4.0.5
- SDK Version: 1.7.1

### Issue Description

I use this credit card number for testing 4111111111111111, 2 days ago it worked fine but now  i get this response :
 { [Error: Response Status : 500]
response: { httpStatusCode: 500 },
 response_stringified: '{"httpStatusCode":500}',
 httpStatusCode: 500 }

**Comment by bluk** [comment]
@davidjtorres Can you please create a new [PayPal Sandbox Personal Buyer account](https://developer.paypal.com/developer/accounts/) and use its generated credit card?

Generic credit card testing numbers such as `4111111111111111` do not work well in the PayPal sandbox.
