### ISSUE TITLE
README link 404

### ISSUE THREAD

**Issue by cloud-tribal** [paypal/PayPal-node-SDK#243]
Customizing a **PayPal payment experience** is available as of version 1.1.0 enabling merchants to provide a customized experience to consumers from the merchant’s website to the PayPal payment. Get started with the supported rest methods and samples.

The above link redirects to a 404

**Comment by bluk** [comment]
@cloud-tribal Thanks for reporting the issue. I've updated the links in the README with their new locations.

The [Payment Experience web profiles](https://developer.paypal.com/docs/integration/direct/payment-experience/) documentation you were looking for is now located [here](https://developer.paypal.com/docs/integration/direct/payment-experience/).
