### ISSUE TITLE
Missing `.d.ts` Typings File 

### ISSUE THREAD

**Issue by MattMorgis** [paypal/PayPal-node-SDK#245]
### General Information

- Mode (Sandbox/Live): `Sandbox`
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used: `v6.9.4`
- SDK Version: `v1.7.1`

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

I am using the PayPal-node-SDK in a TypeScript application. As far as I can tell, there is no `.d.ts` file for the SDK. 

From [this StackOverflow post](http://stackoverflow.com/questions/21247278/about-d-ts-in-typescript)
>The `.d.ts` file is used to provide typescript type information about an API that's written in JavaScript. The idea is that you're using something like jQuery or underscore, an existing javascript library. You want to consume those from your typescript code.

>Rather than rewriting jquery or underscore or whatever in typescript, you can instead write the d.ts file, which contains only the type annotations. Then from your typescript code you get the typescript benefits of static type checking while still using a pure JS library.

TypeScript definitions for projects live [here](https://github.com/DefinitelyTyped/DefinitelyTyped) and can be installed into TypeScript projects via npm:
```
npm install @types/payment-rest-sdk --save-dev
```

**Comment by Nisthar** [comment]
@MattMorgis @pp-randy Not working

**Comment by MattMorgis** [comment]
@Nisthar Yeah, the issue is still open and marked as an SDK enhancement. I've been waiting for a rainy day to submit a PR. For now you will have to use it as-is or you could always submit a PR yourself!

**Comment by trainerbill** [comment]
I am working on a Definitely Typed d.ts file.  Someone can assign this to me.

**Comment by lkorth** [comment]
Who would maintain the definitions when the SDK changes?

**Comment by trainerbill** [comment]
@lkorth 
>I am working on a **Definitely Typed** d.ts file. Someone can assign this to me.

;)  I'll update this issue when I submit the PR.

**Comment by trainerbill** [comment]
@MattMorgis 
```
npm install --save-dev @types/paypal-rest-sdk
```

**Comment by pp-randy** [comment]
Closing the issue now that this has been submitted.

**Comment by MattMorgis** [comment]
Thanks @trainerbill!

**Comment by karloluis** [comment]
What is the protocol for v2 typings?
