### ISSUE TITLE
listBillingPlan always returns 204

### ISSUE THREAD

**Issue by cloud-tribal** [paypal/PayPal-node-SDK#247]
I have tried all the samples in multiple configurations and `listBillingPlan` always returns a 204, both in sandbox and in live environments.

What could be done wrong ?

Is there a UI where I can check out my billing plans/billing agreements that don't currently incur transactions?

**Comment by bluk** [comment]
Please ensure that your [list parameters](https://developer.paypal.com/docs/api/payments.billing-plans#plan_list_parameters) are correct. In particular, if you have not activated your billing plan, then it is probably in a `CREATED` state instead of an `ACTIVE` state. So for the sample, you will want to change [this line](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_plans/list.js#L8) to `CREATED` instead or whatever status state that you are looking for.

I don't believe there is currently a merchant UI for billing plans/agreements, so you will need to filter out by status states.

Hope that helps. If not, please leave a comment or open a new issue. Thanks.

**Comment by cloud-tribal** [comment]
I am still getting a 204, no matter the `status` I am filtering with.

Here is the code

```
import paypal from 'paypal-rest-sdk'

const list_billing_plan = {
    'status': 'CREATED',
    'page_size': 5,
    'page': 1,
};

paypal.configure({
  'mode': 'sandbox',
  'client_id': process.env.PAYPAL_CLIENT_ID,
  'client_secret': process.env.PAYPAL_CLIENT_SECRET
});

paypal.billingPlan.list(list_billing_plan, function (error, billingPlan) {
    if (error) {
        throw error;
    } else {
        console.log("Listing all billing plans: ");
        console.log(billingPlan);
    }
});

```

**Comment by bluk** [comment]
@cloud-tribal Are you able to get an individual billing plan that you created (instead of doing a list)? The code above looks correct.

**Comment by bluk** [comment]
Also, you may want to try ```page: 0``` just in case you don't have too many billing plans.

**Comment by cloud-tribal** [comment]
`page:0` throws

`Error: Response Status : 400`

**Comment by cloud-tribal** [comment]
Either way I can't use it [because](https://github.com/paypal/PayPal-REST-API-issues/issues/14#issue-210921510)

**Comment by bluk** [comment]
Thank you for your report. I will raise the issue with the documentation team.

If you need to support credit cards and PayPal, I recommend considering [Braintree Payments](https://www.braintreepayments.com) (a PayPal service). It has a more extensive list of supported countries for credit cards. Braintree offers PayPal as a payment method while offering a simpler integration that supports many different payment methods. You can contact [Braintree Support at the bottom of the documentation page](https://developers.braintreepayments.com/) for any questions and to make sure it meets your needs.

If you have a chance, if you can log the error `console.log(error);` and give the `PayPal-Debug-ID` response header value, that can help us debug this issue so we can fix it.

Hope that helps, and sorry for your frustrating experience.

**Comment by MichaelLeeHobbs** [comment]
@cloud-tribal page: 0 is correct. Here is a set of functions we use to fetch all no matter their status

    const fetchBillingPlanList = (params) => new Promise((resolve, reject)=> {
      Paypal.billingPlan.list(params, (error, list) => (error) ? reject(error) : resolve(list))
    })
    
    const fetchBillingPlanLists = () => new Promise((resolve, reject)=> {
      let params = {
        //'status': 'CREATED',
        'page_size': 20, // max
        'page': 0, // min
        'total_required': 'yes'
      }
      let listing = []
    
      // initial fetch to know how many pages
      fetchBillingPlanList(params)
        .then((list)=> {
          listing = listing.concat(list.plans)
    
          // request additionally pages
          let promises = []
          for (let i = 1; i < list.total_pages; i++) {
            params.page++
            promises.push(fetchBillingPlanList(params)
              .then((list)=>listing = listing.concat(list.plans))
              .catch(reject)
            )
          }
          Promise.all(promises)
            .then(()=>resolve(listing))
            .catch(reject)
        })
        .catch(reject)
    })

**Comment by cloud-tribal** [comment]
@MichaelLeeHobbs Nice, maybe add those to the samples in this repo?
At this point we've migrated to Stripe due to the crippling number of landmines involved with integrating PayPal. 
Feel free to close this issue as I won't be investigating

**Comment by bdentino** [comment]
I am also getting a 204 using the SDK using the code from @MichaelLeeHobbs. Please reopen this issue @bluk as it is currently impossible for me to access the list of my existing billing plans using the node SDK.

**Comment by xiaoleih41** [comment]
@bdentino  Could you please open a new ticket with  your debug ID?
