### ISSUE TITLE
Create Billing Agreement returns Funding Instrument Validation Error

### ISSUE THREAD

**Issue by cloud-tribal** [paypal/PayPal-node-SDK#248]
I'm trying to create a billing agreement in the Sandbox for a Sandbox account with a Sandbox account Credit Card. It always returns a 400 with following error: 

```
[ { field: 'payer',
    issue: 'Funding Instrument Details are missing or Funding instrument not supported. Only credit-card is supported.' } ]
```

One of many `debug_id`'s: `f4dfd7c9570cf`

I have followed the samples in this repository and in the [quickstart](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/).

Here is my code: 
```

import paypal from 'paypal-rest-sdk'

var isoDate = new Date();
isoDate.setSeconds(isoDate.getSeconds() + 4);
isoDate.toISOString().slice(0, 19) + 'Z';

var billingAgreementAttributes = {
    name: "#3 Cool Test Plan 2 Billing Agreement",
    description: "#3 Cool Test Plan 2 for testing purposes Agreement",
    start_date: isoDate,
    plan: {
        id: "P-2V895852BK158725WQX7LVIQ"
    },
    payer: {
        payment_method: "credit_card",
        funding_instruments: [{
          payment_card: {
            type: 'visa',
            number: '4214026474675567',
            expire_month: '02',
            expire_year: '2022',
            cvv2: '123',
            first_name: "Some",
            last_name: "User",
            billing_country: 'CA',
            billing_address: {
              line1: '145 KOOL STREET',
              city: 'TORONTO',
              state: 'ON',
              postal_code: 'M5A2J0',
              country_code: 'CA'
            }
          }
        }]
    },
    shipping_address: {
        line1: "145 KOOL STREET",
        city: "Toronto",
        state: "ON",
        postal_code: "M5A2J0",
        country_code: "CA"
    }
};

// Create the billing agreement

paypal.billingAgreement.create(billingAgreementAttributes, function (error, billingAgreement) {
    if (error) {
        console.log("ERORR HERE: ", error.response.details);
        throw error;
    } else {
        console.log("Created the Billing Agreement, Boss");
        console.log("billingAgreement: ", billingAgreement);

    }
});

```

The CC credentials are taken from the Sandbox account. 

What am I doing wrong ?

**Comment by cloud-tribal** [comment]
I have changed `funding_instruments` to `credit_card` instead of `payment_card` and starting getting billing_country is not a valid field. I then commented that field out. Here is the `funding_instruments` object: 

        funding_instruments: [{
          credit_card: {
            type: 'visa',
            number: '4214026474675567',
            expire_month: '02',
            expire_year: '2022',
            cvv2: '123',
            first_name: "Some",
            last_name: "User",
            // billing_country: 'CA',
            billing_address: {
              line1: '145 KOOL STREET',
              city: 'TORONTO',
              state: 'ON',
              postal_code: 'M5A2J0',
              country_code: 'CA'
            }}}]

And now am receiving the following error:

```
  response:
   { name: 'DPRP_DISABLED',
     message: 'DPRP is disabled for this merchant.',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#DPRP_DISABLED',
     debug_id: 'c354f874d311f',
     httpStatusCode: 400 },
  httpStatusCode: 400 }
```

The link above does not exist. Note the `credit_card` key does not match the [quickstart guide](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/)'s `payment_card` key.

I called PayPal support and they directed me to their support ticket page where I created a ticket.

This is a very frustrating experience as it is the 3rd day I am attempting to issue basic API calls that conform with the docs, with little success due to unpredictable, non-debuggable responses.

We really want to use PayPal for our startup but the API is increasingly difficult to work with, and we're worried it will only get worse once we're in the meat of the integration.

Can anybody confirm that they have a functioning integration with the REST API?

**Comment by MichaelLeeHobbs** [comment]
@cloud-tribal Take a look at https://developer.paypal.com/developer/accountStatus you can enable features for both sandbox and live. Not sure if this will help you as we are not accepting direct payments yet. Secondly, yes we have a functional MVP using sandbox. Biggest issue we have ran into is #239 JSON patches seem to not conform with RFC 6902.

**Comment by cloud-tribal** [comment]
@MichaelLeeHobbs We've abandoned PayPal in favor of Stripe
