### ISSUE TITLE
Paypal is working in sandbox but not in live?

### ISSUE THREAD

**Issue by pazalvin** [paypal/PayPal-node-SDK#251]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by bluk** [comment]
For live issues, please reach out to [PayPal Technical Support](https://developer.paypal.com/support/). Also, if you have a `PayPal-Debug-ID` or other information, that can be helpful.
