### ISSUE TITLE
GetVerifiedStatus in Mass Payments

### ISSUE THREAD

**Issue by basanthalluri** [paypal/PayPal-node-SDK#252]
Hi,

I am using payout in node js which is working fine if the paypal email address is correct. When the paypal email address is wrong i am getting error message but paypal is charging me 0.25 USD as fee for 0.50 USD amount which is unbelievable.

I want to verify the email address is correct or not before doing payout because it saves my 0.25 USD for wrong paypal email address and cancelation fee. 

Please let me know how i can resolve the issue.

Thanks
Basanth

**Comment by xiaoleih41** [comment]
Thank you for your question. In order verify the PayPal email address, I will suggest you to integrate the login with PayPal feature that PayPal offers. By walking the email owner logging into their PayPal account and grant your permission, it will validate the email address for your. 

Please check into [Login with PayPal site](https://developer.paypal.com/docs/integration/direct/identity/log-in-with-paypal/#integration-steps) for detail. Please let us know if you have any further questions.  Thanks,  Xiaolei

**Comment by xiaoleih41** [comment]
I am closing this thread. If you h ave any further questions, please let me know. Thanks, Xiaolei
