### ISSUE TITLE
Live transactions appear on the developer site but don't turn up in the users activity list

### ISSUE THREAD

**Issue by skywickenden** [paypal/PayPal-node-SDK#253]
Everything seems to go fine with the transaction and if I look at https://developer.paypal.com/developer/dashboard/live/ then the transaction appears on the list.

However when I go to https://www.paypal.com/businessexp/transactions to look at the transaction in the normal users account it is missing.

Definitely using the live client_id and secret. mode is set to live. They appear in the live transactions list on developer. Then disapear into a block whole.

It is a UK business account if that makes a difference. (Being in the UK has caused problems before).

**Comment by bluk** [comment]
Since this is a live production issue with real accounts, please contact [PayPal Technical Support](https://developer.paypal.com/support/) who has more access to the information that can help you resolve this issue.
