### ISSUE TITLE
Billing agreement execute

### ISSUE THREAD

**Issue by UlyssesCB** [paypal/PayPal-node-SDK#255]
After I have the approval URL and redirect my client, how will I know when to execute the contract through the execution URL?

Also, actually I need to set the payment_method as "credit_card" (according to the docs I won't need to redirect my customer to the aprroval URL) but when I do that I got the follow issue:

"message": "DPRP is disabled for this merchant.",
"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DPRP_DISABLED",

Why is that happening?

**Comment by pp-randy** [comment]
`After I have the approval URL and redirect my client, how will I know when to execute the contract through the execution URL?`
When the client gets redirected to the return_url value of merchant_preferences specified in your Plan.  This should be different than the cancel_url value so you know if they approved or not.  You might find lines 11 and 14 of the [Plan Create Sample](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_plans/create.js#L11-L14) helpful.  The client will be redirected by PayPal to this return_url and that is when you execute. 

`Also, actually I need to set the payment_method as "credit_card" (according to the docs I won't need to redirect my customer to the aprroval URL) but when I do that I got the follow issue:`
What is your sandbox account email address?  I will try to enable the DPRP functionality for you.  DPRP is Direct Payment Recurring Payment lingo from the Classic API.

**Comment by UlyssesCB** [comment]
Okay, Randy! Working on that right now!

My sandbox address is: ulysses.informatica@gmail.com

So, more two thoughts:
1 - With the DPRP enable will I be able to redirect my customer to the URL (of course, after I get and validate the payment's infos), without the approval URL, right?
2 - After sandbox, should I have some problem to activate the DPRP on live?

By the way, I'm from Brazil so I'll be getting paid in BRL. But I do not think this will be a problem.

**Comment by pp-randy** [comment]
The redirect url is only used for a PayPal funded payments.  You should be able to use PayPal funded payment but credit card is processing is only available on UK and some US accounts currently with the REST API.  

I would encourage you to reach out to the Brazil Merchant Team here: https://www.paypal.com/br/webapps/mpp/accept-payments-online they would be more knowledgeable about what types of integrations are available.
