### ISSUE TITLE
Create billing agreement throws Response status code 400

### ISSUE THREAD

**Issue by JagadeeswararaoChappa** [paypal/PayPal-node-SDK#257]
debug id : 		"debug_id": "6a9d0e5b6e0c9",
=====================
Request:

{
	"body": {
		"name": "Standard Membership",
		"payer": {
			"payment_method": "credit_card",
			"funding_instruments": [
				{
					"credit_card_token": {
						"credit_card_id": "CARD-6XW44362FA1918457LDRZPMA",
						"payer_id": "3434328"
					}
				}
			]
		},
		"plan": {
			"id": "P-7P532004V8901963AHENS7XQ"
		},
		"shipping_address": {
			"city": "*********",
			"state": "**",
			"postal_code": "*********",
			"country_code": "US",
			"line1": "*********"
		},
		"start_date": "2017-04-04T13:29:00.480Z",
		"description": "Food of the World Club Standard Membership"
	},
	"header": {
		"x-pp-ads-performed": "true",
		"content-length": "445",
		"paypal-request-id": "8cef3c84-7238-43c4-8da8-56aa1a557eec",
		"x-pp-silover": "name=SANDBOX3.API.1&silo_version=1880&app=platformapiserv&TIME=2610946904&HTTP_X_PP_AZ_LOCATOR=",
		"connection": "close",
		"accept": "application/json",
		"client-auth": "No cert",
		"host": "api.sandbox.paypal.com",
		"user-agent": "PayPalSDK/PayPal-node-SDK 1.7.1 (node v6.9.5-ia32-linux; OpenSSL 1.0.2k)",
		"x-pp-idempotencyid": "6a9d0e5b6e0c9_1491312539",
		"x-slr-orig-script_uri": "https://api.sandbox.paypal.com/v1/payments/billing-agreements/",
		"x-pp-slingshot-targetapp": "platformapiserv",
		"x-pp-corrid": "6a9d0e5b6e0c9",
		"pp_remote_addr": "219.91.207.254",
		"content-type": "application/json",
		"authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxD0uQ"
	},
	"additional_properties": {},
	"method": "POST"
}

=============================================
Response:
{
	"status": 400,
	"duration_time": 27,
	"body": {
		"message": "Invalid request. See details.",
		"debug_id": "6a9d0e5b6e0c9",
		"details": [
			{
				"field": "payer",
				"issue": "Funding Instrument Details are missing or Funding instrument not supported. Only credit-card is supported."
			}
		],
		"name": "VALIDATION_ERROR",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR"
	},
	"additional_properties": {},
	"header": {
		"APPLICATION_ID": "APP-80W284485P519543T",
		"Content-Language": "*",
		"CALLER_PARTY_ID": "2032482913770967435",
		"paypal-debug-id": "6a9d0e5b6e0c9",
		"CLIENT_ID": "AUaDVuQ7Z8H_1U9C-6dSqqbzuY7bPI1ukig3JGiqRYS7MHxYXP2_-MG8OCSGB_i0ktmOa7Z_JfiHZ81x",
		"Date": "Tue, 04 Apr 2017 13:28:59 GMT",
		"CALLER_ACCT_NUM": "2032482913770967435"
	}
}

**Comment by pp-randy** [comment]
I apologize Credit Card tokens (vaulted credit cards) are not supported for Billing Agreement creation. 

We are tracking the enhancement request here: https://github.com/paypal/PayPal-REST-API-issues/issues/3

Please let me know if you need further assistance.  Feel free to comment on the above issue as well.

**Comment by JagadeeswararaoChappa** [comment]
Thanks pp-randy  for quick response . if i want create billing agreement i have to go directly with creditcard information right? please confirm.

**Comment by pp-randy** [comment]
Yes, you need to provide the [credit card object](https://developer.paypal.com/docs/api/payments.billing-agreements#definition-credit_card) or use PayPal.  

Example here https://developer.paypal.com/docs/api/payments.billing-agreements#definition-funding_instrument
```
 "funding_instruments": [
  {
    "credit_card":
    {
    "type": "visa",
    "number": "XXXXXXXXXXXX",
    "expire_month": "",
    "expire_year": "",
    "cvv2": "",
    "first_name": "",
    "last_name": "",
    "billing_address":
    {
      "line1": "",
      "line2": "",
      "city": "",
      "state": "",
      "postal_code": "",
      "country_code": ""
    }
    }
  }]
```

Also ensure you are using a US or UK account as those countries support REST credit card payments.
