### ISSUE TITLE
Billing plan list always returns {"httpStatusCode":204}

### ISSUE THREAD

**Issue by JagadeeswararaoChappa** [paypal/PayPal-node-SDK#258]
Below is my code. I have created some plans and made it active. But i'm not able to get list of plans by using below code.
And i'm seeing it is successful transaction under transactions list (URL : /v1/payments/billing-plans/)  
Throw the status {"httpStatusCode":204} in billingPlan
 var list_billing_plan = {
      'status': 'ACTIVE',
      'page_size': 5,
      'page': 1,
      'total_required': 'yes'
     };

    paypal.billingPlan.list(list_billing_plan, function (error, billingPlan) {
        if (error) {
            throw error;
        } else {
            console.log("List Billing Plans Response");
            console.log(JSON.stringify(billingPlan));
            callback(null,billingPlan);
        }
    });

**Comment by pp-randy** [comment]
The default state is CREATED.  Have you patched and plans to be active?  https://developer.paypal.com/docs/api/payments.billing-plans#plan_update

**Comment by JagadeeswararaoChappa** [comment]
Yes , updated to Active with below code.
 var billingPlanUpdateAttributes = [{
            "op": "replace",
            "path": "/",
            "value": {
                "state": "ACTIVE"
            }
        }];

        paypal.billingPlan.create(billingPlanAttribs, function (error, billingPlan){
            if (error){
                console.log(error);
                throw error;
            } else {
                // Activate the plan by changing status to Active
                paypal.billingPlan.update(billingPlan.id, billingPlanUpdateAttributes, 
                    function(error, response){
                    if (error) {
                        console.log(error);
                        throw error;
                    } else {
                        console.log(billingPlan.id);
                        callback(null,billingPlan.id);
                        
                    }
                });
            }
        });

Even i tried to get 'CREATED' plans also but resulting same.

**Comment by pp-randy** [comment]
Can you grab the paypal-debug-id from the response headers?  Also maybe one from a Create and the List so I can try to get a full picture.

**Comment by pp-randy** [comment]
Have you tried page 0?  You would need more than 5 Active plans for any to show up. 

![image](https://cloud.githubusercontent.com/assets/6819909/24712867/ab19449c-19e9-11e7-8c28-dc2cbca49281.png)

**Comment by fiatjaf** [comment]
What do you mean "you need more than 5 for any to show"? Page 0 is the default, right? If I have one plan I can't get it? Should I create 4 dummy plans then?

**Comment by pp-randy** [comment]
@fiatjaf if you have one plan page 0 should work if the status parameter is correct for that plan.  Are you getting this error as well?  Can you snag a paypal-debug-id from the API response headers?

**Comment by fiatjaf** [comment]
No, no, I was about to comment here again that I didn't experience any errors. I just got confused by your comment before I started trying.

**Comment by pp-randy** [comment]
Sorry about that, and thank you for asking.  I updated my previous response to hopefully clear up any confusion.

**Comment by pp-randy** [comment]
@JagadeeswararaoChappa did you get this working?

**Comment by pp-randy** [comment]
Closing due to lack of further responses.

**Comment by blackaiubiun** [comment]
I am facing the same issue.I am trying to get all the list from https://api.sandbox.paypal.com/v1/payments/billing-plans  API.Every time it through me 204 http  code.Since,204 is a http success status code it dosen't give me any debug id.

**Comment by xiaoleih41** [comment]
@blackaiubiun can you create a new issue instead with your query code?
