### ISSUE TITLE
Sandbox Payout: INTERNAL_ERROR - An internal service error has occurred

### ISSUE THREAD

**Issue by mrvautin** [paypal/PayPal-node-SDK#260]
### General Information

Mode (Sandbox/Live): Sandbox
PayPal-Debug-ID(s) (from any logs): f2dd749185d8b, f2dd749185d8b
Version of node.js used: 6.0.0
SDK Version: 1.7.1

### Issue description

I'm attempting to create a simple test Payout on the sandbox, but I always receive an internal service error. I've pretty much followed this example.
Here is my code leading up to the payout creation:

            var paypal = require('paypal-rest-sdk');
            paypal.configure({
              'mode': 'sandbox', //sandbox or live
              'client_id': 'myid',
              'client_secret': 'mysecret'
            });
            var sender_batch_id = Math.random().toString(36).substring(9);

            var create_payout_json = {
                "sender_batch_header": {
                    "sender_batch_id": sender_batch_id,
                    "email_subject": "You have a payment"
                },
                "items": [
                    {
                        "recipient_type": "EMAIL",
                        "amount": {
                            "value": 10,
                            "currency": "USD"
                        },
                        "receiver": "replaced-email@gmail.com",
                        "note": "Thank you.",
                        "sender_item_id": "item_3"
                    }
                ]
            };

            var sync_mode = 'true';

            paypal.payout.create(create_payout_json, sync_mode, function (error, payout) {
                if (error) {
                    console.log(error.response);
                    throw error;
                } else {
                    console.log("Create Single Payout Response");
                    console.log(payout);
                }
            });

The log prints out as:
{
name: 'INTERNAL_ERROR',
message: 'An internal service error has occurred.',
debug_id: '46c6e5f8ce5b1',
information_link: 'https://developer.paypal.com/docs/api/payments.
httpStatusCode: 500
}

**Comment by pp-randy** [comment]
I was able to submit a payout earlier today and in many cases 500 errors are temporary. 

Are you still seeing this error?  If so, would you be able to provide an new debug_id; unfortunately, I was not able to pull any logs for the one already provided. 

A note on ` var sync_mode = 'true';`  
Synchronous payouts are deprecated https://developer.paypal.com/docs/integration/direct/payouts/#payout-modes

**Comment by mrvautin** [comment]
Thanks. Here are some fresh debug ID's: b480dfb76516e, b480dfb76516e

Note: I was trying `sync_mode` as async was not working for me.

**Comment by pp-randy** [comment]
I am seeing a currency of AUD in that last Debug_id.  You would need AUD balance at a minimum for the payout.  Your example shows USD does that still fail? You have plenty of USD balance.  It looks like a denied error, did you get an internal error with that last one? 

Does USD to a US buyer sandbox account work?

**Comment by mrvautin** [comment]
hmm this is embarrassing... I would have thought an "Insufficient funds" response would be returned on a transaction which doesn't have funds in that currency?

Anyway, the currency I was setting was the issue and changing to USD works fine now. Thanks for your help @pp-randy!

**Comment by pp-randy** [comment]
I agree.  I will do some testing and follow up further the error messaging.
