### ISSUE TITLE
Subscription management, specifically subscription cancellations

### ISSUE THREAD

**Issue by sproleee** [paypal/PayPal-node-SDK#261]
General information

**SDK/Library version:** 1.7.1
**Environment:** Sandbox
**PayPal-Debug-ID values:** 76db74c4c6638
**Language, language version, and OS:** Node version 6.10.2 on Windows 10

Issue description

I'm not sure if this is a Sandbox issue or not or an API issue or something I'm doing wrong, but I can't seem to get subscription cancellations to work with this API. I always get the `The profile ID is invalid` message.

When the user subscribes to a recurring payment/subscription, I use the agreement ID and store it in a database (in this case, the ID is `P-4KH18254J5916671UPC2HU7I`). The ID's are always prefaced with a letter "P". Anyway, when the user clicks to unsubscribe, I use the stored ID to connect with the agreement ID and cancel it. However, I get the following error:
```

{ [Error: Response Status : 400]
response:
{ name: 'INVALID_PROFILE_ID',
message: 'The profile ID is invalid',
information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#INVALID_PROFILE_ID',
debug_id: '76db74c4c6638',
httpStatusCode: 400 },
response_stringified: '{"name":"INVALID_PROFILE_ID","message":"The profile ID is invalid","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_PROFILE_ID","debug_id":"76db74c4c6638","httpStatusCode":400}',
httpStatusCode: 400 }
```

I'm not sure if I'm doing something wrong, or if there is something with this API in sandbox mode.

**Comment by pp-randy** [comment]
The agreement ID would start with an `I-`.   The `P-` is most likely the Plan Id.

An example is here for the Execute call for a PayPal funded Agreement ID:
[billing-agreements#agreement_execute](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_execute)

```
{
  "id": "I-1TJ3GAGG82Y9",
  "state": "Active",
  "description": "Monthly agreement with free trial payment definition.",
  "payer": {
    "payment_method": "paypal", ...
```

**Comment by sproleee** [comment]
@pp-randy Thanks for the response.

It looks like that I never execute the billing agreement. I followed the code on this page: https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/create.js

I merely create the plan, create the billing agreement and then update the plan to active state. Nowhere in this chain of events do I execute the billing agreement. 

For execution, this should be established: https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/execute.js

So I would assume that the EC/payment token will be accessible via the payment plan creation callback?

**Comment by pp-randy** [comment]
Here is the gist of how to do it.  

1) Create Plan
2) Activate Plan
3) Create Billing Agreement (For Credit Card this is the final step) 
4) Redirect the payer to PayPal with the [Approval URL](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/create.js#L147).
5) When the payer returns to your site Execute the payment.  The EC token will be provided in the URL when the payer returns as `token`.  

You should be aware that unlike Payments, you don't get the ID (agreement id) until the execute completes, we have a feature tracking an improvement here: https://github.com/paypal/PayPal-REST-API-issues/issues/19.  As a workaround to this some developers will also parse out the token from that approval url to track things easier on their end.

**Comment by sproleee** [comment]
@pp-randy Thanks for your help. This clears it up for me.

**Comment by pp-randy** [comment]
I'm glad I could help.  Feel free to reach out if you have further questions.

**Comment by sproleee** [comment]
Apparently, the token I parsed from the `return_url` via the billing agreement creation's response is invalid. This is the error I'm receiving: 

`{"name":"INVALID_TOKEN","message":"Token is invalid.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_TOKEN","debug_id":"11bafd45b087"}'`

It's a valid token (in this case, `EC-3JT840930S211471D`).

Do I actually have to redirect the person to the payment execution URL that is given to me? I'm using Paypal Express Checkout, so redirecting the person to that URL would be a nightmare.

**Comment by pp-randy** [comment]
Yes you need to redirect them to PayPal with the Approval Url.  Redirecting a person to PayPal is required for Express Checkout to work.

**Comment by pp-randy** [comment]
If you don't want to do a redirect, would your integration support our checkout.js? https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/basic-integration/

**Comment by pp-randy** [comment]
If you don't want to do a redirect, would your integration support our checkout.js? https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/basic-integration/

**Comment by sproleee** [comment]
Hey Randy,

I'm currently using the integration in the link you provided. I have the paypal button loading in an iframe and have the payment and onAuthorize methods working. I'm just not sure how to force a redirect via this method once the execute URL is found. I guess that's the root of the question.

**Comment by pp-randy** [comment]
In checkout.js payment is called when and the PayPal popup is created; this is essentially replacing a full page redirect to PayPal. 

If onAuthorize is called the redirect to PayPal should have happened and buyer authorized the payment.  

You shouldn't need to redirect to PayPal again.  

In your onAuthorize you can call your server to complete the execute, an example is here https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/advanced-integration/. 

paypal.request is an http library and supports GET and POST methods.

**Comment by pp-randy** [comment]
what value is your payment function returning?

**Comment by sproleee** [comment]
So I am doing everything like I'm supposed to. I still get the invalid token error for some reason, which I thought was because I wasn't redirecting manually.

The payment function is the PAY id (like `PAY-13B823781E248220PLD3HRPY`). The the onAuthorize is called, where I execute the payment and create the subscription and trying (but failing) to execute the subscription due to the invalid token error.

**Comment by pp-randy** [comment]
For your Billing Agreement flow (since it doesn't have a Payment ID like Payments) you should return the EC token value you parsed out in the payment function on the client side.  

The simple example would be, you could Ajax this in as well. 
```
        payment: function() {
            return "EC-4L193237S4713824V";			
        }
```

**Comment by sproleee** [comment]
Alright. I returned the token like you explained above and now I have a different, business validation error popping up.

`{"name":"BUSINESS_VALIDATION_ERROR","details":[{"field":"validation_failure","issue":"Invalid Payment Token."}],"message":"Validation Error.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#BUSINESS_VALIDATION_ERROR","debug_id":"57361f725dbd1"}`

I can't find anything in the docs about that error. The link provided leads to nothing but the main docs page. Any ideas what it could be?

**Comment by sproleee** [comment]
Wait, I might be doing this subscription thing wrong.

So when you try to set up a subscription, you don't actually have to authorize a payment beforehand? Does the subscription execution part create the first charge?

As it stands right now, on the server in the payment function, I actually create the payment via `paypal.payment.create` and then in the `onAuthorize` method, I execute the payment via `paypal.payment.execute`. If this is not how it works. then I assume I'm supposed to create the payment plan in the `payment` method and then in the `onAuthorize` method, I'm supposed to generate the billing agreement and then execute it. Is this correct?

This whole PayPal API is extremely confusing to me.

**Comment by pp-randy** [comment]
No you don't need to do a separate payment for a subscription to be created.  You should use [Billing Agreement Create](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create). 

If you want to charge an amount with the creation you can use the `setup_fee` in the [`merchant_preferences`](https://developer.paypal.com/docs/api/payments.billing-plans#definition-merchant_preferences) under merchant_preferences of the billing plan.  You will also want to review the field `initial_fail_amount_action` parameter as well. 

I will also suggest some documentation changes, looking over [Billing Plans Guide](https://developer.paypal.com/docs/integration/direct/billing-plans-and-agreements/#billing-plans).  I do not see much linking setup_fee to being the initial payment being discussed. 

I will also provide another comment to detail more how to create the Subscription with CheckoutJS.

**Comment by sproleee** [comment]
Randy, thank you for your help. Honestly, a life saver. 

I'm probably going to write a Node tutorial on setting up a PayPal subscription once I get this thing worked out to help other people who may have the same problems as me, so you don't have to answer the same question more than once. I would seriously buy you a coffee or something.

I'll try to brainstorm this myself while waiting for your comment.

**Comment by pp-randy** [comment]
How to Create a Subscription (Billing Agreement) using REST API and CheckoutJS.  This is more complex because CheckoutJS does not have an built in Subscription flow yet like it does with payments, so this does utilize the CheckoutJS Express Checkout flow. 

1. **Server**: https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create
2. **Server or Browser**: Parse out the Express Checkout token from the Approval URL provided in the agreement create response.  The EC token is always 20 characters long, so you could grab the farmost right 20 characters of the href string.
```
  "links": [
    {
      "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-7WN97463LN263864T",
      "rel": "approval_url",
      "method": "REDIRECT"
    }
```
3. **Browser**: return the EC token as a result of the function for `payment` of [`paypal.Button.render object`](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/basic-integration/).  Payment can return a promise or a string as long as the final value is the EC token. 
```
payment: function() {
  return "EC-7WN97463LN263864T"; 
},
```
4. **Browser**: After the buyer completes the PayPal flow `onAuthorize` will be called.  In `onAuthorize` you have a few options.  You can use your `return_url` from your Plan to complete the Execute. CheckoutJS can do this redirect too and `onAuthorize` would look like this.
```
onAuthorize: function(authorizeData, actions) {
   // Triggers full page redirect to the Plan return_url.   
   return actions.redirect();
}
```
You could use paypal.request and post details to an API on your side to do the execute that might look like this.
```
onAuthorize: function(authorizeData) {
   var EXECUTE_PAYMENT_URL = 'URL FOR YOUR API TO EXECUTE';
   // The express checkout token is provided again as paymentToken.
   paypal.request.post(EXECUTE_PAYMENT_URL,  { ectoken: authorizeData.paymentToken})
   .then(function(executeData) { 
       // do something on success.  Subscription should be executed at this point. 
    })
   .catch(function(err) {
       // handle failure flow
   });
}
```

**Comment by sproleee** [comment]
Ah, I see. So we completely skip the plan creation, correct? We just create an agreement, execute it and that's that?

**Comment by pp-randy** [comment]
You need the plan still I will edit the above.

**Comment by sproleee** [comment]
@pp-randy 

Randy, I wan't to thank you for helping me out. Your solution worked wonderfully. You are the best.

**Comment by sairamchinna** [comment]
@randstraw what is the "setup_fee" and "payment_definitions"..? can you please explain in details.?
if am giving "setup_fee" as "0", and in "payment_definations" amount value i mentioned "30.00$" and frequency period is "Day", "auto_billing_cycle" : "Yes". So is that profile deduct the money automatically from the payer details ..? Please let me know TIA..!
