### ISSUE TITLE
Something bad happened

### ISSUE THREAD

**Issue by Levino** [paypal/PayPal-node-SDK#262]
### General information

* SDK/Library version: 1.7.1
* Environment: sandbox
* `PayPal-Debug-ID` values: :"fade814db97ef, fade814db97ef"
* Language, language version, and OS: javascript / node, linux alpine

### Issue description

I try to finalise a payment. Works locally but not on server. Same credentials and account and so on.

The error I am gettting in the callback is ```{}```!!!! And all else I can use for debugging are these weird paypal client logs:
```json
{  
   "date":"Wed, 19 Apr 2017 13:44:49 GMT",
   "server":"Apache",
   "paypal-debug-id":"fade814db97ef, fade814db97ef",
   "content-language":"*",
   "connection":"close",
   "set-cookie":[  
      "X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D3513382744%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Wed, 19 Apr 2017 14:14:49 GMT; domain=.paypal.com; path=/; Secure; HttpOnly",
      "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"
   ],
   "vary":"Authorization",
   "content-length":"1614",
   "content-type":"application/json"
}
```

If anyone can help me with this...

**Comment by pp-randy** [comment]
I'm not seeing an error being returned in our logging.  The logs indicate you are calling the [GET payment method](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/get.js), which is used to lookup payment details.  Did you get a response body with the above request?  

Can you explain more how you are attempting to finalize the payment?  Are you trying to [execute a PayPal payment](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/execute.js#L61-L69)?

**Comment by Levino** [comment]
After further investigation this was caused by something else in the code. My bad, sorry to waste your time.
