### ISSUE TITLE
[Question] PayPal's equivalent to Stripe Connect

### ISSUE THREAD

**Issue by WayneUong** [paypal/PayPal-node-SDK#265]
Hi,
Is there a PayPal's equivalent to Stripe Connect? We need to make payments on behalf of our users.
Thanks.

**Comment by xiaoleih41** [comment]
You can have your users to grant you [ third party permissions ](https://developer.paypal.com/docs/classic/admin/third-party/) so that you can make calls on their behalves.

**Comment by WayneUong** [comment]
Would this work with the new REST API? The docs seems to be for the classics API.

**Comment by jaypatel512** [comment]
Hey @WayneUong ! 

You are correct. That would be based on a Classic API, and would require you to use PayPal Classic SDKs instead. 

The other alternative you have is to use [Braintree Marketplace](https://developers.braintreepayments.com/guides/braintree-marketplace/overview), however, unfortunately, it will not support PayPal as a payment option.

**Comment by WayneUong** [comment]
Hi @jaypatel512 ,
Is this feature in the development pipeline? Our users want to process paypal payments and also want us to do it on their behalf.
Thanks.

**Comment by xiaoleih41** [comment]
@WayneUong It's definitely on our product roadmap to provide some partner features to our marketplace type of clients.

**Comment by vincelwt** [comment]
Any news on this? Is there a way with the current APIs that allow payments to be made on behalf of clients (and take a fee on payments) in the same way as Stripe Connect?
