### ISSUE TITLE
How to handle error (e) in the paypal.payment.execute method.

### ISSUE THREAD

**Issue by bluerid** [paypal/PayPal-node-SDK#267]
How to use an error handler try-catch block with this method? It shows error response which are not handled properly. Can I do something like this? I tried but it shows this.. 

```
try {
  			paypal.payment.execute(paymentId, execute_payment_json, function (error, payment) {
  			    if (error) {
                                console.log(error);
  			        throw error;
  			    } else {
  			      console.log("Get Payment Response");
  			      console.log(JSON.stringify(payment));
  			    }
  			});
      }
      catch(error){
        console.log(error)
      }
```
` { name: 'DUPLICATE_TRANSACTION',
     message: 'Duplicate invoice Id detected.',
     information_link: 'https://developer.paypal.com/docs/api/payments/#errors',
     debug_id: '6124xxxx78x51',
     httpStatusCode: 400 },
  httpStatusCode: 400 }
/media/itobuz-06/storage_aurora1/node_docs/pagespeedv2/routes/index.js:293
  			        throw error;
  			        ^

Error: Response Status : 400
    at IncomingMessage.<anonymous> (/media/itobuz-06/storage_aurora1/node_docs/pagespeedv2/node_modules/paypal-rest-sdk/lib/client.js:136:23)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 `

**Comment by pp-randy** [comment]
I found this article that might be helpful https://bytearcher.com/articles/why-asynchronous-exceptions-are-uncatchable/. 

This is an asynchronous function so your try catch have already finished by the time the callback is executed. 

This is your current callback below.
```
function (error, payment) {
	if (error) {
		console.log(error);
		throw error;
	} else {
		console.log("Get Payment Response");
		console.log(JSON.stringify(payment));
	}
});
```
Instead of using `throw error`, you could call a function to handle the error.  The code you were intending for the catch block you could start with. 
```
function handleError(error) {
	console.log(error);
}

function (error, payment) {
	if (error) {
		console.log(error);
		handleError(error);
	} else {
		console.log("Get Payment Response");
		console.log(JSON.stringify(payment));
	}
});
```

**Comment by bluerid** [comment]
Well, @pp-randy Thx for the tip. It's always hard for me to understand which one is an asynchronous call and which one isn't. However, I will have to read more I guess.
