### ISSUE TITLE
Add support for RAAS

### ISSUE THREAD

**Issue by jimmykane** [paypal/PayPal-node-SDK#268]
Hi there, 

I found out that RAAS is missing from this SDK (and the rest of the SDK's eg PHP etc) 

Are there any plans of integrating this? Should I submit a PR ?

**Comment by pp-randy** [comment]
What do you mean by RAAS?

**Comment by pp-randy** [comment]
The PayPal RAAS API is a limited release API, so it does not get SDK support.

**Comment by jimmykane** [comment]
Great thanks. Good to know.
