### ISSUE TITLE
Refund credit card payment

### ISSUE THREAD

**Issue by ajouve** [paypal/PayPal-node-SDK#270]
### General information

* SDK/Library version: 1.7.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 4791f4fde5314
* Language, language version, and OS: node 7.4.0

### Issue description

I am trying to refund a payment made by card using Paypal but I have an error 500 on refund

    { name: 'INTERNAL_SERVICE_ERROR',
      message: 'An internal service error occurred.',
      information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR',
      debug_id: '4791f4fde5314',
      httpStatusCode: 500 
    },

My code is

    const paypal = require('paypal-rest-sdk');
    const creditCardType = require('credit-card-type');
    const util = require('util')
    
    const card = creditCardType('4111111111111111');
    
    paypal.configure({
      'mode': 'sandbox', //sandbox or live
      'client_id': 'id',
      'client_secret': 'secret'
    });
    
    const paymentObj = {
        intent: 'sale',
        payer: {
            payment_method: 'credit_card',
            funding_instruments: [{
                'credit_card': {
                    number: '4111111111111111',
                    type: card[0].type,
                    'expire_month': 11,
                    'expire_year': 2019,
                    cvv2: 123,
                    'first_name': 'Jon Doe'
                }
            }]
        },
        transactions: [{
            amount: {
                total: '12.12',
                currency: 'EUR'
            }
        }]
    };
    console.log(util.inspect(paymentObj, false, null));
    
    paypal.payment.create(paymentObj, (error, payment) => {
        if(error) console.log(util.inspect(error, false, null));
        console.log(util.inspect(payment, false, null));
        paypal.sale.refund(payment.id, {
            amount: {
                total: '1.99',
                currency: 'EUR'
            }
        }, (error, response) => {
            if(error) console.log(util.inspect(error, false, null));
            console.log(util.inspect(response, false, null));
        })
    })

I don't understand, I am not sure I have to capture the payment if this is a card payment, following the doc I shouldn't
I tried `paypal.sale.refund`, I don't know if there is an other way.

**Comment by xiaoleih41** [comment]
You can refund the sale by using **saleId/transaction ID**. Please refer to the [sample code](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sale/RefundSale.php#L35) in the SDK.

**Comment by ajouve** [comment]
When I do a payment I am receiving

```
{ id: 'PAY-0PR34305EU040664ULE77LLI',
  create_time: '2017-06-13T14:24:45Z',
  update_time: '2017-06-13T14:24:45Z',
  state: 'created',
  intent: 'sale',
  payer:
   { payment_method: 'credit_card',
     funding_instruments:
      [ { credit_card:
           { type: 'visa',
             number: 'xxxxxxxxxxxx1111',
             expire_month: '1',
             expire_year: '2019',
             first_name: 'Jon Doe' } } ] },
  transactions:
   [ { amount:
        { total: '12.12',
          currency: 'EUR',
          details: { subtotal: '12.12' } },
       related_resources: [] } ],
  links:
   [ { href: 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-0PR34305EU040664ULE77LLI',
       rel: 'self',
       method: 'GET' } ],
  httpStatusCode: 200 
}
```

I am passing this id to the refund call and I have an error, is it the wrong id ?

**Comment by xiaoleih41** [comment]
This is `paymentId` not `saleId`.  Please refer to https://github.com/paypal/PayPal-PHP-SDK/issues/854. It's in PHP but you should get the idea on how to retrieve `saleId` in Node.

**Comment by ajouve** [comment]
I made some tests with the following code

```js
const paypal = require('paypal-rest-sdk');

const creditCardType = require('credit-card-type');
const util = require('util')

const card = creditCardType('4111111111111111');

paypal.configure({
  'mode': 'sandbox', //sandbox or live
  'client_id': '****',
  'client_secret': '****'
});

const paymentObj = {
    intent: 'sale',
    payer: {
        payment_method: 'credit_card',
        funding_instruments: [{
            'credit_card': {
                number: '4111111111111111',
                type: card[0].type,
                'expire_month': 11,
                'expire_year': 2019,
                cvv2: 123,
                'first_name': 'Jon Doe'
            }
        }]
    },
    transactions: [{
        amount: {
            total: '12.12',
            currency: 'EUR'
        }
    }]
};
console.log(util.inspect(paymentObj, false, null));

paypal.payment.create(paymentObj, (error, payment) => {
    if(error) console.log(util.inspect(error, false, null));
    console.log(util.inspect(payment, false, null));

    paypal.payment.get(payment.id, (error, result) => {
        if(error) console.log(util.inspect(error, false, null));
        console.log(util.inspect(result, false, null));
    })
})
```

After the create and the get I have exactly the same result:

```
{ 
  id: 'PAY-2EN47092BD589194DLFFJHUA',
  create_time: '2017-06-21T15:42:08Z',
  update_time: '2017-06-21T15:42:08Z',
  state: 'created',
  intent: 'sale',
  payer:
   { payment_method: 'credit_card',
     funding_instruments:
      [ { credit_card:
           { type: 'visa',
             number: 'xxxxxxxxxxxx1111',
             expire_month: '11',
             expire_year: '2019',
             first_name: 'Jon Doe' } } ] },
  transactions:
   [ { amount:
        { total: '12.12',
          currency: 'EUR',
          details: { subtotal: '12.12' } },
       related_resources: [] } ],
  links:
   [ { href: 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-2EN47092BD589194DLFFJHUA',
       rel: 'self',
       method: 'GET' } ],
  httpStatusCode: 200 
}
```

I had a look in the link you gave me and the sale_id should be in the `related_resources` but in my case this is always empty.

**Comment by xiaoleih41** [comment]
Can you try a different credit card number? Get a randomly generated credit card number and try again. The system should throw an error if you use `4111111111111111` as we should not accept this card number anymore.  Also, what's your sandbox account email? I would like to take a look at the setting too.

**Comment by ajouve** [comment]
Working, thanks a lit, it was due to the card number.

**Comment by xiaoleih41** [comment]
Close as the issue has been solved.
