### ISSUE TITLE
Canceling the agreement results in MALFORMED_REQUEST 

### ISSUE THREAD

**Issue by poohitan** [paypal/PayPal-node-SDK#275]
### General information

* SDK/Library version: 1.7.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: `9ffed2a3b859b`
* Language, language version, and OS: Node.js 6.1.0 on Ubuntu 16.10

### Issue description

I'm trying to cancel a Billing Agreement. For some reason I get the 400 response saying that my request if malformed.

The smallest piece of code, which reproduces the issue: 
```javascript
const paypal = require('paypal-rest-sdk'),
  agreementId = 'I-UH1P512B80M9',
  cancelNote = 'Canceling the agreement';

paypal.billingAgreement.cancel(agreementId, cancelNote, (error, response) => {
  if (error) {
    console.error(error);
  }
  ...
});
```
I get this error:

```javascript
{ Error: Response Status : 400
  at IncomingMessage.<anonymous> (/home/ubuntu/staging/current/node_modules/paypal-rest-sdk/lib/client.js:136:23)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at IncomingMessage.wrapped (/home/ubuntu/staging/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
  at IncomingMessage.wrappedResponseEmit [as emit] (/home/ubuntu/staging/current/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:99:26)
  at endReadableNT (_stream_readable.js:926:12)
  at wrapped (/home/ubuntu/staging/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
response:
 { name: 'MALFORMED_REQUEST',
   message: 'The request JSON is not well formed.',
   information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST',
   debug_id: '9ffed2a3b859b',
   httpStatusCode: 400 },
httpStatusCode: 400 }
```

So what's wrong here?

BTW the response includes an [information link](https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST), but it's broken, that page doesn't containt any info about malformed requests. That's an issue too :(

**Comment by poohitan** [comment]
My mistake, the second param should be an object instead of string. it's clearly stated in the example.

So the correct code should looks like
```javascript
const paypal = require('paypal-rest-sdk'),
  agreementId = 'I-UH1P512B80M9',
  cancelNote = 'Canceling the agreement';

paypal.billingAgreement.cancel(agreementId, cancelNote, (error, response) => {
  if (error) {
    console.error(error);
  }
  ...
});
```

**Comment by poohitan** [comment]
Anyway, it would be great, if somebody from PayPal will pass the info about broken link to appropriate person and it will be fixed.

**Comment by xiaoleih41** [comment]
The link was showing you the info on your malformed request. Your cancelled note should be an `agreement_state_descriptor` object. So it should be called as `{ note: "Canceling the agreement" };`

**Comment by poohitan** [comment]
@xiaoleih41 thanks for the reply.
I've provided the link above, it seems to me that that page doesn't contain any info about malformed requests. Isn't it?

**Comment by xiaoleih41** [comment]
It doesn't contain the definition of what malformed request is but it directs you to the sample of what the correct form should be. It can be confusing when the expectations can be different for the link content. I fully understand where you come from. I will bring this to the product team to see if they will consider to make a change.

**Comment by poohitan** [comment]
Thanks :). All I see under that link is just an overview of the API, which doesnt help me at all, and I have a strong feeling of broken page or link, cause when I see an anchor in the link (`#MALFORMDER_REQUEST` in this case), I expect that the page will get scrolled to some section concerning malformed requests, but actually the anchor doesn't do anything...

**Comment by xiaoleih41** [comment]
This issue is tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/104. Please follow that issue for future updates.
