### ISSUE TITLE
Webhook does not trigger new payment actions on sandbox

### ISSUE THREAD

**Issue by miguelcostero** [paypal/PayPal-node-SDK#276]
Hello, I've been using the paypal node SDK to create paypal payments through creditcard my problem is that this transactions are not showing on webhook sandbox console, even when payment have been successfully approved.

**Comment by xiaoleih41** [comment]
Did you follow the [steps](https://developer.paypal.com/docs/integration/direct/webhooks/) to set up Webhooks correctly?

**Comment by miguelcostero** [comment]
@xiaoleih41 yes I did, even the mock webhook simulator is working

**Comment by xiaoleih41** [comment]
I am not sure what your exact issue could be. If you have added webhooks to the app that making those payment calls, you should be able to see it in the webhook event log if you have selected correct app and correct environment ( sandbox or live). I just tested my sandbox account, it worked.

**Comment by miguelcostero** [comment]
Neither do I, all the payments are showed on the app api calls log, but there is no registry on webhook event log.

**Comment by xiaoleih41** [comment]
Please double check how you [subscribe the event inside of your app](https://developer.paypal.com/docs/integration/direct/webhooks/rest-webhooks/#subscribe-to-events).

**Comment by miguelcostero** [comment]
Today I received the webhook notifications from yesterday, I think this could be a timezone problem, I just set the correct timezone for my current location on my paypal-facilitator and my paypal-buyer accounts (not able to set timezone on production account), but all new sales still do not showing up on dashboard, instead I am receiving yesterday sales, what do you think am I doing wrong?

**Comment by xiaoleih41** [comment]
@miguelcostero It is a confirmed issue. Please follow https://github.com/paypal/PayPal-REST-API-issues/issues/103 for future updates on this issue. I am going to close this thread to eliminate duplicates.
