### ISSUE TITLE
Invalid ressource ID (404)

### ISSUE THREAD

**Issue by Blamo27** [paypal/PayPal-node-SDK#279]
### General information

* SDK/Library version: `4.2.0`
* Mode: `Sandbox`
* `PayPal-Debug-ID` values: 60b8fbe9a6142
* Language, language version, and OS: `Debian Jessie, NodeJS v7.8.0`

### Issue description

Webhook does not trigger new payment actions on sandbox (#276)
--> Still not working

I have a problem with the Webhook simulator :

I'm sure that is the correct ID, and I see an error : 'Invalid ressource ID'.
<img src="http://i.imgur.com/RvpphF7.png" />

Webhook event : 
`    paypal.notification.webhookEvent.get(webhookEventId, function (error, webhookEvent) {
      if (error) {
          console.log(error);
          throw error;
      } else {
          console.log("Get webhookEvent Response");
          console.log(JSON.stringify(webhookEvent));
      }
    });
`

**Comment by pp-randy** [comment]
Are you trying to look up a webhook event sent from the simulator?  If so, it only checks connectivity to your listener.  The simulator webhook events cannot be validated or looked up.  

The on-going issue with Payment webhooks not being sent in the sandbox is being tracked here: https://github.com/paypal/PayPal-REST-API-issues/issues/103.

**Comment by Blamo27** [comment]
Yes but I'm not receiving requests when I buy.

IPN isn't working too, so I can't test my paypal back-end system.

**Comment by xiaoleih41** [comment]
Can you provide more detail on "not receiving requests when you buy" and what type of IPN issue do you have? Is it delayed?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit if you have any further information.
