### ISSUE TITLE
Rename functions with keywords.

### ISSUE THREAD

**Issue by trainerbill** [paypal/PayPal-node-SDK#283]
### General information

We have functions for payment.void and webhook.delete.  When typing them it is difficult since void and delete are keywords( function delete / function void ) .  The next version of the SDK we should probably think of different names.

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by pp-randy** [comment]
This should be addressed in the next major version.

**Comment by pp-randy** [comment]
Looks good for the Void example https://github.com/paypal/PayPal-node-SDK/blob/2.0-beta/spec/payments/request/authorizationVoidRequestTest.js.
