### ISSUE TITLE
Update billing plan error

### ISSUE THREAD

**Issue by fernandocalsa** [paypal/PayPal-node-SDK#284]
### General information

* SDK/Library version: 1.7.1
* Environment: Production
* `PayPal-Debug-ID` values: 351c57aea8495, 351c57aea8495
* Language, language version, and OS: NodeJS v6.9.5

### Issue description

I am trying to update a Billing Plan just after create it. I've followed the flow inside the SDK and the call to the API is well formed, and the response has a code 200, however, the response is empty, so in [lib/client.js:L111](https://github.com/paypal/PayPal-node-SDK/blob/master/lib/client.js#L111) is throwing an error because the answer is empty. In the sandbox environment the response has this content type: text/plain; charset=ISO-8859-1. But in production the content type is application/json. I don't know if this difference is something that you are aware and you have to update the SDK or this difference in the API response is an error.

Thank you for your support.

**Comment by pp-randy** [comment]
Thank you for submitting the issue, we will look into the empty response and follow up further.  If you have already coded a solution to handle we would be happy to review a pull request.

**Comment by fernandocalsa** [comment]
Hi Randy thanks for your answer.

I've made a change in order to fix it in my app, but as the behaviour between the sandbox environment and production is not consistent, I think making a change in the SDK is not the best solution, due to the rest of the SDKs should have the same problem.

This was working the first week of this month, but after that something was changed. I think the behaviour in sandbox is more consistent rather the live behaviour.

If you think the problem should be treated here I'll be happy to open a pull request.

Thank you!

**Comment by pp-randy** [comment]
I think you are correct, I see another related error here https://github.com/paypal/PayPal-Ruby-SDK/issues/302

**Comment by pp-randy** [comment]
I will track this issue here, please follow for updates: https://github.com/paypal/PayPal-REST-API-issues/issues/120.

**Comment by fernandocalsa** [comment]
Thank you @pp-randy I will follow the other issue, helpfully we can have a fix soon :D
