### ISSUE TITLE
setup_fee is being charged twice

### ISSUE THREAD

**Issue by poohitan** [paypal/PayPal-node-SDK#288]
### General information

* SDK/Library version: 1.7.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: f788c22346263, 31b816bb27562
* Language, language version, and OS: Node 6.1.0 on Ubuntu 16.10

### Issue description

Hi. For some reason when I'm subscribing to a plan, I'm getting charged twice. This is my Billing Plan definition:

```javascript
{
  "id": "P-9M531076R8973332TTBDIH3I",
  "state": "ACTIVE",
  "name": "Basic (EUR)",
  "description": "Basic (EUR)",
  "type": "INFINITE",
  "payment_definitions": [
    {
      "id": "PD-4GA39677WB8337901TBDIH3I",
      "name": "Basic (EUR)",
      "type": "REGULAR",
      "frequency": "Month",
      "amount": {
        "currency": "EUR",
        "value": "7.99"
      },
      "cycles": "0",
      "charge_models": [],
      "frequency_interval": "1"
    }
  ],
  "merchant_preferences": {
    "setup_fee": {
      "currency": "EUR",
      "value": "7.99"
    },
    "max_fail_attempts": "1",
    "return_url": "https://api.***.com/webhooks/paypal/process-agreement",
    "cancel_url": "https://api.***.com/webhooks/paypal/cancel-agreement",
    "auto_bill_amount": "YES",
    "initial_fail_amount_action": "CANCEL"
  },
  "create_time": "2017-07-31T10:52:24.429Z",
  "update_time": "2017-07-31T10:52:26.355Z",
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/billing-plans/P-9M531076R8973332TTBDIH3I",
      "rel": "self",
      "method": "GET"
    }
  ],
  "httpStatusCode": 200
}
```
When I subscribe to it, merchant get's payment twice, buyer is withdrawn twice too, I receive two webhooks (the second is in several minutes after the first). Seems like something is wrong with my plan or it's a bug and `setup_fee` is being charged twice. 
Can anyone suggest what is wrong? 
As I understand, I should get only one immediate payment, which is `setup_fee`. The next payment should be in a month, as it's the billing frequency defined in plan.

**Comment by pp-randy** [comment]
Was your start_date set for the next month?

**Comment by poohitan** [comment]
@pp-randy If you mean Billing Agreement's `start_date`, then I'm always setting it to current date + one minute. Is it wrong? 
Is `start_date` the date when the first payment should be proceed, or is it the date when billing flow begins and the first payment will be proceeded `frequency` * `frequency_interval` after the `start_date`?

**Comment by pp-randy** [comment]
@poohitan so `start_date` is when you want the scheduled payments to start; this explains the two payments you are seeing. Add a month to the date for your `start_date`. 

The frequency and interval should begin at the `start_date` you provide if that answers your question.

**Comment by poohitan** [comment]
Ok, got it, thank you @pp-randy.

Can you please also explain me what is the difference between next two flows:
1) Billing plan has a `setup_fee`, `start_date` is set to one month from now. 
2) Billing plan has no `setup_fee`, `start_date` is set to one minute from now.
In both cases user will be charged right after subscribing to agreement, and then every month. Is there any pros/cons of implementing my flow in any of these two ways?

**Comment by xiaoleih41** [comment]
@poohitan There's really no difference in your situation. Some merchant may like to set a certain date for all subscriptions. `setup_fee` will help them charge the first incomplete month fee before the full month subscription kicks in.

**Comment by poohitan** [comment]
Thank you guys :)

**Comment by pp-randy** [comment]
No problem. Let us know if you have further questions.
