### ISSUE TITLE
promisify create function not working

### ISSUE THREAD

**Issue by heinhoang** [paypal/PayPal-node-SDK#290]
* SDK/Library version: "paypal-rest-sdk": "^1.7.1",
* Environment: Sandbox
* `PayPal-Debug-ID` values: "{\"error\":{}}"
* Language, language version, and OS: Wins10

### Issue description
```
const helper = () => {
    //...
    // this's not working
    const createAsync = Promise.promisify(paypal.payment.create);
    return createAsync(paymentOpts, configs);
}
```
Using like this:
```
createPaypalPayment(paypalOpts, configs)
        .then(payment => res.status(HTTPStatus.ACCEPTED).json(JSON.stringify({ message: 'Your payment is accepted', payment })))
        .catch(e => res.status(HTTPStatus.BAD_REQUEST).json(JSON.stringify({ error: e })));
```
it ouputs
```
"{\"error\":{}}"
```
### Note
If in helper function, I use `paypal.payment.create` insteads of promise, it works well
```
   // this works
    paypal.payment.create(paymentOpts, configs, (err, res) => {
         if (err) { console.log(JSON.stringify(err)); } else { console.log(JSON.stringify(res)); }
     });
```

**Comment by pp-randy** [comment]
Have you tried to return a Promise?  Then use reject and resolve? 
http://bluebirdjs.com/docs/api/new-promise.html

```
function createPaypalPayment(paypalOpts, configs) {
	return new Promise(function (resolve, reject) {
		paypal.payment.create(paymentOpts, configs, (err, res) => {
			if (err) {
				reject(err);
			} else {
				resolve(res);
			}
		});
	});
}
```

I will see if I can dig a bit deeper and see if I can find an error in the Promisify functionality.

**Comment by heinhoang** [comment]
yes, I use Promise like that, it works. But `Promise.promisify` not working.

**Comment by pp-randy** [comment]
The problem is due to the `this` usage in the [generated functions](https://github.com/paypal/PayPal-node-SDK/blob/master/lib/generate.js#L26-L28).  The `this` has changed after the promisify.  I'm not advising this over the above suggestion but you can bind it back to `paypal.payment`  as possible workaround `Promise.promisify(paypal.payment.create).bind(paypal.payment); `.

**Comment by pp-randy** [comment]
You could add a new function to paypal.payment as well
```
paypal.payment.createAsPromised = Promise.promisify(paypal.payment.create);
paypal.payment.createAsPromised (create_payment_json).then(console.log).catch(console.error);
```

**Comment by heinhoang** [comment]
thanks @pp-randy, I understand now.
