### ISSUE TITLE
paypal.payment.create no callback?

### ISSUE THREAD

**Issue by rwmia** [paypal/PayPal-node-SDK#292]
Not receiving any response running the payment.create function. However, the sale is successful in my dashboard. Seems that everything works, except the actual call never receives a response. Times out even at 15 seconds.

Any idea why function(error, payment) never returns a callback?

```
var payment_data = {
    "intent": "sale",
    "payer": {
        "payment_method": "credit_card",
        "funding_instruments": [
            {
                "payment_card": {
                    "type": "visa",
                    "number": "4111111111111111",
                    "expire_month": "12",
                    "expire_year": "2020",
                    "cvv2": "999",
                    "first_name": "Redact",
                    "last_name": "Redact",
                    "billing_country": "US",
                    "billing_address": {
                        "line1": "Redact",
                        "city": "Redact",
                        "state": "FL",
                        "postal_code": "Redact",
                        "country_code": "US"
                    }
                }
            }
        ]
    },
    "transactions": [
        {
            "amount": {
                "total": "134.63",
                "currency": "USD"
            },
            "description": "My description"
        }
    ]
}
```

```
paypal.payment.create(payment_data, function(error, payment){
            console.log('anything?');
              if(error){
                console.log(JSON.stringify(error));
              } else {
                console.log(JSON.stringify(payment));
              }
 });
```

Thanks in advance.

**Comment by pp-randy** [comment]
I will look into this.  If you are just beginning development I would not advise using this SDK to process credit cards and instead see if our Braintree offerings fit your needs.  Braintree offers a Node.js SDK as well https://developers.braintreepayments.com/guides/credit-cards/server-side/node.

**Comment by xiaoleih41** [comment]
@rwmia Just like what Randy has suggested that you should consider to use PayPal Braintree product for credit card processing integration instead. The credit card you were using "4111111111111111" in this REST integration can cause error too. It is suggested to use a randomly generated card number instead. However as PayPal is  moving all future credit card processing related development to Braintree, please follow the link provided above and switch your integration accordingly.
