### ISSUE TITLE
Internal service error while creating payouts using Node.js SDK

### ISSUE THREAD

**Issue by Mustehssun** [paypal/PayPal-node-SDK#297]
* SDK/Library version: Node.js SDK
* Environment: Sandbox
* `PayPal-Debug-ID` values: d6e93055e9523
* Language, language version, and OS: Node.js, 7.10, Windows

Duplicate issue: https://github.com/paypal/PayPal-REST-API-issues/issues/130

I got an internal server error on creating a payout. It was working correctly yesterday. Following is the json I'm sending in request:

{
"sender_batch_header": {
"sender_batch_id": *****,
"email_subject": "You have a payout"
},
"items": [
{
"recipient_type": "EMAIL",
"amount": {
"value": *****,
"currency": "USD"
},
"receiver": **********,
"note": "Thank you.",
"sender_item_id": *********
}
]
}

sync_mode is set to "false".
Following is the response from the API:

{
"response": {
"name": "INTERNAL_ERROR",
"message": "An internal service error has occurred.",
"debug_id": "d6e93055e9523",
"information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
"httpStatusCode": 500
},
"response_stringified": "{"name":"INTERNAL_ERROR","message":"An internal service error has occurred.","debug_id":"d6e93055e9523","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors\",\"httpStatusCode\":500}",
"httpStatusCode": 500
}

Payments creation and execution is currently working but I'm only having problems in the payouts API. Kindly consider this issue.
Thanks

**Comment by chris-trotter** [comment]
This is a known unresolved issue with the REST APi. [#915](See https://github.com/paypal/PayPal-PHP-SDK/issues/915)

**Comment by pp-randy** [comment]
Closing this as a duplicate, I will investigate https://github.com/paypal/PayPal-REST-API-issues/issues/130
