### ISSUE TITLE
Where install this module?

### ISSUE THREAD

**Issue by booradleys** [paypal/PayPal-node-SDK#298]
Hi there,
I'd like to know where to install this module?
Server side ? ie into ExpressJs node_modules
Client side ? ie into Ionic/Angular node_modules

**Comment by xiaoleih41** [comment]
It will be on the server side.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.

**Comment by booradleys** [comment]
Thank you @xiaoleih41 !
