### ISSUE TITLE
INTERNAL_SERVICE_ERROR when creating a payment

### ISSUE THREAD

**Issue by joseaomedes** [paypal/PayPal-node-SDK#299]
### General information

* SDK/Library version: 1.7.1
* Environment: SandBox
* `PayPal-Debug-ID` values: 9c74a935bba1e, 84a126782702d
* Language, language version, and OS: NodeJs v0.12.15 on Ubuntu 14.02

### Issue description

When trying to issue a payment on a registered credit card, we always get "Internal Server Error".
The issue is 100% reproduceable. 

Find below the response we get from Paypal API:

{"response":{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"84a126782702d","httpStatusCode":500},"httpStatusCode":500}

**Comment by xiaoleih41** [comment]
Are you using the credit card come with the sample code? Please make sure to use a card number newly generated by card generator. Please refer to https://github.com/paypal/PayPal-REST-API-issues/issues/22

**Comment by joseaomedes** [comment]
Hello,

I am using the credit cards listed by PayPal as test credit cards.

https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm <https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm>

I will use the CC generator and re-test.

Many thanks,

Jose

**Comment by xiaoleih41** [comment]
These are the cards for PayPal manager transactions. For REST API, you will have to use newly generated card. Please resubmit if it doesn't solve the issue along with a **debugId**, we will look into it for you.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.

**Comment by xiaoleih41** [comment]
did you try a newly generated card by a card generator?
