### ISSUE TITLE
NON_HOLDING_CURRENCY

### ISSUE THREAD

**Issue by tranchuong** [paypal/PayPal-node-SDK#301]
### General information

* SDK/Library version: 1.7.1
* Environment:  Sandbox
* `PayPal-Debug-ID: 987b46bdd2b59
* Language, language version, and OS: node 6.9.1 on macOS 10.12.6

### Issue description

I have a debug log

> '{"name":"NON_HOLDING_CURRENCY","message":"An internal service error has occurred.","debug_id":"987b46bdd2b59","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}'

I can't find error code in [Error messages](https://developer.paypal.com/docs/api/payments.payouts-batch/#errors)
Can you help me?

**Comment by xiaoleih41** [comment]
It looks like you are trying to make a payout in **SGD** while you don't have any balance in this currency.

**Comment by tranchuong** [comment]
@xiaoleih41 I see. Thanks you

I have a question, can I setup API for user A payout to user B? In case of user A & B using the personal account Paypal

**Comment by xiaoleih41** [comment]
Payout has to be from your account to another PayPal account. You cannot facilitate 3rd party payout.

**Comment by tranchuong** [comment]
Thanks you
