### ISSUE TITLE
Inmediate payment

### ISSUE THREAD

**Issue by yamifr07** [paypal/PayPal-node-SDK#302]
Hello, I'm creating a payment for credit card payments: paypal.payment.create(data)
Response could be: 'created', 'approved' and 'failed' but I need an inmediate response with two states paid/not paid. Is there any parameter to force a binary mode?

**Comment by xiaoleih41** [comment]
You have to execute the payment to get the **sale state**. It will have multiple states but you can create your own status to categorize them into two different status.

**Comment by xiaoleih41** [comment]
Close the issue as the question has been answered.
