### ISSUE TITLE
Braintree vs PayPal Node.js SDKs

### ISSUE THREAD

**Issue by kyrylkov** [paypal/PayPal-node-SDK#305]
I would like PayPal to clarify the status of PayPal-node-SDK development, especially in the relation to https://github.com/paypal/PayPal-node-SDK/issues/234

The last release of PayPal-node-SDK was almost 10 months ago.  

Many things have happened in Node.js in that period of time including release of Node.js v8, soon to become LTS, fully embracing promises and async functions.

In the same period of time https://github.com/braintree/braintree_node was actively developed, had ~10 releases, with v2 release in Feb 2017 dropping support for legacy versions of Node.js (< 4) and adding support for promises in v2.1.0

Will PayPal-node-SDK continue to remain abandonware with no new features added?  If so, it's best to clarify this and direct people to use https://github.com/braintree/braintree_nod instead.

**Comment by xiaoleih41** [comment]
We are release new version of REST SDK soon. New version of PayPal-node-SDK should be available before the end of the year. Thank you for your patience and support.
