### ISSUE TITLE
How to test paypal.payment.execute function

### ISSUE THREAD

**Issue by toviaKan** [paypal/PayPal-node-SDK#306]

**Comment by xiaoleih41** [comment]
[Here](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/execute.js) is the SDK sample on how to execute a PayPal payment.

**Comment by toviaKan** [comment]
Thanks for your answers,

I'm sorry that I did not explain my self very well,
I'm looking for integration test, for CI-CD.
And every single version of my web I want to do real buy (not sandbox) on production from the server.

Thanks

**Comment by xiaoleih41** [comment]
All the sample codes can be used in production, if you use live credentials and set in live environment.  If it doesn't answer your questions, could you please elaborate more on what is lacking and what you want to accomplish?

**Comment by xiaoleih41** [comment]
Close this as the answer has been provided. If you need more information, please provide more clarification on the issue.
