### ISSUE TITLE
Where is the Node.js library for using PayPal Express Checkout?

### ISSUE THREAD

**Issue by chaddjohnson** [paypal/PayPal-node-SDK#307]
I'm sorry to post this here, but I think the Node.js community deserves some clarity on this topic.

I'm looking at [PayPal's documentation](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/) on Reference Transactions, and at the top of the page it says:

> Important: This integration method is Deprecated as of January 1, 2017. For new integrations, see the PayPal Express Checkout Integration Guide.

But when I go to [the new page](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/), there's nothing there about how to do reference transactions with PayPal Express Checkout. It really seems PayPal has dropped the ball here. And even worse, it seems PayPal provides no Node.js libraries capable of performing reference transactions using PayPal Express Checkout.

I see the [Node SDK](https://github.com/paypal/PayPal-node-SDK) as well as the [PayPal Checkout Demo](https://github.com/paypal/paypal-checkout-demo) and [server code](https://github.com/paypal/paypal-checkout-demo/blob/master/src/app/server/lib/paypal.js), but it's not clear whether these are using the non-deprecated PayPal Express Checkout API. Further, it's not possible for me to use this Node SDK anymore because when I sign up for a developer sandbox account, I am presented with a `username`, `password`, and `signature`, whereas this library requires a `client_id` and a `client_secret`.

I did find the [paypal-ec2 package](https://www.npmjs.com/package/paypal-ec2) as well as [this nice demo](https://github.com/tayutaedomo/node-paypal-reference-transaction) that uses that library, but neither of these are provided by PayPal itself.

Here is [some more information](https://stackoverflow.com/questions/46161864/how-can-i-obtain-a-token-to-charge-authorized-paypal-accounts-as-needed) related to what I'm looking for.

Please provide clarity on what to do as this library seems unusable.

**Comment by chaddjohnson** [comment]
Nevermind. I figured out I can set up an application with PayPal and obtain credentials by visiting https://developer.paypal.com/developer/applications/, and then I can use this SDK.

The notice at the top of the [documentation page](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/) is super confusing, and I think PayPal needs to clarify things. That notification makes me think that the API that this SDK uses has been deprecated and that I have to use some new API (PayPal Express Checkout) that has no Node client.

Furthermore, it's also confusing when I create a sandbox account, and I'm given `username`, `password`, and `signature`, and I have dig around a lot and eventually figure out that I have to register an app within my sandbox account in order to obtain a `clientId` and a `clientSecret`.

For a multi-billion dollar company, this pretty bad.

**Comment by chaddjohnson** [comment]
Could one of you guys comment on this? I'm still really confused by the deprecation warning at https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/ and would appreciate clarification.

**Comment by chaddjohnson** [comment]
@avidas @prannamalai @bluk @siddick @tkanta would love some feedback.

**Comment by xiaoleih41** [comment]
@chaddjohnson The guide is for our classic SOAP/NVP API while REST SDK doesn't have reference transaction related feature built in at this time.  PayPal will update all SDKs in Q4.

**Comment by chaddjohnson** [comment]
Okay, thanks for the clarity! I will continue using the paypal-ec2 package for now.
