### ISSUE TITLE
Info request: how webhook retry policies work?

### ISSUE THREAD

**Issue by nvivo** [paypal/PayPal-node-SDK#308]
Is there any detailed information somewhere about the retry policies of paypal webhooks? I'd like to know what happens when a webhook fail, to better plan downtimes, and how much time a customer will have to wait if we cannot receive the event at that time. [Other than this comment](https://github.com/paypal/PayPal-node-SDK/issues/125#issuecomment-175074282) I cannot find any information on this.

I'd like to know:

1. What intervals (even if approximate) will paypal retry sending the event
2. For how long will paypal retry the events before giving up

Any information or link is appreciated. Thanks.

**Comment by xiaoleih41** [comment]
We don't have the exact time frame but the first try should be within a few minutes and there will be several retires within a day . You can also integrate PayPal [IPN](https://developer.paypal.com/docs/classic/products/instant-payment-notification/) to provide double assurance.

**Comment by xiaoleih41** [comment]
Close this case as the answer has been provided

**Comment by nvivo** [comment]
Thanks!
