### ISSUE TITLE
Does it supports React Native ?

### ISSUE THREAD

**Issue by gowthamkumar7** [paypal/PayPal-node-SDK#310]
* SDK/Library version: 1.0.1
* Environment: Sandbox or Production
* Language, language version, and OS: React Native 0.47

### Issue description
Does this support react native , if not please specify how to achieve it.

**Comment by bluk** [comment]
This SDK does not support React Native and is only for server side integrations. Leaving your client secret in a distributed application would allow someone to perform actions as your seller account (like refund any payment).

For the client side, you should probably look into hosting a payment page to use [PayPal Express Checkout with the REST API and JavaScript](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/client-side-REST-integration/) or the [Braintree SDK with a JavaScript client](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/client-side/javascript/v3/). You can find more details on the Express Checkout pages on the PayPal developer site.
