### ISSUE TITLE
Are IPN verification query strings always delivered in the same order?

### ISSUE THREAD

**Issue by dcorns** [paypal/PayPal-node-SDK#313]
We are attempting to use ipn for payment verification. The problem is that our end point that receives the PayPal notification is an AWS API Gateway resource which always converts the query strings to key/value pairs with no respect for order. The IPN documentation states that this initial request must be sent back to PayPal with the same values(no problem) and the same 'exact' order. Given this problem, The only way I can think to solve it is by reconstructing the query strings before returning to PayPal. This can not work unless the order parameters (when present) when sent from IPN is always the same. If you know of another way to solve this please provide a solution or tell me, Does the IPN notification service always send query strings parameters in the same order? And honestly, I am perplexed as to why you require them to be in the same exact order when sent back anyway. Thank for your help.

**Comment by xiaoleih41** [comment]
As long as you have all the value there and same. It should be ok. You don't have to have them in the exact order.  Order doesn't matter.

**Comment by xiaoleih41** [comment]
Close as the answer has been given
