### ISSUE TITLE
error when making a get by paymentId

### ISSUE THREAD

**Issue by Erick-Zanetti** [paypal/PayPal-node-SDK#316]
**General information**

- paypal-rest-sdk version: 1.7.1
- Environment: Sandbox
- PayPal-Debug-ID values: dfc22c75adcc0, dfc22c75adcc0
- Language: Node-js

**Descripition** 
My code is like this:
`exports.cosultaTransacao = function() {

    paypal.configure({
        'mode': 'sandbox', //sandbox or live
        'client_id': '',
        'client_secret': ''
    });

    var tid = "PAY-1GV129502F674254DLH4G2IY";
    
    paypal.payment.get(tid, function (error, payment) {
        if (payment) {
            console.log(error, payment);
        } else {
            console.log(error, payment);
        }
    });
  }`

All other routines work, but this returns me the following error

`{ Error: Response Status : 404
    at IncomingMessage.<anonymous> (d:\www\limber-ecommerce\server\node_modules\paypal-rest-sdk\lib\client.js:136:23)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  response: 
   { name: 'INVALID_RESOURCE_ID',
     message: 'The requested resource ID was not found',
     information_link: 'https://developer.paypal.com/docs/api/payments/#errors',
     debug_id: 'dfc22c75adcc0',
     httpStatusCode: 404 },
  response_stringified: '{"name":"INVALID_RESOURCE_ID","message":"The requested resource ID was not found","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"dfc22c75adcc0","httpStatusCode":404}',
  httpStatusCode: 404 }`

I could not identify the source of the error, since it is the same as the documentation

**Comment by xiaoleih41** [comment]
It's a live account transaction but you set it as sandbox environment. Can you check if this could be the issue?

**Comment by Erick-Zanetti** [comment]
Really this mistake the problem, was so involved in it yesterday that did not realize, sorry for the inconvenience.
