### ISSUE TITLE
Is it possible to create an approved payment using paypal rest API?

### ISSUE THREAD

**Issue by tiagodavi** [paypal/PayPal-node-SDK#317]
Hi Guys. My question is simple. I would like to create an approved payment in order to test my business logic. Documentation says I have to create a Payment, then the customer has to approve it before I can execute it and this is my problem. I would like to execute it without having to approve it by the customer.

Is it possible?

**Comment by xiaoleih41** [comment]
Are you trying to payout to some? If you don't need the recipient to approve it, it will be payout API. Yes you can test in sandbox if that's what you were looking for. For live environment, please make sure apply and get approved at developer.paypal.com inside of the app you have created as it's an advanced feature.

**Comment by tiagodavi** [comment]
Hi @xiaoleih41 Actually I am trying to create a payment with status == approved without having to log in with the customer to approve it. 

/v1/payments/payment/{payment_id}/execute
Executes a PayPal payment **that the customer has approved**. You can optionally update one or more transactions when you execute the payment.

I would like to execute the api above without having customer's approval for testing purposes

**Comment by pp-randy** [comment]
@tiagodavi that is currently not possible, for a PayPal payment, the buyer needs to approve the payment.  If you want to test your application code, I suggest you mock the api request and responses needed.

**Comment by tiagodavi** [comment]
I see. Thanks.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.

**Comment by dan003400** [comment]
How is this not possible? Anyone using the PayPal REST API and wants to write full integration tests now can not do so.

Add a flag to create order that overrides the check for approved by customer.

This should not be closed, there was no solution given.
