### ISSUE TITLE
Create payment without requirement access token?

### ISSUE THREAD

**Issue by ntlzz93** [paypal/PayPal-node-SDK#319]
### General information

* SDK/Library version: 1.7.1
* Environment: sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Nodejs 8 on Macos

### Issue description
I realize that this SDK can create payment without require access token. Is this normal way to create payment?

**Comment by pp-randy** [comment]
You need the access token or you will get 401 unauthorized from the API. 

SDK handles the access token creation for you if you configure the PayPal library, like done in the sample [samples/configure.js](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/configure.js.)

**Comment by xiaoleih41** [comment]
Close as the answer has been given.

**Comment by acomito** [comment]
@pp-randy link is dead
