### ISSUE TITLE
invalid_client 401 after upgrading to v1.8.0

### ISSUE THREAD

**Issue by dr-dimitru** [paypal/PayPal-node-SDK#320]
### General information

* SDK/Library version: 1.8.0
* Environment: live (production)
* Language, language version, and OS: nodejs@8.8.1, MacOS@10.13.1 and Debian@8.9

### Issue description

Needs to be mentioned everything works fine with `sandbox` mode, and sandbox credentials. First I thought my `live` secret (*token*) was somehow broke/expired, I've generated a new one and end up with same result.

Error log:
```
{ Error: Response Status : 401
  at IncomingMessage.<anonymous> (/Users/user/proj/node_modules/paypal-rest-sdk/lib/client.js:130:23)
  at emitNone (events.js:110:20)
  at IncomingMessage.emit (events.js:207:7)
  at endReadableNT (_stream_readable.js:1056:12)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)
response: 
 { error: 'invalid_client',
   error_description: 'Client Authentication failed',
   httpStatusCode: 401 },
httpStatusCode: 401 }
```

Switching back to `v1.7.1` immediately solved this issue.

Minimal reproduction:
```js
import paypal from 'paypal-rest-sdk';

paypal.configure({
  mode: PP_MODE, // live
  client_id: PP_CID, // client id
  client_secret: PP_SEC // secret
});

const paypalWebprofile = {
  name: 'prof',
  presentation: {
    brand_name: 'example.com',
    logo_image: 'https://example.com/images/pp_logo.png',
    locale_code: 'US'
  },
  input_fields: {
    allow_note: false,
    no_shipping: 1,
    address_override: 1
  },
  flow_config: {
    landing_page_type: 'billing',
    user_action: 'commit'
  }
};

paypal.webProfile.list((error, webProfiles) => {
  console.info('[paypal.webProfile.list]');
  if (error) {
    console.error('[paypal.webProfile.list]', error, webProfiles);
  } else {
    if (webProfiles && webProfiles.length) {
      for (let i = webProfiles.length - 1; i >= 0; i--) {
        console.info('PayPal profile [FOUND]', webProfiles[i]);
        if (webProfiles[i].name === paypalWebprofile.name) {
          return;
        }
      }
    }

    paypal.webProfile.create(paypalWebprofile, (createError, webProfile) => {
      console.info('[paypal.webProfile.create]');
      if (createError) {
        console.error('[paypal.webProfile.create]', createError, webProfile);
      } else {
        console.info('PayPal profiles [CREATED]', webProfile.id);
      }
    });
  }
});
```

**Comment by tinovyatkin** [comment]
The same for me on Node 9. Rolling back to previous version solves the problem.

**Comment by arminschleicher** [comment]
+1 got the same issue

**Comment by haemse** [comment]
Same with me - using micropayments

**Comment by haemse** [comment]
very interesting - sandbox works on production AND localhost

live works on localhost, but not in production on the server ... very, very strange.

any suggestions for this behavior?

credentials and mode: live 100% correct

**Comment by haemse** [comment]
Anyone knows where to set the API version?

**Comment by yshing** [comment]
+1

**Comment by arminschleicher** [comment]
related: https://stackoverflow.com/questions/47627722/401-invalid-client-when-processing-paypal-payment-using-node-sdk-on-production-s/47628960#47628960

**Comment by dr-dimitru** [comment]
@haemse in your `package.json` set `paypal-rest-sdk` to `~1.7.1`:
```json
{
  "name": "my local deps",
  "scripts": {
    "start": "node"
  },
  "dependencies": {
    "paypal-rest-sdk": "~1.7.1"
  }
}
```

**Comment by bluk** [comment]
Thanks for the reports. We are investigating.

**Comment by bluk** [comment]
This should be resolved in [v1.8.1](https://github.com/paypal/PayPal-node-SDK/releases/tag/v1.8.1). If you are still running into an issue, please leave a comment. Apologies for the error.

**Comment by dr-dimitru** [comment]
@bluk tests successfully passed. Hopefully we will be good after deployment

**Comment by bf** [comment]
Is it working again for your @dr-dimitru ?

**Comment by peterjuras** [comment]
v1.8.1 works for us again.

Please don't increase minor versions when doing something like this and please thoroughly test this. We lost revenue and also upset our customers! This is a no-go!

**Comment by dr-dimitru** [comment]
@peterjuras totally agree with you.
We have been saved by our beta stage and automated testing.

@bf yes, `v1.8.1` is good to go.
