### ISSUE TITLE
Payment without requesting User Info

### ISSUE THREAD

**Issue by Pfeiffer86** [paypal/PayPal-node-SDK#324]
Hi,
 
I am using REST-API to redirect user to Paypal platform and pay for services on a website.
`var paypal_api = require("paypal-rest-sdk");`

Is there a way to make the following fields optional (when paying by card)
- Last Name
- First Name
- Address
- Email 
- Phone number

I would like my user to pay without filling those fields.
I am ready to rebuild completely my code in order to succeed.
 
Thank you

**Comment by xiaoleih41** [comment]
We can't make it optional as that's required information for PayPal to process a guest credit card checkout  without logging into their PayPal account.

**Comment by Pfeiffer86** [comment]
Thank you for your answer xiaoleih41,
I close the issue.
