### ISSUE TITLE
Manually configured host gets overwritten by default values

### ISSUE THREAD

**Issue by cacheonly** [paypal/PayPal-node-SDK#326]
### General information

* SDK/Library version: 1.8.1
* Environment: n/a
* `PayPal-Debug-ID` values: n/a
* Language, language version, and OS: n/a

### Issue description

As a part of our testing suite at my company, we have set up a fake PayPal REST API server that stubs out responses for certain requests. However even though I have configured our node PayPal library with the following options

```
let paypal = require('paypal-rest-sdk')
paypal.configure({
      client_id: '<CLIENT_ID>',
      client_secret: '<CLIENT_SECRET>',
      schema: 'http',
      host: 'localhost',
      port: '1234',
})
```

the `host` variable gets overwritten here (https://github.com/paypal/PayPal-node-SDK/blob/master/lib/api.js#L62) by a default value. Is this by design or a bug? I can get a PR ready that reprioritizes the settings to respect options passed by the user first.

**Comment by pp-randy** [comment]
I see some recent changes around the code which were added and reverted recently.  

Reverse Commit: https://github.com/paypal/PayPal-node-SDK/commit/bf942ea11248abdb033c1e5cb83317849250dc8a

Change Commit: https://github.com/paypal/PayPal-node-SDK/commit/fa652aa6962150eb12b3a456c5e92fe57d812a23

A related thread: https://github.com/paypal/PayPal-node-SDK/issues/320.  

It looks like you should be able up modify the host in the V2 beta being worked on https://github.com/paypal/PayPal-node-SDK/blob/2.0-beta/lib/core/paypal_environment.js#L16

**Comment by cacheonly** [comment]
Thanks for the response. Is 2.0 production ready?

**Comment by pp-randy** [comment]
It is not production ready.  As a workaround for now, you could mock the `getDefaultApiEndpoint` depending on your test library.


This is an example using Jest, but other libraries might be similar. 

```
const paypalutil = require('paypal-rest-sdk/lib/utils');

describe("test payment", () => {

    it("should test payment", () => {
        paypal.configure({
            'mode': 'sandbox', //sandbox or live
            'client_id': 'EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM',
            'client_secret': 'EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM',
            'port': '1234'
        });

        // create spy
        const spy = jest.spyOn(paypalutil, 'getDefaultApiEndpoint').mockImplementation((host) => {
            return 'localhost';
        });
         
        ... Test some stuff

        //restore functionality
         spy.mockRestore();
```

Which will fail  `problem with request: connect ECONNREFUSED 127.0.0.1:1234` for me because I don't have the server setup for mocking.  

If you are mocking everything,  you could set `paypalutil.getDefaultApiEndpoint = () => { return 'localhost'};`

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been given.
