### ISSUE TITLE
QUESTION: Are installments and commissions doable?

### ISSUE THREAD

**Issue by mrnkr** [paypal/PayPal-node-SDK#328]
Hello!

I am currently working on a marketplace like app and the particular requirements I'm being asked to comply with are: 
1. Send payments to the merchants at once. (This I was able to accomplish)
2. Take a commission from each payment.
3. Allow users to pay in installments.

The second two I wasn't able to accomplish... 
I have read the docs for the REST API and found that it is possible to charge a partner fee like so:
```json
"partner_fee_details": {
    "receiver": {
      "email": "partner@example.com"
    },
    "amount": {
      "value": "0.01",
      "currency": "USD"
    }
}
```
Using the Payments API with the Node SDK does not allow for this, at least not to my knowledge... Is there any workaround?

As for the installments, I was able to generate both a billing plan and agreement, but was not able to make use of it in my orders, which I saw was possible by means of the following code:
```json
"payer": {
      "payment_method": "paypal",
      "funding_instruments": [
        {
          "billing": {
            "billing_agreement_id": "insert_billing_agreement_id"
          }
        }
      ]
    }
```
Again, this code is not usable with the SDK as far as I'm concerned...

Any clues or help you could give me would be highly appreciated!
Thanks in advance!

**Comment by xiaoleih41** [comment]
Are you trying to set up a billing agreement between a buyer and a merchant of the marketplace? That's one advanced feature that not available for general public. Please contact the customer service number on your account and request to talk to sales team. The sale rep should be able to help you determine if you are qualified for the feature that you need for your project. It will be a different product that is not available for this SDK.

**Comment by mrnkr** [comment]
I understand, thank you!

**Comment by xiaoleih41** [comment]
I am closing this issue as it has been addressed.
