### ISSUE TITLE
Question: How long will the 1.x version be supported after release of 2.0?

### ISSUE THREAD

**Issue by walling** [paypal/PayPal-node-SDK#329]
Hi, I know this might be a bit early, since the 2.0 version is not released yet. In my company we have been looking at the 2.0-beta branch and for now we would like to stay on the 1.x branch. How long can we expect it to be supported/maintained?

I tried reading the [migration guide](https://github.com/paypal/PayPal-node-SDK/blob/2.0-beta/docs/Migrating.md) and [FAQ](https://github.com/paypal/PayPal-node-SDK/blob/2.0-beta/docs/FAQ.md) as well as the [2.0-beta readme](https://github.com/paypal/PayPal-node-SDK/tree/2.0-beta#paypal-sdk-200-beta), however I didn't find an answer to my question. That's why I'm asking here.

**Comment by pp-randy** [comment]
The existing version will have maintenance support, but will not be updated with new features or APIs.  If you are using features in the 1.x version of the SDK I would suggest integrating 1.x, since the 2.0 version is subject to change.

**Comment by walling** [comment]
Ok, thanks for clarifying.
