### ISSUE TITLE
Cancel Example wrong method call

### ISSUE THREAD

**Issue by sameerjain** [paypal/PayPal-node-SDK#330]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Can anyone correct following example 

https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/cancel.js

It should call billingAgreement.get after successful cancel. Example suggests to call billingPlan.get which leads to wrong results.

Thanks

**Comment by xiaoleih41** [comment]
I have noted this issue and will look into this. Thank you for pointing this out.
