### ISSUE TITLE
Transaction Details

### ISSUE THREAD

**Issue by divyashobana19** [paypal/PayPal-node-SDK#331]
I am getting the transaction in Sandbox API Call History.How i will get the transaction details in summary of paypal account.

![image](https://user-images.githubusercontent.com/25704038/34715703-8316a642-f553-11e7-919f-21cc20b218d1.png)

**Comment by xiaoleih41** [comment]
If you log on to www.sandbox.paypal.com.  You can get the transaction history in the **Activity** section.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given
