### ISSUE TITLE
Execute payment malformed request

### ISSUE THREAD

**Issue by safinn** [paypal/PayPal-node-SDK#332]
### General information

* SDK/Library version: ^1.8.1
* Environment: sandbox
* `PayPal-Debug-ID` values: 59972149a711e

### Issue description

Im creating the payment on the client side as seen below:

```
payment = (data, actions) => {
    return actions.payment.create({
      transactions: [{
        amount: {
            total: this.props.price,
            currency: 'EUR'
        }
      }]
    });
  }
```

Once my `onAuthorize` function fires I make a request on my server using the paymentId and payerId created on the client side. My server side code looks like this:

```
paypal.payment.execute(paymentId, payerId, (err, payment) => {
    if (err) {
      // goes in here
    }
});
```

The error: 
```
{ name: 'MALFORMED_REQUEST',
     message: 'Incoming JSON request does not map to API request',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST',
     debug_id: '1bca345641174',
     httpStatusCode: 400 },
  httpStatusCode: 400 }
```

**Comment by safinn** [comment]
Sorted. The `payerId` must be in an object like this:
```
{ payer_id: payerId }
```

**Comment by pp-randy** [comment]
Thank you for providing your solution.
