### ISSUE TITLE
using paypal in india

### ISSUE THREAD

**Issue by toviaKan** [paypal/PayPal-node-SDK#333]
I open my web to buy in India via PayPal
but when I try to buy I got this message:
```
We aren't able to process your payment using your PayPal account at this time. Please go back to the merchant and try using a different payment method.
```
Can you explain to me how to fix it?

**Comment by xiaoleih41** [comment]
This looks more like an account specific issue. Please contact customer service number listed on your account.

**Comment by pp-randy** [comment]
Since this is not a SDK issue closing in favor of the comment provided by @xiaoleih41.
