### ISSUE TITLE
Paypal configure method returns undefined

### ISSUE THREAD

**Issue by vforv** [paypal/PayPal-node-SDK#334]
Version:

"paypal-rest-sdk": "^1.8.1"

### Issue description

```
const Paypal = require('paypal-rest-sdk');

console.log(Paypal)
console.log(Paypal.configure({
            'mode': 'sandbox', //sandbox or live
            'client_id': 'MYID',
            'client_secret': 'MYSECRET'
        }));
```

I changed MYID and MYSECRET part...

so 1st console log showing pay pal object but after configure it return undefined.

**Comment by xiaoleih41** [comment]
Did you get the access token created? What's the error message and do you have a debugId to share with us?

**Comment by Thesephi** [comment]
I think that's how it's supposed to work. You only ever need the `Paypal` object (which was `require`d from `paypal-rest-sdk`). The `configure` method simply sets things up for you, it doesn't have to return any object. You can now start using the API by invoking i.e. `Paypal.payment.create(...)` and so on.

**Comment by vforv** [comment]
@Thesephi yo are correct. I thought it should return something.
