### ISSUE TITLE
I can't update recurring billing plan amount

### ISSUE THREAD

**Issue by kaalees** [paypal/PayPal-node-SDK#335]
### General information
I can't update recurring billing plan amount using this SDK

* SDK/Library version: 1.8.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 3eb95618ad9e5
* Language, language version, and OS: NodeJS 7.10 on MAC

### Issue description
I received the response below
{"response":{"name":"BUSINESS_VALIDATION_ERROR","details":[{"field":"validation_error","issue":"Invalid Path provided."}],"message":"Validation Error.","information_link":"https://developer.paypal.com/docs/api/payments.billing-plans#errors","debug_id":"3eb95618ad9e5","httpStatusCode":400},"httpStatusCode":400}

**Comment by pp-randy** [comment]
Please see https://github.com/paypal/PayPal-REST-API-issues/issues/25
