### ISSUE TITLE
Negative testing

### ISSUE THREAD

**Issue by limitsapp** [paypal/PayPal-node-SDK#336]
### Issue description

Having trouble finding the documentation on how to negative test using the node.js rest api

**Comment by xiaoleih41** [comment]
Please look into the guidance [here] on how to do negative testing on REST API.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.

**Comment by dcworldwide** [comment]
Does this lib support negative testing though? How to set it up with this lib? Specifically, HTTP request negative testing...
