### ISSUE TITLE
Need help in integrating subscription. 

### ISSUE THREAD

**Issue by keerthikumarsr95** [paypal/PayPal-node-SDK#337]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I have set up a PayPal subscription flow with billing plan and billing agreement,

after creating billing agreement a redirect URL is returned from API call, where the user is redirected. 
Here PayPal asks for the user to pay either with logging into existing account or by creating a new account. 

my doubt is here how can I get guest checkout to pay for the subscription.

**Comment by xiaoleih41** [comment]
You will have to have a PayPal account to sign up a billing agreement. As it's not one time payment, guest checkout won't work.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.

**Comment by keerthikumarsr95** [comment]
Thanks for the information. is there any other way where we can implement subscription with guest checkout??

**Comment by xiaoleih41** [comment]
Not for guest checkout, You will have to be approved for direct credit card processing for subscription type of billing.  You can look into Braintree SDK  which vault feature supports both credit card and PayPal.
