### ISSUE TITLE
Recurring payments using Billing Agreement ID

### ISSUE THREAD

**Issue by mihirlibran** [paypal/PayPal-node-SDK#338]
### General information

* SDK/Library version: 1.8.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: N/A

### Issue description
Hello,
I am trying to implement charging a customer using his/her billing agreement id. I do not need to go through the flow of creating a sale, getting approval from the customer and then charging the customer. I already have the billing agreement id with me and I just want to use that and charge the customer.

I am aware this can be done through your SOAP integration, but I was wondering if its possible to do the same using REST? I am using the Node SDK but I am clueless as to how to do it using the SDK as there seems to be no documentation on the same.

Thanks in advance for your help. Let me know if you need any more info.

**Comment by xiaoleih41** [comment]
It's not supported at this time on REST. Please consider to use Braintree SDK which vault feature can support this type of payment behavior for both credit card and paypal.

**Comment by mihirlibran** [comment]
Got it. Thank you for the response!
