### ISSUE TITLE
GET: /v1/payments/billing-plans always returns "204 No Content"

### ISSUE THREAD

**Issue by niklam** [paypal/PayPal-node-SDK#343]
I'm trying to fetch billing plans, but I always get `204 No Content` as response.

Query:
```
https://api.sandbox.paypal.com/v1/payments/billing-plans?page_size=3&status=ACTIVE&&page=0&total_required=yes
```

Paypal-debug-id: `533c91c4e1a1e`

I've tried with different settings (different status, page_size, page, etc) and the result is always the same.

I do not know if I can fetch data for single billing plan as I do not know the ids.

How should I proceed to get the list of billing plans?

**Comment by xiaoleih41** [comment]
I cannot reproduce the error. How many billing plans have you created and activated? Is it possible that you have only created a plan but yet to activate it?

**Comment by niklam** [comment]
There are (around) 8. As mentioned. I've tried setting status to different values so I should get even in-active items I suppose. If I try to set status to invalid value I get error, but none of the valid values return results.

**Comment by xiaoleih41** [comment]
I cannot reproduce the error. I ran the same exact code and got all mine returned.  Can you please confirm that after you had created all the billing agreement, did you patch "active status" to all of these 8 billing plans?

**Comment by niklam** [comment]
We're developing with sandbox data. There are active and inactive items.

**Comment by xiaoleih41** [comment]
Can you please create a new plan, update it with active status then try to query it again and provide me with  a new debugId.

**Comment by niklam** [comment]
We finally got result by creating recurring payment ourselves via API. It seems that we only can get the ones we've created via API, not the others.

**Comment by xiaoleih41** [comment]
Ah yes. two different product. The REST billing agreement is only created by API. The recurring payment product is a different product on a different product that REST API won't be able to retrieve.

**Comment by dzt** [comment]
Any way to still get billing plan data through subscriptions (made via PayPal buttons) in the REST API? @xiaoleih41

**Comment by SmitaHasole** [comment]
We are using Paypal REST API's (v1), created payment successfully, but now trying to update its amount (adding shipping charges with resp to address) using **https://api.sandbox.paypal.com/v1/payments/payment/payment_id"** PATCH API, it returns 204 but its not updating payment entry. 
I searched this - https://developer.paypal.com/docs/integration/paypal-plus/mexico-brazil/update-the-payment-selection-page/

> it says If the call succeeds, the response returns the HTTP 204 No Content status code. 
Then if it the call succeeds then why its not fetching updated payment entry?

**Comment by kgrosvenor** [comment]
Same issue on web api via CURL
