### ISSUE TITLE
TypeError: paypal.configure is not a function

### ISSUE THREAD

**Issue by SmelayaPanda** [paypal/PayPal-node-SDK#345]
Tell me why the following problem may occur. After installing the module paypal-rest-sdk and importing it into an existing project (with a large number of modules), when the server starts, an error is generated

paypal.configure ({
        ^
TypeError: paypal.configure is not a function;

------------------------------------
-> npm install --save paypal-rest-sdk 
-> app.js
const paypal = require('paypal-rest-sdk');
paypal.configure({
    'mode': 'sandbox', //sandbox or live
    'client_id': 'EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM',
    'client_secret': 'EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM'
});

**Comment by luanmuniz** [comment]
I had the some problem today.
They f** up here. You installed version `2.0.0-rc-1`.

`npm install paypal-rest-sdk` is installing v2.

You need to install v1 specifying the version or try to understand the mess in v2 =/

**Comment by SmelayaPanda** [comment]
Thank you very much, I changed to the first version everything worked correctly! =)
