### ISSUE TITLE
transaction amount is not sending to paypal

### ISSUE THREAD

**Issue by zaw-hlaing-bwar** [paypal/PayPal-node-SDK#347]
![image](https://user-images.githubusercontent.com/18108171/36411954-5f69c206-1646-11e8-843a-70ef127b6097.png)
I cant see the transition total amount in paypal site.
I am using paypal rest sdk v2.0
The following code is how i execute payment
```
client.execute(request).then((response) => {
        console.log(response.statusCode);
        console.log(response.result);
        var id = response.result.id;
        var links = response.result.links;
        var counter = links.length;
        while( counter -- ) {
            if ( links[counter].method == 'REDIRECT') {
                return res.redirect( links[counter].href )
            }
        }
      }).catch((error) => {
        console.error(error.statusCode);
        console.error(error.message);
      })
```
I also feel strange with that UI too.
I integrated paypal in react but it come up with a new ui

The following image is how paypal return result!
![image](https://user-images.githubusercontent.com/18108171/36412196-8eed1de2-1647-11e8-9340-467262ae6dd8.png)

**Comment by bluk** [comment]
The different UI was potentially due to a sandbox issue. Can you please try again?

**Comment by zaw-hlaing-bwar** [comment]
@bluk 
using [paypal checkout](https://github.com/paypal/paypal-checkout) in react (sandbox) but it goes everything fine.
but in node still having the old UI till now!

**Comment by xiaoleih41** [comment]
We will look into this

**Comment by zaw-hlaing-bwar** [comment]
@xiaoleih41  @bluk 
fix transition amount view by adding some more params in payment request json.
I hope you guys can help me fix the UI issue with One Touch(TM).
I also want to know how to get the payment response by PAY-ID for furthermore check up.
I saw sample on v1 and that doesnt work on v2.
Thanks for ur work guys.

**Comment by xiaoleih41** [comment]
Can you please send us a sample of request? We are trying to figure out if this is due to the transaction amount not being sent or because some issue going to the old UI.

**Comment by zaw-hlaing-bwar** [comment]
@xiaoleih41 
This is the code for creating payment.
Please check it.
And by the way, is there any update docs for v2?

`
  let payment = {
    'intent': 'authorize',
    'redirect_urls': {
      'cancel_url': 'http://localhost:8000/cancel',
      'return_url': 'http://localhost:8000/result-url'
    },
    'payer': {
      'payment_method': 'paypal'
    },
    "transactions": [{
              "amount": {
                  "total": 10,
                  "currency": "USD",
                  /*
                  adding details and item lists in transactions params let me show the amount
                  */
                  "details": {
                      "subtotal": 10,
                      "tax": "0.00",
                      "shipping": "0.00"
                  }
              },
              "description": "This is payment description.",
              /*
              adding details and item lists in transactions params let me show the amount
              */
              "item_list": {
                  "items":[
                      {
                          "quantity":"1",
                          "name":"ticket",
                          "price": 10,
                          "currency":"USD"
                      }
                  ]
              }
          }]
  };
  var request = new payments.PaymentCreateRequest();
  request.requestBody(payment);

  client.execute(request).then((response) => {
    var id = response.result.id;
    var links = response.result.links;
    var counter = links.length;
    while( counter -- ) {
        if ( links[counter].method == 'REDIRECT') {
          //check pay id and save in db
          //redirect to paypal page for user confirmation
            return res.redirect( links[counter].href )
        }
    }
  }).catch((error) => {
    console.error(error.statusCode);
    console.error(error.message);
  });
`

**Comment by ankibalyan** [comment]
@zaw-hlaing-bwar how would you execute the payment after user confirmation. I'm trying something like 

    function handleChargeResponse({ body, payment_ref }) {
      const payments = paypal.v1.payments;
      const payReq = new payments.PaymentExecuteRequest(body.paymentId);
      payReq.headers['PayPal-Request-ID'] = payment_ref;
      payReq.headers['Authorization'] = `Bearer ${body.token}`;
      const details = { payer_id: body.payerId};
      payReq.requestBody(body.paymentId, details);
      return client.execute(payReq)
        .then((chargeObject) => {
          console.log('=============== START DEBUG LOG retrieve Paypal chargeObject ===============');
          console.log(chargeObject);
          console.log('=============== END DEBUG LOG retrieve Paypal chargeObject ===============');
          return { chargeObject };
        })
        .catch((err) => {
          console.log(err);
          return { chargeObject };
        });
    }

**Comment by ankibalyan** [comment]
#350 raised an issue here

**Comment by ankibalyan** [comment]
@zaw-hlaing-bwar Can you try passing all the amount fields as string with fixed 2 decimal places. I'm using the similar pattern and its working for me.
Let me know if anything more details you want.

**Comment by zaw-hlaing-bwar** [comment]
@ankibalyan 
Thanks for your help,
Currently I am busy with another project and so I haven't tested your code,
I can fix the transaction amount problem by adding some params,
the really problem is paypal is showing up with old UI, not with the new One Touch UI.
How does your paypal UI work with?
with new One Touch(TM) UI?

**Comment by ankibalyan** [comment]
@zaw-hlaing-bwar yes, I'm getting new One Touch UI.

**Comment by xjijies** [comment]
@zaw-hlaing-bwar Are you still facing this issue?

**Comment by xjijies** [comment]
@zaw-hlaing-bwar Closing this issue. Please reopen if you are still see this instances around.
