### ISSUE TITLE
Failed to load (URL): Response for preflight is invalid (redirect)

### ISSUE THREAD

**Issue by dawlat-netlinks** [paypal/PayPal-node-SDK#348]
I want to integrate PayPal with node but when I create payment I getting the below error.
Failed to load `https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-29M57709H9663654S:` Response for preflight is invalid (redirect)
please help me what is the problem.

**Comment by xiaoleih41** [comment]
Do you have a `debugId`?  Also, which version of Node are you using? Are you using our newest (beta 2.0 version](https://github.com/paypal/PayPal-node-SDK/tree/2.0-beta)?

**Comment by dawlat-netlinks** [comment]
I have a `debugId ` ,  my node version is `v8.9.4` and also I used the new version of PayPal SDK.

Thanks for reply

**Comment by xiaoleih41** [comment]
What's the debugId?

**Comment by xiaoleih41** [comment]
Can you recreate it the error and provide the newest debugId for us to do research?

**Comment by lordvee** [comment]
Hi, I've gotten the same issue.

My debugId is Paypal-Debug-Id:201694a6b4a38. This is an OPTIONS call has the following headers:

Access-Control-Request-Headers:content-type,x-xsrf-token
Access-Control-Request-Method:GET

in accordance to https://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0

thanks

**Comment by bluk** [comment]
Are you trying to use this Node SDK in a browser? This SDK is only intended to be used on a secure server; if you use this SDK in a browser, your credentials would be available to any user when making requests.

**Comment by lordvee** [comment]
hi,
obviously not. however the redirect gets sent to a browser. The browser then tries to execute a preflight request on the URL to verify that CORS are accepted but the end point OPTIONS call does not seem to accept CORS requests, thus breaking the redirect. So in my view the issue is that the end point that i am calling (https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=RECEIVED_TOKEN) does not support CORS requests

**Comment by bluk** [comment]
How are you trying to perform the redirect?

**Comment by lordvee** [comment]
from node.js i call res.redirect(token);
i've tried changing the return code from 301, 302, 307... same result

**Comment by bluk** [comment]
Do you have an AJAX request that is calling the endpoint that is doing the redirect?

For instance, you load a page and someone clicks a button which invokes an XmlHttpRequest to an endpoint on your server. This endpoint then creates the PayPal payment and in its response does the redirect (`res.redirect(url_with_token);`). If so, you will need to instead pass back the `url_with_token` back to your AJAX request and do the redirect in the browser using JavaScript possibly.

**Comment by lordvee** [comment]
Okay, I tried that and it's working. Is this a workaround or a solution? If that's a solution, I am afraid it's completely unclear in the documentation.

Thanks for your help

**Comment by bluk** [comment]
It's a possible solution depending on how you've architected and designed your flow. When the browser gets the redirect in the AJAX request, it is trying to follow the redirect for the AJAX `XmlHttpRequest` response (not for the whole page). The redirect in that response wouldn't redirect the entire browser page/user to the new URL.

I believe this is also the cause of the original issue, so will close. If you have any other issues or a follow up, please open a new issue or leave a comment. Thanks.
