### ISSUE TITLE
Pending transactions status request with paypal express checkout

### ISSUE THREAD

**Issue by ankibalyan** [paypal/PayPal-node-SDK#351]
* SDK/Library version: 2.0.0-rc.1
* Environment: Sandbox
* Language, language version, and OS: Nodejs 8.9.4, Ubuntu 16.04

### Issue description

Trying to figure out, how can I reterive the pending transaction status from paypal. for example,
 if a user clicks on paypal express checkout button, 
then moves to paypal screen,
then he either closes the browser/app or just stays there for long,

In that case, how can I can confirm the payment status? when can I mark this transaction as failure.

**Comment by ankibalyan** [comment]
Does paypal expires the pending status after some time if payment is not fulfilled?

**Comment by xiaoleih41** [comment]
express checkout token is valid for 3 hours. You can [get Payment detail](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/get.js) to check the status of the created payment and mark it as failure.

**Comment by ankibalyan** [comment]
@xiaoleih41 Thanks, but for payment details I should `PaymentGetRequest` isn't?

**Comment by xiaoleih41** [comment]
When you create a payment, you will get a `paymentId`. You can use the `paymentId` to get the payment detail.

**Comment by ankibalyan** [comment]
Its working for me! 
I was confirming about the `PaymentGetRequest` method from 2.0.0.beta version.
