### ISSUE TITLE
Using the 2.0.0 beta in production

### ISSUE THREAD

**Issue by chamini2** [paypal/PayPal-node-SDK#354]
I know the readme of the beta says not to use it in production, but we will start developing an integration with PayPal next week and wanted to know the status of the beta, since I don't want to rewrite the whole thing really soon to upgrade.

**Comment by sdcoffey** [comment]
Hey @chamini2,

Awesome! I'm excited you're thinking about using it. At this point, the API is very unlikely to change significantly, so please go ahead and use it! If you want to be safe, I'd pin to a specific version and review breaking changes (if any) between now and the official 2.0 release. And please let us know if you find any issues.
