### ISSUE TITLE
Paypal saved Credit Card Payment return INTERNAL_SERVICE_ERROR Error

### ISSUE THREAD

**Issue by vsinghjodhpur** [paypal/PayPal-node-SDK#358]
i am using paypal vault feature to capture payment to saved credit card token but its return error with this message, i'm using paypal sandbox right now.

    { name: 'INTERNAL_SERVICE_ERROR',
     message: 'An internal service error occurred.',
     information_link: 'https://developer.paypal.com/docs/api/payments/#errors',
     debug_id: '3d9a8c9bc214b',
     httpStatusCode: 500 },

**Comment by xiaoleih41** [comment]
This feature has been deprecated. Please consider to integrate Braintree SDK instead. For detail please refer to README.MD.
