### ISSUE TITLE
Authorization error in live mode, sandbox mode works perfectly

### ISSUE THREAD

**Issue by MGTHEBOSS** [paypal/PayPal-node-SDK#359]
Hi,

We would like to thank all the contributors for the efforts they have put into paypal node sdk. It's undoubtedly an excellent sdk that makes it very convenient for developers to develop paypal rest api-based node apps. We are developing an app that uses the pauouts api. We have extensively tested the app in sandbox mode and it works as expected. We have recently started testing in live mode but we are getting authorization error. Payouts is enabled in live.

```
{ name: 'AUTHORIZATION_ERROR',
  debug_id: 'e94f6b0de2554',
  message: 'Authorization error occurred.',
  information_link: 'https://developer.paypal.com/docs/api/payments.payouts-batc
h/#errors',
  httpStatusCode: 403 }
REDACTED\REDACTED.js:55
        throw error;
        ^

Error: Response Status : 403
    at IncomingMessage.<anonymous> (REDACTED\paypal-rest-sdk\lib\client.js:130:23)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

General information: 
Sdk version: 1.8.1 
Environment: live 
Paypal debug id: e94f6b0de2554 
Language, language version, and os: node v8.9.3, windows 7 professional

We appreciate the cooperation of the community members.

**Comment by xiaoleih41** [comment]
When you do the payout API, please make sure your sender's email is in verified status.

**Comment by xiaoleih41** [comment]
Close this issue has it has been solved.
