### ISSUE TITLE
500 error with Sandbox environment

### ISSUE THREAD

**Issue by dadsquatch** [paypal/PayPal-node-SDK#361]
### General information

* SDK/Library version: 1.8.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 622b489eae543
* Language, language version, and OS: Running locally through Node 6.11.3 and Express 4.16.3 

### Issue description

Following the readme samples to try and get this working.

When I finally had my object pass all the Paypal validation steps on the object I was sending it, did I start receiving the 500 ISE. Here is the sample object I am passing in:

```
// All #### represent good values in my code

// Scoped data from front end being passed to backend 
// Credit card details are generated within the sandbox environment
$scope.sampleData = {
      intent: "sale",
      payer: {
        payment_method: "credit_card",
        funding_instruments: [
          {
            "credit_card":  { 
              number: "###############", 
              type: "visa",
              expire_month: #,
              expire_year:  ##,
              cvv2: "###",
              first_name: "##",
              last_name: "##",
              billing_address: {
                line1: "##", 
                city: "Oscoda",
                state: "MI",
                postal_code: "48750",
                country_code: "US"
              }
            }
          }
        ]
      },
      transactions: [
        {
          amount: {
            total: "1.06",
            currency: "USD",
            details: {
              subtotal: "1.00",
              tax: "0.06",
              shipping: "0.00"
            }
          },
          invoice_number: "123456"
        }
      ]
    }

// Backend route for passing data to Paypal API

const paypal = require('paypal-rest-sdk');

const sandboxConfig = {
  'mode': 'sandbox',
  'client_id': '###########################',
  'client_secret': '########################################'
}

paypal.configure(sandboxConfig);

// Send an order to the API to process through paypal.
exports.processPayment = (req, res) => {
  paypal.payment.create(req.body, function (error, payment) {
      if (error) {
          res.send(error);
      } else {
          res.send(payment);
      }
  });
}

```

**Comment by dadsquatch** [comment]
Had a couple go through and they show up in my sandbox.paypal.com account, but it's like 1 in 20 requests that are not ending in a 500 Internal Server error.

**Comment by xiaoleih41** [comment]
Please make sure to use a newly generated credit card number instead.

**Comment by dadsquatch** [comment]
@xiaoleih41 just tried again with a newly generated mastercard and same issue.

**Comment by dadsquatch** [comment]
![image](https://user-images.githubusercontent.com/19417626/39191881-e4fdaad2-47a5-11e8-98b5-aa418c3063fe.png)

This is the same information being passed to the API, the 500 ISEs that it sends back aren't true as eventually one of them results in the sandbox order being placed (shows in my sandbox.paypal.com dashboard minutes after the duplicate error comes about), then it goes back to 500 ISE.

**Comment by xiaoleih41** [comment]
PayPal sandbox testing for direct credit card processing is having issue. I have reported issue. will update with the tracking ticket number.

**Comment by dadsquatch** [comment]
Looks like you guys have this working again. Will keep an eye on it. Close this as well as my other open issue as my recent orders are reporting properly.

**Comment by mitulparmar21696** [comment]
I am getting this error.
Here I pasted error with new debug_id. 
{ Error: Response Status : 500
at IncomingMessage. (/var/www/html/node_modules/paypal-rest-sdk/lib/client.js:130:23)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1056:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
response:
{ name: 'INTERNAL_SERVICE_ERROR',
message: 'An internal service error occurred.',
information_link: 'https://developer.paypal.com/docs/api/payments/#errors',
debug_id: '933022068ba4d',
httpStatusCode: 500 },
httpStatusCode: 500 }
any help will be appreciated

**Comment by xiaoleih41** [comment]
@mitulparmar21696  Yours is a different issue. Can you please reach out to developer.paypal.com/support to submit an error? I am not sure if you have live account permission on this feature as the feature has been deprecated. No new live production approval will be given out. I want to make sure that you have the permission before putting into any integration effort.

**Comment by xiaoleih41** [comment]
Close this issue as the original issue has been solved.
