### ISSUE TITLE
Code stopped working over the weekend

### ISSUE THREAD

**Issue by alan123489** [paypal/PayPal-node-SDK#363]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
{error: "invalid_client", error_description: "Client credentials are missing"}
error
:
"invalid_client"
error_description
:
"Client credentials are missing"

* Language, language version, and OS: php

### Issue description

I'm using

	function paypalButtonCreate(test){
    paypal.Button.render({

		
        env: 'sandbox', 

        client: {
            sandbox:    'A Sandbox api key k',
            production: 'NONE'
        },
        commit: true, // Show a 'Pay Now' button

        payment: function(data, actions) {

            return actions.payment.create({
                payment: {
                    transactions: [
                        {
							item_list: 
								{
								  items: test
								}
									   ,
                            amount: amounthold
                        }
                    ]
                }
            });
        },

        onAuthorize: function(data, actions) {
            return actions.payment.execute().then(function(payment) {
				tansact = payment.transactions;
				details = payment.payer;
				runAjax("authoriseResult",tansact,details);
			
            });
        },
		onCancel: function(data) {
			jQuery('#checkoutHolder').html('<h1>The checkout failed please refresh the page and try again.</h1>');
			
			jQuery(".payPalButton").hide();

		}

    }, '#paypal-button');
}

This was working fine last week and allowed everything to go through.  However today it's just stopped working and says Client credentials are missing.  Has something changed or am I missing something?
It seems to work if I switch it to production mode where all I've changed is 

`        client: {
            sandbox:    'None',
            production: 'Production key'
        },`

thanks

**Comment by xiaoleih41** [comment]
What client ID did you put in and is the app is still in active status?

**Comment by alan123489** [comment]
I'm not sure what you mean by client ID
and yes the app is still active

**Comment by alan123489** [comment]
So it's started working again - my guess is the test system stopped working for a few days and paypal either didn't notice or thought it better not to tell and just fix it.
