### ISSUE TITLE
On live mode configuration host is set to api.sandbox.paypal.com

### ISSUE THREAD

**Issue by Etto91** [paypal/PayPal-node-SDK#364]
```
var paypal = require('paypal-rest-sdk');
paypal.configure({
	mode: "live",
	client_id:
		process.env.PAYPAL_CLIENT ,
	client_secret:
		process.env.PAYPAL_SECRET 
});
console.log(
	'PAYPAL => HOST => ',
	paypal.configuration.host,
	' => MODE => ',
	paypal.configuration.mode
);
```

//log

PAYPAL => HOST =>  api.sandbox.paypal.com  => MODE =>  live

do i have to set manually the host url for live mode?

**Comment by xiaoleih41** [comment]
Yes, you will need to update the host url.

**Comment by Etto91** [comment]
I have set the hosting URL to api.paypal.com but after a payment i can not find the transaction. I can see the api live call from the developer dashboard and PayPal id PAY-XXXX. the payment process is successful on my site but there is no new accreditation. Maybe is not the right place for this issue

**Comment by xiaoleih41** [comment]
Did you check your production account balance on www.paypal.com? Do you have a webhook or IPN set up to track if a payment is successful or not?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity.

**Comment by Etto91** [comment]
i'm sorry for the inactivity time.

I checked my account balance but no transition appeared.

<img width="895" alt="screen shot 2018-05-11 at 09 12 09" src="https://user-images.githubusercontent.com/17198502/39911468-c657f8f4-54fb-11e8-9d6f-6cd4369c6f40.png">

<img width="948" alt="screen shot 2018-05-11 at 09 12 25" src="https://user-images.githubusercontent.com/17198502/39911472-c94f07fa-54fb-11e8-94d7-94d09059c0ef.png">

this is my configuration


```
paypal.configure({
	mode: process.env.PAYPAL_SECRET ? "live" : 'sandbox', //sandbox or live
	host: "api.paypal.com",
        openid_connect_host: 'api.paypal.com',
        openid_connect_port: '',
        authorize_url: 'https://www.paypal.com/signin/authorize',
        logout_url: 'https://www.paypal.com/webapps/auth/protocol/openidconnect/v1/endsession',
	client_id:
		process.env.PAYPAL_CLIENT,
	client_secret:
		process.env.PAYPAL_SECRET 
});

```
