### ISSUE TITLE
Property cart missing from paypal.PaymentResponse type definition

### ISSUE THREAD

**Issue by Smilebags** [paypal/PayPal-node-SDK#365]
### General information
While the property 'cart' is not in the type definition for paypal.PaymentResponse (second argument in the paypal.payment.execute callback), it is a property of that object.

```
paypal.payment.execute(paymentId, payerId, async function (error, payment) {
  payment.cart; // string
});
```
* SDK/Library version: 1.8.1
* Environment: tested in Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Node 8.9.4 Windows 10

### Issue description
```
import * as paypal from "paypal-rest-sdk";
let paymentId = "PAY-5PV18714PL4147816LLTLKTY";
let payerId = { "payer_id": "FXCBB33TDRTV4" };
paypal.payment.execute(paymentId, payerId, async function (error, payment) {
  payment.cart; // string, but TypeScript Error "Property 'cart' does not exist on type 'PaymentResponse'."
});
```
This code example shows the missing type definition.

**Comment by xiaoleih41** [comment]
I don't see it [here](https://developer.paypal.com/docs/api/payments/#payment_execute).

**Comment by Smilebags** [comment]
Neither do I, which is why it needs either removing from the response or added to the documentation/type definition.

**Comment by xiaoleih41** [comment]
Close this issue due to insufficient information.
