### ISSUE TITLE
Get granted consent for future payments

### ISSUE THREAD

**Issue by oscarcalvo** [paypal/PayPal-node-SDK#366]
I know maybe this is not the best place to this question but I have looked for the solution and its complicated, you have a lot of depreciated sdk's, apis etc. 
My question is: working on web, are there any way to get granted consent of one user for future payments? your documentation speaks about mobile sdk but then it says that is depreciated and you have to go to express checkout...where I cant see anything about granted consent.

My use case is typical, I want that customers that buy by second time and above dont need to login again and accept the payment.

Thanks

**Comment by xiaoleih41** [comment]
@oscarcalvo Will you be open to Braintree SDK instead? It's vault feature has PayPal option too. PayPal is working on pushing out the new billing agreement API soon but mobile SDK has been deprecated.

**Comment by javascriptlove** [comment]
just found this after already developing the most parts of the payment system... any news about the progress? is there any workaround without using Braintree?
