### ISSUE TITLE
Payment Method : Credit Card for Subscriptions

### ISSUE THREAD

**Issue by sushantshek20** [paypal/PayPal-node-SDK#368]
Hello,

I am using this code for Subscriptions/Recuring Payments.
https://github.com/paypaldev/node-samples/blob/master/subscriptions-single/subscriptions-single.js
and have referred the billing agreements.
The problem I am facing is, the payment gateway that is redirected to only supports payments if the customer has a paypal account. and no support for credit cards. How can I start accepting credit cards subscriptions?

SideNote: It also opens the Old Paypal UI.

**Comment by xiaoleih41** [comment]
direct credit card feature has been deprecated. Please consider to integrate braintree SDK for credit card processing feature.
