### ISSUE TITLE
Error while doing capture

### ISSUE THREAD

**Issue by subhrawdc** [paypal/PayPal-node-SDK#369]
I am getting error while doing capture. 

I can successfully authorize the payment in paypal. I am able to get paymentId, PayerID and authid but when I am doing **paypal.authorization.capture(authid, capture_details, function (error, capture) {}** I am getting the error. Below is the error code

{"response":{"error":"invalid_client","error_description":"Client Authentication failed","httpStatusCode":401},"httpStatusCode":401}

Below is my code

**var capture_details = {
        amount: {
          currency: 'USD',
          total: '5.54'
        },
        is_final_capture: false
      };
     var authid = '1UV47932S64110024';
  
    // Capture authorization.
    paypal.authorization.capture(authid, capture_details, function (error, capture) {
        if (error) {
          console.error('278 >>> ', JSON.stringify(error));
        } else {
          console.log('280 >>> ', JSON.stringify(capture));
        }
    });**

It is always saying in console
**278 >>>  {"response":{"error":"invalid_client","error_description":"Client Authentication failed","httpStatusCode":401},"httpStatusCode":401}**

**Comment by trainerbill** [comment]
did you configure the paypal rest sdk?  Can you send the debug id and tell me if you are in production or sandbox.

https://github.com/paypal/PayPal-node-SDK#debugging

**Comment by xiaoleih41** [comment]
Close the issue due to inactivity.
