### ISSUE TITLE
Don't Ask for Address

### ISSUE THREAD

**Issue by divrse** [paypal/PayPal-node-SDK#374]
When selling digital products I deliver them digitally and do not need the customer's address, is it possible to set this through this api to not collect the customer's address? Would love a way to do this.

**Comment by sairamchinna** [comment]
Hello @divrse , 

Please check this below link will help you.. 

[hide shipping address ](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment_experience/web_profile/create_payment_with_customized_experience.js)

**Comment by zrthxn** [comment]
The docs say that the billing address is compulsory. Also, AVS verified transactions will need the address so you **can't remove the billing address**

Of course you can hide the shipping address by "no_shipping": 1

**Comment by xjijies** [comment]
@divrse Shall I close this issue or you need any support for this?

**Comment by xjijies** [comment]
@divrse Closing this issue. Please reopen if you are still see this instances around
