### ISSUE TITLE
[2.0] Marketplace API

### ISSUE THREAD

**Issue by mariusa** [paypal/PayPal-node-SDK#377]
* SDK/Library version: 2.0

Please implement the Marketplace API too in 2.0. Since February, docs say only "coming soon". 
Thanks!

**Comment by dcworldwide** [comment]
Would love some updates on this

**Comment by sucithrashanu** [comment]
@mariusa 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future. Please Check [PayPal Community](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts)

Thanks!
