### ISSUE TITLE
[2.0] Please update Creating a Payment example for v2

### ISSUE THREAD

**Issue by mariusa** [paypal/PayPal-node-SDK#378]
At https://github.com/paypal/PayPal-node-SDK/tree/2.0-beta

Creating a Payment
stil uses v1: 
```
const payments = paypal.v1.payments;
```

Please update example to use v2.

**Comment by mariusa** [comment]
I was confused by .v1.
Why does the version need to be exposed in the library SDK? Other libraries simply use no version in SDK. Version is given by the library version, specified in package.json

**Comment by sucithrashanu** [comment]
@mariusa 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.Please Check [PayPal Community](https://www.paypal-community.com)  and  [MTS](https://paypal.com/mts)  

Thanks!
