### ISSUE TITLE
Why same subscription token can be executed mutiple times?

### ISSUE THREAD

**Issue by cijo7** [paypal/PayPal-node-SDK#381]
This occurs when **creating subscription**:

I was testing the integration and i am seeing that after making the payment the returned token could be executed multiple times successfully. Luckily, the agreement id remains the same. But the execute function doesn't return any error. It just auth's user and give access to content.

 So, how can i ensure multiple users doesn't use same token?

**Comment by sucithrashanu** [comment]
@cijo7 ,
Are you asking about Access Token?? 
If yes
Access token generates after giving the client_id and secret_id.
So every user will have separate credentials  to create access token.

Thanks

**Comment by cijo7** [comment]
after making a payment on PayPal, the user is redirected with a token like EC-XXX to the merchant site. This token can be used multiple times to verify payments. So, if I don't cross-verify it with agree id. and rely upon only on token executed success, then duplicate purchases can be made without paying.

**Comment by prakash-gangadharan** [comment]
@cijo7 ,  you said like after making the payment the returned EC-Token could be executed multiple times successfully. 
Yes you could execute multiple times, after the first successful execution it always return the **idempotent response**.  There is no duplicate transaction involved behind it.

**Comment by prakash-gangadharan** [comment]
@cijo7 , after consecutive execution of the EC-Token you can see only the idempotent response with the same agree id. Its doesn't make the duplicate billing agreement id/purchases.

**Comment by cijo7** [comment]
yes, it generates the same result instead of failing until it expires.

I'm referring to the payment verification process at merchant end. The dev has to make sure the agreement id is unique.

**Comment by sucithrashanu** [comment]
@cijo7 
I am closing the ticket. If your dev team have any query please reopen the issue.
