### ISSUE TITLE
nextbillingcycle date not coming properly in excution response

### ISSUE THREAD

**Issue by Sairam-Ch** [paypal/PayPal-node-SDK#382]
@randstraw 
* Environment: Sandbox
### Issue description 
 When am executing the paypal excution using paypal-node-sdk in that response doesn't get proper info for next billing date, please refer below object. I did the transacion today, and my next billing cycle period is : "Day"  but in next billing cycle value in response same date coming. TIA

{"id":"I-TF1NGHUYP2BD","state":"Active","description":"Agreement for Fast Speed Plan","start_date":"2018-08-31T04:00:00Z","payer":{"payment_method":"paypal","status":"verified","payer_info":{"email":"ttest-personal1@gmail.com","first_name":"Jhon","last_name":"Lena","payer_id":"DS57YA7MYHU3E","shipping_address":{"recipient_name":"Jhon Lena","line1":"1 Maire-Victorin","city":"Toronto","state":"Ontario","postal_code":"M5A 1E1","country_code":"CA"}}},"shipping_address":{"recipient_name":"Jhon Lena","line1":"1 Maire-Victorin","city":"Toronto","state":"Ontario","postal_code":"M5A 1E1","country_code":"CA"},"plan":{"payment_definitions":[{"id":null,"name":null,"type":"REGULAR","frequency":"Month","amount":{"value":"100.00"},"cycles":"0","charge_models":[{"id":null,"type":"TAX","amount":{"value":"13.00"},"state":null},{"id":null,"type":"SHIPPING","amount":{"value":"0.00"},"state":null}],"state":null,"frequency_interval":"1"}],"merchant_preferences":{"setup_fee":{"value":"0.00"},"max_fail_attempts":"11","return_url":null,"cancel_url":null,"notify_url":null,"id":null,"state":null,"auto_bill_amount":"YES","initial_fail_amount_action":null,"accepted_payment_type":null,"char_set":null},"currency_code":"CAD"},"links":[{"href":"https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-TF1NGHUYP2BD","rel":"self","method":"GET"}],"agreement_details":{"outstanding_balance":{"value":"0.00"},"cycles_remaining":"0","cycles_completed":"0","next_billing_date":"2018-08-31T10:00:00Z","final_payment_date":"1970-01-01T00:00:00Z","failed_payment_count":"0"},"httpStatusCode":200}

**Comment by sucithrashanu** [comment]
@Sairam-Ch 

Do you still see the issue occurrence on same date of today as in "next_billing_date"?
I tried with billing agreement execution i did't face the issue.  

Thanks

**Comment by Sairam-Ch** [comment]
@sucithrashanu I have't worked on this recently. For overcome this issue i have manipulated the enddate from my side. But once i'll test this scenario add let you know soon.

**Comment by sucithrashanu** [comment]
@Sairam-Ch 
I will close the issue. if you any have  query reopen the issue.
