### ISSUE TITLE
Using PayPal REST SDK in SANDBOX mode, why do i got an orange exclamation mark in the Dashboard of the Webhook page?

### ISSUE THREAD

**Issue by Neokyuubi** [paypal/PayPal-node-SDK#383]
@randstraw

- Environment: Sandbox
**I posted by mistake in the Node section, please someone can delete this issue ? i will re-create one in the PHP's SDK **

**Issue description**
I receive the webhook 'PAYMENT.SALE.COMPLETED' in my server side but in the "Status" column of the Dashboard i got a yellow exclamation mark instead of the green check mark !
So why is that ?

here's a screenshot : ![screen](https://user-images.githubusercontent.com/40678329/45160248-7fcd1880-b1d8-11e8-9766-52290ed4c8a0.jpg)

And i use echo $status; at the end of the listener file/method.
PS : I'm using Laravel

**Comment by sucithrashanu** [comment]
@Neokyuubi 
As you told its not part of Node sdk issue. I am closing the issue.
