### ISSUE TITLE
Payout issue : REQUIRED_SCOPE_MISSING

### ISSUE THREAD

**Issue by Aash-Kothari** [paypal/PayPal-node-SDK#388]
Hello support,

I am integrating paypal in node js seup. Trying to calll payout api using given sdk.
But getting error as follows:
   {
        "name": "REQUIRED_SCOPE_MISSING",
        "message": "Access token does not have required scope.",
        "information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
        "httpStatusCode": 403
    }
I have checked in my paypal account all possible permisiions. But after alll permission I am getting such issues.

My paypal account credentials as follows: 
User name: bharat.chandel@hiteshi.com 
Password: bharat@010

App credentials:
'client_id': 'AaPhQdL0Izk6_TyNpYOP5HshR8PpXT-4nkro10M_SHPBVxbSS38g9050Rk1NqWB9xpy9kQWCdk5O6XLt', 
 
'client_secret': 'EJMFUEV428Lf_Lk0WbJA5G0OPKw9htP3m8MGoGvWzXsS8azF1w-PPHmjvZ_Q_3gJkkejyxR7DJ5Qmesm' 

I am basiically trying to withdraw aount from mechant account to other papal buisness account.
Plesae provide your support.
Thanks & Regards,
Neha Gupta

**Comment by RoyeA** [comment]
Have the same issue.
Any solution ? 
Thanks, 
Roye Avidor

**Comment by RoyeA** [comment]
This resolved my issue : 
https://github.com/paypal/PayPal-node-SDK/issues/372

**Comment by xjijies** [comment]
@Aash-Kothari Are you still facing this Access token does not have required scope issue? Shall I close this issue if you don't have now.

**Comment by xjijies** [comment]
@Aash-Kothari Closing this issue. Please reopen if you are still see this instances around
