### ISSUE TITLE
Invalid value for opts.mode

### ISSUE THREAD

**Issue by EndStatement** [paypal/PayPal-node-SDK#389]
Hello there how can I fix this?
> app.js:210132 Uncaught Error: Invalid value for opts.mode
>     at new module.exports (app.js:210132)
>     at Object.http.request (app.js:115248)
>     at Object.https.request (app.js:37361)
>     at Object.invoke (app.js:115131)
>     at retryInvoke (app.js:12673)
>     at app.js:12644
>     at app.js:12626
>     at exports.IncomingMessage.<anonymous> (app.js:115197)
>     at exports.IncomingMessage.EventEmitter.emit (app.js:27114)
>     at endReadableNT (app.js:116625)
> module.exports @ app.js:210132
> http.request @ app.js:115248
> https.request @ app.js:37361
> invoke @ app.js:115131
> retryInvoke @ app.js:12673
> (anonymous) @ app.js:12644
> (anonymous) @ app.js:12626
> (anonymous) @ app.js:115197
> EventEmitter.emit @ app.js:27114
> endReadableNT @ app.js:116625
> afterTickTwo @ app.js:27400
> Item.run @ app.js:11055
> drainQueue @ app.js:11025
> setTimeout (async)
> runTimeout @ app.js:10943
> process.nextTick @ app.js:11045
> nextTick @ app.js:27399
> resume @ app.js:116398
> Readable.resume @ app.js:116390
> Readable.on @ app.js:116360
> (anonymous) @ app.js:115144
> EventEmitter.emit @ app.js:27099
> ClientRequest._connect @ app.js:210344
> (anonymous) @ app.js:210235
> Promise.then (async)
> ClientRequest._onFinish @ app.js:210233
> (anonymous) @ app.js:210138
> EventEmitter.emit @ app.js:27096
> finishMaybe @ app.js:36973
> afterWrite @ app.js:36835
> afterTick @ app.js:27413
> Item.run @ app.js:11055
> drainQueue @ app.js:11025
> setTimeout (async)
> runTimeout @ app.js:10943
> process.nextTick @ app.js:11045
> nextTick @ app.js:27412
> onwrite @ app.js:36823
> WritableState.onwrite @ app.js:36523
> ClientRequest._write @ app.js:210351
> doWrite @ app.js:36771
> writeOrBuffer @ app.js:36760
> Writable.write @ app.js:36677
> invoke @ app.js:115202
> generateToken @ app.js:12610
> updateToken @ app.js:12639
> executeHttp @ app.js:12698
> create @ app.js:213354
> payOut @ app.js:209949
> callCallback @ app.js:127592
> invokeGuardedCallbackDev @ app.js:127630
> invokeGuardedCallback @ app.js:127679
> invokeGuardedCallbackAndCatchFirstError @ app.js:127693
> executeDispatch @ app.js:127953
> executeDispatchesInOrder @ app.js:127975
> executeDispatchesAndRelease @ app.js:128073
> executeDispatchesAndReleaseTopLevel @ app.js:128084
> forEachAccumulated @ app.js:128054
> runEventsInBatch @ app.js:128215
> runExtractedEventsInBatch @ app.js:128224
> handleTopLevel @ app.js:131969
> batchedUpdates$1 @ app.js:144152
> batchedUpdates @ app.js:129623
> dispatchEvent @ app.js:132048
> interactiveUpdates$1 @ app.js:144207
> interactiveUpdates @ app.js:129642
> dispatchInteractiveEvent @ app.js:132025

**Comment by xjijies** [comment]
@EndStatement  Are you still facing this issue? If you are facing now, which action are trying to do,give more context.

**Comment by xjijies** [comment]
@EndStatement Closing this issue. Please feel to reopen if you are still see this instances around.
