### ISSUE TITLE
MALFORMED_REQUEST

### ISSUE THREAD

**Issue by vishal3011** [paypal/PayPal-node-SDK#390]
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Response Status : 400",
    "response": {
      "name": "MALFORMED_REQUEST",
      "message": "Incoming JSON request does not map to API request",
      "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST",
      "debug_id": "30edea0840e41",
      "httpStatusCode": 400
    },
    "httpStatusCode": 400,
    "stack": "my stack",
}

Can you please let me know what's wrong with my request?

**"debug_id": "30edea0840e41"**

**Comment by a8hokkumar** [comment]
Hello, 

I am a payer, I want to know more information about payee. As of now I have payee emailId, How I will know more about payee(Address, location, timezone).

What api help me to get payee information using emailId?(Email which is used by payee to create their own Paypal account)

**Comment by xjijies** [comment]
@vishal3011 Can you give more context about what you tried with sample snippet of request data

**Comment by sucithrashanu** [comment]
@a8hokkumar 
You should be a merchant to call the API's

Thanks
