### ISSUE TITLE
archive a invoice

### ISSUE THREAD

**Issue by Wqrld** [paypal/PayPal-node-SDK#391]
Hello, how would i archive a invoice? I am able to cancel it but it doesn't disappear from my paypal account before explicitly archiving it.

**Comment by xjijies** [comment]
@Wqrld Are you expecting to do Archive using SDK instead of my PayPal account?

**Comment by Wqrld** [comment]
This issue is almost a year old.

I wanted to do it by SDK but i chose to go with the express checkout system later. This would probably still be a good feature to have.

**Comment by xjijies** [comment]
@Wqrld Currently we don't have API to archive a invoice. Closing this ticket
