### ISSUE TITLE
OAuth/OpenID token regeneration

### ISSUE THREAD

**Issue by unckleg** [paypal/PayPal-node-SDK#395]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

What should developers do in case when there is scope changing (Sandbox enabling) that is not immediately reflected in hashed token due to cached version of the same.

Or changing of secret_key ?

**Comment by sucithrashanu** [comment]
@unckleg 
Can you give more context about the issue and give any one use cases it would be helpful for me to give solution to your query.

Thanks

**Comment by sucithrashanu** [comment]
@unckleg 
I am closing the ticket. If you have any query please reopen the issue.

Thanks
