### ISSUE TITLE
Client Authentication failed when backend server restart

### ISSUE THREAD

**Issue by cheong12001** [paypal/PayPal-node-SDK#396]
i am using PayPal-node-SDK in my node server. when i finish implement the api, i got "error":"invalid_client","error_description":"Client Authentication failed" response randomly. Later, i discover that, when i update my server and restart it, transaction with fail with the message "error":"invalid_client","error_description":"Client Authentication failed". the solution is my client must refresh the frontend web and checkout again.

Reproduction step:
1. load frontend checkout website 
2. restart the backend server
3. start checkout with paypal
4. backend server will catch error with message: "error":"invalid_client","error_description":"Client Authentication failed"
5. told the client to refresh their frontend browser.
6. checkout again.
7. checkout success.

the question is, when i update my backend server. all client should restart their frontend website to make the transaction success.

**Comment by xjijies** [comment]
@cheong12001 Are you still facing this issue? I will check if you have this issue now.

**Comment by xjijies** [comment]
@cheong12001 Closing this issue. Please feel to reopen if you are still see this instances around.
