### ISSUE TITLE
How to get payout_batch_id

### ISSUE THREAD

**Issue by SCharity2018** [paypal/PayPal-node-SDK#402]
Upon creation of payout, the payout_batch_id (payoutId) will be showed in console as a response.
How can I can get the payout_batch_id from the response or from any other ways and assign it to the variable(var payoutId)?

```
//After the creation of payout i managed to get a response
paypal.payout.create(create_payout_json, sync_mode, function (error, payout) {
    if (error) {
        console.log(error.response);
        throw error;
    } else {
        console.log("Create Single Payout Response");
        console.log(payout);
    }
});

//How to I get this? I need this to check the payout.
var payoutId = ;

paypal.payout.get(payoutId, function (error, payout) {
    if (error) {
        console.log(error);
        throw error;
    } else {
        console.log("Get Payout Response");
        console.log(JSON.stringify(payout));
    }
});
```
I am new to node.js, please help. 
Thanks  :)

**Comment by thirtified** [comment]
Hi @SCharity2018, the Payout Batch ID is returned as the property `payout_batch_id` of the `batch_header` object in the response. Extending your sample code,

```javascript
paypal.payout.create(create_payout_json, function(error, payout) {
    if (error) {
        console.log(error.response);
        throw error;
    } else {
        console.log("Create Payout Response", payout);
        var payoutBatchID = payout.batch_header.payout_batch_id;

        // Use Payouts Batch ID from here for further calls, e.g.
        // paypal.payout.get(payoutBatchID, function() { … });
    }
});
```
Please note:
- The Payout Batch ID will only become available in the callback of the Create Payout call. In your example, you are calling Get Payout in parallel – this won't work.
- The `sync` mode for Payouts has been deprecated.

**Comment by xjijies** [comment]
@SCharity2018 Have you tried above sample,
var payoutBatchID = payout.batch_header.payout_batch_id;
Shall I close this issue?
