### ISSUE TITLE
PayPal PayOut API limits

### ISSUE THREAD

**Issue by dcworldwide** [paypal/PayPal-node-SDK#406]
What are the limitations of the PayPal payouts api? There are not documented on the website and there is no info on stackoverflow or the official paypal forum.

I'd like to know:

- Max recipients per payment?
- Max $ amount per payment?
- Max $ amount per recipient within a single payment?

Appreciate some clarity. This is a tough question to find an answer to.

**Comment by thirtified** [comment]
Hi @dcworldwide, thanks for your feedback. Please have a look at the [official Payouts documentation](https://developer.paypal.com/docs/payouts/) and the [Payouts FAQs](https://developer.paypal.com/docs/payouts/reference/faq/):

> **API Integration**: Up to 15,000 recipients in a single call

and

> **How much money can I send?**
> There is no limit on the total amount of the payout. Each individual payment can be no more than $20,000.00 USD or its equivalent in local currency by default. If you need to send higher value payments, please contact your account representative or Customer Service.

Hth,
\- Julian

**Comment by dcworldwide** [comment]
Thankyou Julian. Appreciate your answer.
