### ISSUE TITLE
Is this module still under development?

### ISSUE THREAD

**Issue by ChrisTalman** [paypal/PayPal-node-SDK#409]
It's a little unclear whether this module is still under development. The `README.md` has a [section](https://github.com/paypal/PayPal-node-SDK#20-release-candidate) on '2.0 Release Candidate', but the last commit to the 2.0 branch seems to be in April last year, and 2.0 seems to remain in beta. It would be much appreciated if the status of the module, and 2.0 in particular, could be clarified.

**Comment by dshaw** [comment]
@ChrisTalman Short answer is yes. We have a bunch of updates coming soon. This will include moving 2.0 out of "beta".

What are you integrating?

**Comment by ChrisTalman** [comment]
@dshaw Thanks for the clarification, that's good to hear.

I was considering using this module to create, execute, and otherwise manage billing agreements.

The billing agreements API endpoint response provides an approval URL, to which users could be redirected, where they can approve the agreement.

However, it seems as though quite a few websites use a slightly different flow, somehow making use of the PayPal Checkout popup UI instead of a redirect. Presumably, they pass something to the server which can be executed to start the billing agreement. I haven't been able to work out how this flow is implemented, though.

**Comment by mwalden2004** [comment]
Hey @ChrisTalman 
 Is it possible they are using Braintree?

**Comment by ChrisTalman** [comment]
@mwalden2004 One site seems to be using a service called *Recurly*. I'm not familiar with that service. I haven't looked into the markup on other sites.

**Comment by mwalden2004** [comment]
Strange, I have never heard of it.

**Comment by silverskysoft** [comment]
@dshaw  -- Any update on when this package would move to production? The 1.8.x series API endpoints are now deprecated in the documentation.

**Comment by manian-kumaran** [comment]
Is this PayPal node SDK still maintained? The v2 is still RC and seems to get stuck in that version since April 2018 and very soon we are in 2020.

As @silverskysoft said, the 1.8.x series API endpoints are now deprecated in the documentation. 

Is there alternative for PayPal node.js SDK or should we just do the raw HTTP REST transaction in the examples using curl in the doc, if PayPal node.js SDK is no longer maintained?

**Comment by manian-kumaran** [comment]
Is seems that the whole PayPal SDK is no longer maintained? The last commit was more than 2 years ago.

Can someone from PayPal update the status? It's going to be sad if we have to drop PayPal payment support because there is no reliable/maintained SDK.

**Comment by mwalden2004** [comment]
I'm thinking of making my own PayPal SDK, and maintaining it.

**Comment by sucithrashanu** [comment]
@ChrisTalman 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.Please Check [PayPal Community](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts) 

Thanks!

**Comment by JustDoItSascha** [comment]
Once again: Are there any updates? It seems no one is working on this package anymore? Am I right?
