### ISSUE TITLE
Payer payment api

### ISSUE THREAD

**Issue by hieunguyenvanLC** [paypal/PayPal-node-SDK#410]
Hi Guys. My question is simple. I would like to create an approved payment in order to test my business logic. Documentation says I have to create a Payment, then the customer has to approve it before I can execute it and this is my problem. I build an app with face recognize payment solution, and I already have account paypal payer account. I would like to use API to approve order, without access paypal view. I do want to process all of it in terminal so customers don't have to click accept button. Is it possible to do that? Thank you all.

**Comment by sucithrashanu** [comment]
@hieunguyenvanLC 
Can you post code snippet for the above query.

**Comment by sucithrashanu** [comment]
@hieunguyenvanLC 
I am closing this ticket. If you are facing the above mentioned issue still now? Feel free to re-open the issue.

Thanks
