### ISSUE TITLE
New subscriptions APIs support

### ISSUE THREAD

**Issue by ilDon** [paypal/PayPal-node-SDK#411]
### General information

* SDK/Library version: 2.0 Beta
* Environment: Sandbox and Production
* Language, language version, and OS: NodeJs

### Issue description

The ReadMe file specifies that subscriptions are supported, but it links to the old deprecated APIs [Subscription Payments](https://developer.paypal.com/docs/integration/direct/create-billing-plan/)

Do the beta version supports the [new subscriptions APIs](https://developer.paypal.com/docs/limited-release/subscriptions/)?

**Comment by givethemheller** [comment]
There is no support for the new subscriptions api in the current release as of today. Documentation indicates that the billing plan api's are now deprecated. 

might see if I can get at this. I need it.

**Comment by givethemheller** [comment]
trying to help get the ball moved along on this with some work of my own.
https://github.com/paypal/PayPal-node-SDK/pull/418

**Comment by updatesvc** [comment]
its kinda sad that a company like paypal does a poor Job with their APIs and documentation.
@givethemheller 
I saw that it wasn't mergerd, do you have a forked version of the sdk with v2 subscriptions?

**Comment by rpappa** [comment]
I started working on this out of necessity here:
https://github.com/DestroyerBots/PayPal-node-SDK

I didn't base off v2 since we needed something production-ready. Not sure if I'm doing things right but if there's interest in getting this merged I can keep working on it, it still needs many of the endpoints added and better testing.

**Comment by lematy** [comment]
this is why iv built a checkout tool, where you connect your paypal/stripe and on your app call an api for a checkout link, and all subscriptions are handled by Stripe and Paypal.

And yes, this api was pretty bad to work with, just lack of documentation.

Should be out soon

**Comment by sucithrashanu** [comment]
@ilDon 
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )

Thanks!
