### ISSUE TITLE
Webhook verification always fail

### ISSUE THREAD

**Issue by souzajr** [paypal/PayPal-node-SDK#412]
### General information

* SDK/Library version: Latest
* Environment: Production
* `PayPal-Debug-ID` values: NaN
* Language, language version, and OS: NaN

### Issue description

Whenever I try to check PayPal webhook, I get a verification status failure. What am I doing wrong?

Code:
`paypal.notification.webhookEvent.verify(req.headers, req.body, process.env.PAYPAL_CLIENT_WEBHOOKID, async (error, response) => {})`

Response:
`{ verification_status: 'FAILURE', httpStatusCode: 200 }`

**Comment by egorsmth** [comment]
Hi, this is because inside of `paypal.notification.webhookEvent.verify` they use `JSON.parse` on `req.body`, because of that some float values might change to int.
I got same case there 1.0 changed to 1 and because of that verification failed.
My solution to that was to implement my own verify function
```
const VERIFY_URL = 'https://api.paypal.com/v1/notifications/verify-webhook-signature';

async function verify(header, body, token, webhookId) {
    const
        webhookObjJSON = '{' +
        '"auth_algo": "' + header['paypal-auth-algo'] + '"' +
        ',"cert_url": "' + header['paypal-cert-url']+ '"' +
        ',"transmission_id": "' + header['paypal-transmission-id']+ '"' +
        ',"transmission_sig": "' + header['paypal-transmission-sig']+ '"' +
        ',"transmission_time": "' + header['paypal-transmission-time']+ '"' +
        ',"webhook_id": "' + webhookId + '"' +
        ',"webhook_event": ' + body +
        '}',

        validationReqOptions = {
            headers: {
                'Authorization': token,
                'content-type': 'application/json'
            },
            body: webhookObjJSON,
            method: 'POST'
        },

        res = await api.request(VERIFY_URL, validationReqOptions);

    return JSON.parse(res.body);
}
```

**Comment by souzajr** [comment]
Hello!

Thanks for helping. Which library are you using to make the request?

**Comment by egorsmth** [comment]
request https://www.npmjs.com/package/request

**Comment by souzajr** [comment]
Thanks!
