### ISSUE TITLE
Fix verify function

### ISSUE THREAD

**Issue by egorsmth** [paypal/PayPal-node-SDK#414]
* SDK/Library version: 1.8.1
* Environment: Sandbox and Production
* Language, language version, and OS: node.js 11

### Issue description

There is an issue with verify function. Because of using `JSON.parse` on body, some values are changed. For example `1.0` become  `1`, that is give us failure on verification in paypal.
Please fix that.

**Comment by xjijies** [comment]
Hi @egorsmth , can you add more context about this issue? do you have code snippet?

**Comment by egorsmth** [comment]
@xjijies 
```
var foo = {a: 1.0}
var bar = JSON.parse(JSON.stringify(foo))
console.log(foo === bar)
console.log(bar)

// false
// {a: 1}
```

**Comment by xjijies** [comment]
@egorsmth Can you tell me for which flow you are facing this issue. I mean the function and file you called under lib/resources/*

**Comment by egorsmth** [comment]
@xjijies 
`Notification.js` line 119
When we receive webhook we should call `verify` function to verify that this webhook is from paypal.
We pass to verify received headers and body, which sdk transform and sends to paypal for validation. 
As you see in `Notification.js` on line 119, sdk either call JSON.parse to parse body or just use object we passed to make request. But if our body countains in some field value `1.0`, it parsed and the stringified to 1, so paypal can't validate it.

**Comment by xjijies** [comment]
@egorsmth I tried with sample in PayPal-node-SDK,  webhook_payload_verify.js. In eventbody decimal values are in stringify pattern, I got verification_status as Success. For var foo = '{"a": "1.0"}'  parsed value result in 1.0. Do you have any use case where you send data in decimal number format.

**Comment by xjijies** [comment]
@egorsmth Closing this issue. Please reopen if you are still need any help further around this.
