### ISSUE TITLE
Capture function is displaying incorrect error messaging

### ISSUE THREAD

**Issue by BrandonCopley** [paypal/PayPal-node-SDK#415]
When performing a DUPLICATE PAYPAL.authorization.capture()

ERROR: AUTHORIZATION_CANNOT_BE_VOIDED will be shown, however the old error message that used to be returned was ERROR: AUTHORIZATION_ALREADY_COMPLETED which was far more accurate.

**Comment by sucithrashanu** [comment]
<img width="1408" alt="Error_Msg" src="https://user-images.githubusercontent.com/11882622/66896825-4f7abf00-f013-11e9-8bd6-16bdc3749182.png">
@BrandonCopley : 
I am using the version SDK 1.8.1 and getting error message like  ERROR: AUTHORIZATION_ALREADY_COMPLETED when status is "state": "approved".

**Comment by sucithrashanu** [comment]
@BrandonCopley 
I am closing the ticket. If you have any query please reopen the issue.

Thanks
