### ISSUE TITLE
How to use promises for Payout?

### ISSUE THREAD

**Issue by rajababu3** [paypal/PayPal-node-SDK#416]
### General information

* SDK/Library version:beta 
* Environment:sandbox 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

How to use promises for Payout?

**Comment by Nate66676** [comment]
stevensnathan232@gmail.com

**Comment by Nate66676** [comment]
stevensnathan232@gmail.com

**Comment by xjijies** [comment]
@rajababu3 Do you want to use promise node module instead of callback?

**Comment by xjijies** [comment]
@rajababu3 Closing this issue. Please feel to reopen if you are still see this instances around.

**Comment by xjijies** [comment]
@rajababu3 Closing this issue. Please feel to reopen if you are still see this instances around.
