### ISSUE TITLE
PayPal GET /v1/reporting/transactions ? 

### ISSUE THREAD

**Issue by tiagosiebler** [paypal/PayPal-node-SDK#417]
Hello, either I'm missing something blatantly obvious, or this SDK is only meant for the processing of payments? Can I use this API via this module?

https://developer.paypal.com/docs/api/sync/v1/#transactions

I want to query a list of transactions between two days. Thanks!

**Comment by Maximvdw** [comment]
+1

**Comment by xjijies** [comment]
@tiagosiebler You can pass start_date and end_date to query list of transactions 

https://api.sandbox.paypal.com/v1/reporting/transactions?start_date=2019-07-01T00:00:00-0700&end_date=2019-07-03T23:59:59-0700

**Comment by xjijies** [comment]
@tiagosiebler Closing this issue. Please reopen if you need any help further around this.

**Comment by 50bbx** [comment]
+1 here. Can I use this SDK to call /v1/reporting/transactions ? It doesn't seem possibile, at the moment.
