### ISSUE TITLE
where is POST https://api.sandbox.paypal.com/v1/billing/subscriptions ?

### ISSUE THREAD

**Issue by egorsmth** [paypal/PayPal-node-SDK#419]
Can't find `POST https://api.sandbox.paypal.com/v1/billing/subscriptions`

**Comment by fgnm** [comment]
This SDK miss any new subscriptions API, so I'm wondering why if this is the official SDK it isn't updated?

**Comment by lukeatt** [comment]
Same problem here, trying to implement subscriptions on my system and was following the PayPal guide: https://developer.paypal.com/docs/subscriptions/integrate/#4-create-a-subscription
but couldn't find a way to execute the same steps using the node SDK particularly this 
POST https://api.sandbox.paypal.com/v1/billing/subscriptions

**Comment by fgnm** [comment]
This repository seems to be abandoned... I'm implementing new REST APIs of my own on top of this repository

**Comment by Gr8z** [comment]
A billion-dollar company can't even keep its official wrapper up to date.

**Comment by prakash-gangadharan** [comment]
Hi folks, current REST sdks still using below `Billing Plans API` which is  deprecated.
https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans

**Deprecation notice**:

-  The /v1/billing-plans endpoints are deprecated. 
- Use the /v1/billing/subscriptions endpoints instead. 
- For details, see [Subscriptions Integration](https://developer.paypal.com/docs/subscriptions/integrate/).

Currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one but it may be available in near future.

**Comment by prakash-gangadharan** [comment]
Similar issue : https://github.com/paypal/PayPal-node-SDK/issues/431

**Comment by cjohnweb** [comment]
I'm trying to get react-paypal-button-v2 npm package to go. I'm getting the same error but the subdomain is different:

POST https://www.sandbox.paypal.com/v1/billing/subscriptions 404
