### ISSUE TITLE
Can I use PayPal-node-SDK for Donation Purpose

### ISSUE THREAD

**Issue by trungdh** [paypal/PayPal-node-SDK#424]
Hi,
I'm trying to build a non-profit application which to help donor can directly transfer money to anybody who need help via paypal.
I'm already integrated this SDK for my Node server. But when donor send donation money to beneficiary, it work as steps :
1. Donor send money to intermediate account which be used to register application on paypal to get ClientID key and secret key
2. System auto send that donation money to beneficiary's paypal account by payout APIs
But with this solution, I have lost double paypal fees.

So do we have any solution or paypal policy for non-profit application to minimum paypal fees to help beneficiary can get more money from donor ?

**Comment by ian-maurmann** [comment]
Donate button link is broken.
