### ISSUE TITLE
is it possible to use masPay (payouts) behalf third party?

### ISSUE THREAD

**Issue by Vladinho10** [paypal/PayPal-node-SDK#427]
I have an app. There are 3 types of users seller, buyer and broker. I want to send money from seller Paypal to buyer Paypal and Broker Paypal. Is it possible?

It's my code
        const api = new PermissionsApi({
            mode: 'sandbox', // set "live" for production
            userId: paypalAppData['X-PAYPAL-SECURITY-USERID'],
            password: paypalAppData['X-PAYPAL-SECURITY-PASSWORD'],
            signature: paypalAppData['X-PAYPAL-SECURITY-SIGNATURE'],
            appId: paypalAppData['X-PAYPAL-APPLICATION-ID'],
        });

        const scope = ['MASS_PAY', 'ACCESS_BASIC_PERSONAL_DATA', 'ACCOUNT_BALANCE'];
        const returnUrl = 'http://localhost:3001/payments/paypal/permission';

        const response = await UtilsService.promisify(api, 'requestPermissions', [scope, returnUrl]);
I got this response
{ responseEnvelope:
   { timestamp: '2019-06-17T01:39:45.122-07:00',
     ack: 'Success',
     correlationId: '8c1b0d7b3add4',
     build: '2210301' },
  token: 'AAAAAAApzCFeAHi7EB5S' }
then I passed this token to query and suggest my seller to login with Paypal. When seller is already logged in, he grand permissions to app account. Then I got this 
userData { responseEnvelope:
   { timestamp: '2019-06-17T01:40:18.948-07:00',
     ack: 'Success',
     correlationId: 'f3a110cbc210d',
     build: '2210301' },
  scope:
   [ 'ACCOUNT_BALANCE',
     'MASS_PAY',
     'INVOICING',
     'ACCESS_BASIC_PERSONAL_DATA' ],
  token: 'RvR99ZWIqjhdB1HypXCY8tMFcQ3SZP7bNa5H0T5kCViBtEXzEZyuhg',
  tokenSecret: 'AqnkKG0kKqdVXO.R8J9yH2IKCcM' }
 then how can I send seller's money to the buyer and broker?

**Comment by sucithrashanu** [comment]
@Vladinho10 
**Note**:The MassPay API is Deprecated 
Why can't you try for "Payout"? Using PayPal Payouts we can send money to multiple people at the same time.
[Link](https://developer.paypal.com/docs/payouts/#payouts-flow)

Thanks
