### ISSUE TITLE
PayPal Auth - Adaptative Payments

### ISSUE THREAD

**Issue by jdgabriel** [paypal/PayPal-node-SDK#429]
### General information

* SDK/Library version: latest skd
* Environment: Production 
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: Node:latest on Windows

### Issue description

Hello devs;

How do I get a paypal authorization to use adaptive payment? 
Do I really need this authorization?

PS: I have my whole code ready and tested in the sandbox.

Thanks...  :+1:

**Comment by sucithrashanu** [comment]
@jdgabriel 
The below link will be helpful for Adaptive payment  
https://developer.paypal.com/docs/classic/adaptive-payments/gs-AdaptivePayments/

**Comment by jdgabriel** [comment]
Ty.
