### ISSUE TITLE
Error 500- paypal.billingPlan.get

### ISSUE THREAD

**Issue by JasminDreasond** [paypal/PayPal-node-SDK#431]
### General information

* SDK/Library version: 1.8.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 8aa0631a61be7
* Language, language version, and OS: Nodejs, Windows 10

### Issue description

The callback return a error 500.

```js
var fs = require('fs');
var http = require('http');
var https = require('https');
var privateKey  = fs.readFileSync('server.key', 'utf8');
var certificate = fs.readFileSync('server.crt', 'utf8');

var credentials = {key: privateKey, cert: certificate};
var express = require('express');
var app = express();
var bodyParser = require('body-parser');
var paypal = require('paypal-rest-sdk');

app.use(bodyParser.json());       // to support JSON-encoded bodies
app.use(bodyParser.urlencoded({     // to support URL-encoded bodies
    extended: true
}));

paypal.configure(HIDDEN);

app.post('*', function (req, res) {

    console.log(req.body);
    paypal.notification.webhookEvent.getAndVerify(JSON.stringify(req.body), (error, response) => {
        if(response === true || response === "true") {
            console.log(req.body.resource.plan_id);
            paypal.billingPlan.get(req.body.resource.plan_id, function (error, billingPlan) {
                if (!error) {
                    console.log("Get Billing Plan");
                    console.log(billingPlan);


                    if(req.body.event_type === "BILLING.SUBSCRIPTION.CREATED"){

                    }



                } else {
                    console.error(error);
                }
            });
        }
        res.end();
    });

});

// your express configuration here

var httpServer = http.createServer(app);
var httpsServer = https.createServer(credentials, app);

httpServer.listen(80);
httpsServer.listen(8443);


```

**Comment by sucithrashanu** [comment]
@JasminDreasond 
If you are still facing this issue.Please provide latest PayPal-Debug-ID.
Thanks

**Comment by prakash-gangadharan** [comment]
Hi @JasminDreasond, do you have any recent instance of this Error 500?

**Comment by sucithrashanu** [comment]
@JasminDreasond 

The reported issue look like  merchant is doing the create plan using new api call and trying to get the plan details using old legacy api. 

**POST**-Create a Billing Plan using *https://api.sandbox.payapl.com/v1/billing/plans*
**GET**- Do a get call using  https://api.sandbox.payapl.com/v1/payments/billing-plans/{{planId}}
**Error** will be thrown stating "Internal error while fetching plan information.Please contact administrator"

**Comment by JasminDreasond** [comment]
the debug id is 30a49b57e4d34
the plan creator is  https://api.sandbox.payapl.com/v1/billing/plans

**Comment by prakash-gangadharan** [comment]
@JasminDreasond, it looks like you have created billing plan via below API https://developer.paypal.com/docs/api/subscriptions/v1/#plans_create.

https://developer.paypal.com/docs/api/subscriptions/v1/#plans - this new endpoint was not implemented in sdk yet and it is still using the deprecated endpoint.

This issue occurs when you create billing plan via new enpoint and trying to make GET call via deprecated endpoint.

**Comment by prakash-gangadharan** [comment]
@JasminDreasond REST Sdks still using below Billing Plans API
https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans

**Deprecation notice**:

-  The /v1/billing-plans endpoints are deprecated. 
- Use the /v1/billing/subscriptions endpoints instead. 
- For details, see [Subscriptions Integration](https://developer.paypal.com/docs/subscriptions/integrate/).

Currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one but it may be available in near future.

**Comment by prakash-gangadharan** [comment]
Similar issue : https://github.com/paypal/PayPal-node-SDK/issues/431
