### ISSUE TITLE
Setup fee not showing when paying

### ISSUE THREAD

**Issue by josepgomes** [paypal/PayPal-node-SDK#434]
Hi!

I'm using this sample: https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/create.js

When i'm at check out, there is nothing about the fee or shipping or taxes... and nothing is removed from the account when paying, immediately... but with a really long delay!

I'm in the sandbox... is this the normal behavior?

**Comment by sucithrashanu** [comment]
@josepgomes 
Can you  please give Clear context about the issue and code snippet?

**Comment by sucithrashanu** [comment]
@josepgomes 
I think your Issue has been resolved. I am closing the issue. If you have any query please reopen the issue.
