### ISSUE TITLE
Cancel thousands of agreements at the same time

### ISSUE THREAD

**Issue by josepgomes** [paypal/PayPal-node-SDK#435]
Hi,

Paypal has a sample for cancel an agreement: https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/cancel.js

What happens if i have more than 2000 users, each one with an agreement and i need to cancel all of them?

Is there any alternative? Like, telling paypal to cancel an array of agreements? Will it block me after x requests if i make one at a time?

Many thanks!

**Comment by prakash-gangadharan** [comment]
Hi @josepgomes, an API to do bulk cancel does not exist for RT/Billing Agreement.
You can try writing a script to invoke Cancel API in a batch.
