### ISSUE TITLE
PayPal's SDK Exposes its Applications to Priv. Escalation

### ISSUE THREAD

**Issue by k1ngshaq** [paypal/PayPal-node-SDK#442]
### General information

* SDK/Library version: all of them
* Language, language version, and OS: nodejs, all systems.

### Issue description

Hi, i found a critical security vulnerability and reported it via HackerOne platform. They basically told me that this is out of scope because they didn't wanted to make an exception and pay a $20,000 bounty. They also didn't reward with a lower amount, a swag or fame(not professional at all but whatever...I'm over it. You guys just lost another researcher...i already moved to another program). 

Anyways, they told me that i should approach you guys. Is there an official email of a PayPal employee(**who is also responsible for this repo**) that you can provide me so i can forward the report? I'm not a git expert so i'm not sure if this thread is visible for everybody or not (i believe in a responsible disclosure. I don't think that it should be publicly available until you deploy a fix) 

thanks! :)

**Comment by sucithrashanu** [comment]
@k1ngshaq  If this not an integration issue with PayPal-node-SDK, refer the below link for merchant technical support.
[link](https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723)

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!

**Comment by k1ngshaq** [comment]
Hi @sucithrashanu , thanks for the quick response.
I don't know if it falls under the definition of an *integration issue*. Or maybe i misunderstood your reply.
It's a vulnerability that is found in the code, which affects every application that makes use the nodejs sdk. 

I've forwarded the question (without details about the report) to the technical support. First i want to see if they can confirm that i sent the message to the right place. Then i'll send the report.

**Comment by lmarkus** [comment]
You can forward it directly to me. 
Lmarkus at PayPal dot com.

**Comment by johnsonsan** [comment]
Sent from Yahoo Mail on Android 
 
  On Fri, Nov 1, 2019 at 7:18 AM, Lenny Markus<notifications@github.com> wrote:   
You can forward it directly to me.
Lmarkus at PayPal dot com.

**Comment by k1ngshaq** [comment]
> You can forward it directly to me.
> Lmarkus at PayPal dot com.

Hi Markus, i sent you an email. We can discuss more over there.
