### ISSUE TITLE
Paypal transaction API returns `Data for the given start date is not available.`

### ISSUE THREAD

**Issue by ashokraghu14** [paypal/PayPal-node-SDK#452]
### General information

* SDK/Library version: paypal-base:1.0
* Environment: Production
* `PayPal-Debug-ID` values: 4a924c46669da
* Language, language version, and OS: jdk1.8.0_60 on Ubuntu 16.04

### Issue description

When requesting the Reporting [API](https://api.paypal.com/v1/reporting/transactions) for the last 30 days, I'm getting the following response from the API for the days since 8th March:

`{"debug_id":"4a924c46669da","name":"INVALID_REQUEST","details":[],"links":[],"message":"Data for the given start date is not available."} |GatewayName=PayPal, AccountName=<redacted>, InputDateRange=[2020-01-11T00:00:00.000Z UTC, 2020-03-11T00:00:00.000Z UTC], ReportingSliceDateRange=[2020-03-09T00:00:00.000Z UTC, 2020-03-09T23:59:59.999Z UTC], GatewayRequstDateRange=[2020-03-09T00:00:00+0000 UTC, 2020-03-09T23:59:59+0000 UTC]`

But there are transactions happed for those days and I'm able to see the transaction on the Paypal gateway dashboard.

Please help me out with the issue.

**Comment by sunnykoundal** [comment]
I am facing the same problem, what was the solution for this ?

**Comment by sunnykoundal** [comment]
Thanks for Reply!!
Yes, I know it has a date there. Actually I have a scheduler to check every 10 minutes after the transactions which is not fulfilling my purpose as date issue is coming. Do you have any idea how to get rid of that ?

**Comment by ashokraghu14** [comment]
It looks like it's problem with the API. I would advice you to wait for two days. It'll fix by itself. We gone through their forum and found it's a know issue.
