### ISSUE TITLE
Payer info not available when getting the billing agreement

### ISSUE THREAD

**Issue by bcallaars** [paypal/PayPal-node-SDK#62]
When I do `paypal.billingAgreement.get` the `payer` property is never added to the response object as shown in the documentation.

https://developer.paypal.com/webapps/developer/docs/api/#retrieve-an-agreement 

I assume this is because of an API problem as shown here (https://github.com/paypal/PayPal-Python-SDK/issues/57) or am I wrong?

**Comment by bcallaars** [comment]
[f: 1h]

**Comment by jziaja** [comment]
Hi @bcallaars, the API team is actively working on getting this fixed.

(cc [PayPal PHP SDK Issue #155](https://github.com/paypal/PayPal-PHP-SDK/issues/155))

**Comment by avidas** [comment]
This bug is getting tracked in ( [PayPal PHP SDK Issue #155](https://github.com/paypal/PayPal-PHP-SDK/issues/155))
