### ISSUE TITLE
It is impossible to set up more than one pay-pal configuration

### ISSUE THREAD

**Issue by alekbarszczewski** [paypal/PayPal-node-SDK#63]
What I need is to use 2 pay-pal APPs (with different client_id/secret). It seems that there is no such option in `PayPal-node-SDK` because there is only global `paypal.configure(...)` method. Or maybe I am missing something? Is it possible to work with more than one pay-pal APP?

**Comment by avidas** [comment]
Hey @alekbarszczewski it is supported. Let me provide a sample which demonstrates that behavior

**Comment by avidas** [comment]
@alekbarszczewski Check out the [sample](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/configuration/multiple_config.js) for multiple config support.

**Comment by alekbarszczewski** [comment]
@avidas Thank you!
