### ISSUE TITLE
Required Scope Missing

### ISSUE THREAD

**Issue by ongspxm** [paypal/PayPal-node-SDK#66]
When I tried creating a Payout, I couldn't really get it to work, I keep receiving the "Required Scope Missing" error. Couldn't find any answers, anyone tried using payout yet?

**Comment by grydstedt** [comment]
@ongspxm were you able to resolve this?

**Comment by ongspxm** [comment]
it was a long time ago. But if my memory serves me right, it was to do with some of the paypal settings itself. there is a setting page to enable payouts for your account.
