### ISSUE TITLE
paypal.billingAgreement.get() documentation for state field 

### ISSUE THREAD

**Issue by mulyoved** [paypal/PayPal-node-SDK#67]
looking at this link

https://developer.paypal.com/docs/api/#agreement-object

I don't see the state field documented, when testing I get state: 'Active' what other values I can expect? where this is documented?

**Comment by jziaja** [comment]
Thanks for reporting this @mulyoved!  I'm following up with the docs team to see if we can get this added along with the expected `state` values.  I know `Pending` and `Expired` are other possible states, but I'll check with the subscription team to get the full list and share that here.

**Comment by avidas** [comment]
@mulyoved updates: this will go out soon with documentation updates.

**Comment by avidas** [comment]
This will go out with the next release of docs
