### ISSUE TITLE
`utils.merge` has a bug that is causing some other failures.

### ISSUE THREAD

**Issue by kobalicek** [paypal/PayPal-node-SDK#69]
Guys, I spent today some time with a bug on your side that is happening in `api.js`, this code:

```
function updateToken(http_options, error_callback, callback) {
    generateToken(http_options, function (error, token) {
        if (error) {
            error_callback(error, token);
        } else {
            http_options.headers.Authorization = token;
            callback();
        }
    });
}
```

The problem is that `http_option.headers` is undefined so it throws TypeError. I tracked it down and the issue is most probably in your `utils.merge` function, that uses some weird approach to merge properties from one object to another, and it fails in certain cases.

I wrote a test program to verify your `utils.merge`, If you install paypal-rest-sdk locally, you should be able to reproduce it:

```
var utils = require("./node_modules/paypal-rest-sdk/lib/utils");

var obj1 = {
  "host": "api.sandbox.paypal.com",
  "port": "",
  "client_id": "SomeId",
  "client_secret": "SomeSecret"
};

var obj2 = {
  "mode": "sandbox",
  "schema": "https",
  "host": "api.sandbox.paypal.com",
  "port": "",
  "openid_connect_schema": "https",
  "openid_connect_host": "api.sandbox.paypal.com",
  "openid_connect_port": "",
  "authorize_url": "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize",
  "logout_url": "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/endsession",
  "headers": {}
};

console.log("OBJ1 = " + JSON.stringify(obj1, null, 2));
console.log("OBJ2 = " + JSON.stringify(obj2, null, 2));

var result = utils.merge(obj1, obj2);
console.log("RESULT = " + JSON.stringify(result, null, 2));
```

The console output is:

```
OBJ1 = {
  "host": "api.sandbox.paypal.com",
  "port": "",
  "client_id": "SomeId",
  "client_secret": "SomeSecret"
}
OBJ2 = {
  "mode": "sandbox",
  "schema": "https",
  "host": "api.sandbox.paypal.com",
  "port": "",
  "openid_connect_schema": "https",
  "openid_connect_host": "api.sandbox.paypal.com",
  "openid_connect_port": "",
  "authorize_url": "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize",
  "logout_url": "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/endsession",
  "headers": {}
}
RESULT = {
  "host": "api.sandbox.paypal.com",
  "port": "",
  "client_id": "SomeId",
  "client_secret": "SomeSecret",
  "mode": "sandbox",
  "schema": "https",
  "openid_connect_schema": "https",
  "openid_connect_host": "api.sandbox.paypal.com",
  "openid_connect_port": "",
  "authorize_url": "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize",
  "logout_url": "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/endsession"
}
```

The `headers` object is NOT in the result, but your code in api.js assumes it's there.

**Comment by avidas** [comment]
Hey @kobalicek , we will take a look at this issue and get back to you soon. Thanks.

**Comment by kobalicek** [comment]
Thanks for checking it out

**Comment by avidas** [comment]
@kobalicek no problem. While we look at it, feel free to send in a pull request as well if you feel that you have a fix that addresses the issue.

**Comment by kobalicek** [comment]
Well I just tested it, but I don't feel like proposing a change as the function `merge` looks a bit weird to me, I don't really know what it is supposed to do so it's better if you guys take a look. I think it would be better if you unittest your utils so it behaves like you expect :)

**Comment by avidas** [comment]
Hey @kobalicek identified the fix, it will go out in the next release.

**Comment by kobalicek** [comment]
I'm not sure if the patch is right, the `obj1[p] = obj2[p];` does a weak copy from `obj2`, that means that if `obj2` is not a primitive value it will be just referenced, so any modification in `obj1` will be immediately reflected to `obj2`.

**Comment by kobalicek** [comment]
I experimented with a merge implementation that probably does what you want, just take a look if you are interested. Some cases are missing as I'm not sure how you intent to handle incompatible types, like `a` is `[]` and `b` is `{}`. I think the function should check for these conditions and fail in such cases.

```JS
var isArray = Array.isArray;
var hasOwn = Object.prototype.hasOwnProperty;

function clone(v) {
  if (v == null || typeof v !== "object")
    return v;

  if (isArray(v)) {
    var arr = v.slice();
    for (var i = 0; i < srcArr.length; i++)
      arr[i] = clone(arr[i]);
    return arr;
  }
  else {
    var obj = {};
    for (var k in v)
      obj[k] = clone(v[k]);
    return obj;
  }
}

function merge(a, b) {
  // Handle invalid arguments.
  if (a == null || typeof a !== "object")
    throw new TypeError("merge() - 'a' has to be an object, not " + typeof a + ".");

  if (b == null || typeof b !== "object")
    throw new TypeError("merge() - 'b' has to be an object, not " + typeof b + ".");

  var aIsArray = isArray(a);
  var bIsArray = isArray(b);

  if (aIsArray && bIsArray) {
    // TODO: Not sure if this is allowed...
    return a;
  }

  if (aIsArray || bIsArray)
    throw new TypeError("merge() - Detected incompatible types.");

  for (var k in b) {
    var aVal, bVal = b[k];
    if (hasOwn.call(a, k)) {
      aVal = a[k];
      if (aVal != null && typeof aVal === "object" &&
          bVal != null && typeof bVal === "object") {
        merge(aVal, bVal);
      }
      else {
        // Not sure what to do here, clone? 
        a[k] = clone(bVal);
      }
    }
    else {
      a[k] = clone(bVal);
    }
  }

  return a;
}

console.log(merge(
  {},
  { a: true, b: 1 })
);

console.log(merge(
  { a: 1, b: { c: 1 } },
  { a: 42, b: { c: 42 } })
);

console.log(merge(
  {},
  { a: true, b: { c: { d: 42 } } })
);
```

**Comment by avidas** [comment]
Hey @kobalicek thanks for this! You are correct that incompatible type merges should fail. The merge function here is supposed to take care of the specific use cases as it applies to this sdk, mostly updating the http configurations or data. Clients of the merge function would be internal within the sdks itself and not beyond that. In that respect, it is not meant to be a fits all merge implementation. Do you anticipate sdk use cases where the proposed merge would fail?

**Comment by kobalicek** [comment]
Hi @avidas, I provided the code as a reference, the problem in your implementation can be described by using this code (it's using the new merge you provided):

```JS
function merge(obj1, obj2) {
    for (var p in obj2) {
        try {
            // Property in destination object set; update its value.
            if (obj2[p].constructor === Object) {
                if (!obj1[p]) {
                    obj1[p] = obj2[p];
                }
                else {
                    obj1[p] = merge(obj1[p], obj2[p]);
                }
            } else {
                obj1[p] = obj2[p];
            }
        } catch (e) {
            // Property in destination object not set; create it and set its value.
            obj1[p] = obj2[p];
        }
    }
    return obj1;
}

var template = { options: {} };

var dst1 = merge({}, template);
var dst2 = merge({}, template);

console.log(JSON.stringify(dst1, null, 2));
console.log(JSON.stringify(dst2, null, 2));

dst1.options.a = true;

console.log(JSON.stringify(dst1, null, 2));
console.log(JSON.stringify(dst2, null, 2));
```

which outputs:

```
{
  "options": {}
}
{
  "options": {}
}
{
  "options": {
    "a": true
  }
}
{
  "options": {
    "a": true
  }
}
```

I hope you see now the problem, the implementation is still wrong and fails.

**Comment by avidas** [comment]
Reopening this

**Comment by GavinPalmer1984** [comment]
I grabbed the paypal-rest-sdk just now and encountered this bug as well.  Thank you for your help!

**Comment by avidas** [comment]
@kobalicek thanks for that example, I would agree with you that the bug in merge still exists. Might use your merge implementation as baseline for the the new rewrite and make sure that you are credited for it.

**Comment by kobalicek** [comment]
I consider the code I posted as public domain, it's fine, thanks for fixing the bug :+1:

**Comment by avidas** [comment]
@kobalicek @GavinPalmer1984 release 1.5.1 went out with updated merge implementation.

**Comment by kobalicek** [comment]
Thanks! There is a minor typo, that doesn't affect the functionality (I commented).

**Comment by avidas** [comment]
Thanks @kobalicek patched the error message now on master.

**Comment by kobalicek** [comment]
Thanks, I see no other problem here, thanks :+1:

**Comment by avidas** [comment]
closing
