### ISSUE TITLE
TypeError creating a charge from a Future Payment authorization

### ISSUE THREAD

**Issue by knightcode** [paypal/PayPal-node-SDK#71]
Having previously authorized a future payment and stored the refresh token in our DB, The following code is crashing the server (node.js) when payment information comes in from the iOS SDK. I've already ensured that all the data given to these objects is legit, and the `client_id` and `client_secret` were previously set by a call to `paypal.configure`.

```
ppConf = {
          mode = "sandbox",
          correlation_id: payment.corrID,
          refresh_token: paymentAuthID
      };
charge = {
          intent: "sale",
          payer: {payment_method: "paypal"},
          transactions: [{
            amount: {currency: "USD", total: order.grandTotal / 100.0},
            description: ""
            }]
      };
paypal.payment.create(charge, ppConf, function (err, payment) {
   ...
}
```
The exception:
```
TypeError: Cannot set property 'Paypal-Application-Correlation-Id' of undefined
     at Object.executeHttp (....../node_modules/paypal-rest-sdk/lib/api.js:132:67)
     at Object.create (..../node_modules/paypal-rest-sdk/lib/generate.js:27:13)
```

**Comment by avidas** [comment]
Hey @knightcode what version of the sdk are you using? Has this started happening recently or has it always been an issue?

**Comment by knightcode** [comment]
have it set to always use the latest, so 1.5.0 in this case. And it's always been an issue.

**Comment by avidas** [comment]
@knightcode the issue is likely related to #69 , I am working on a fix and will post here soon.

**Comment by avidas** [comment]
@knightcode version 1.5.1 with a patch for #69 will go out soon, could you confirm if the bug still appears on your end?

**Comment by knightcode** [comment]
Not crashing any more, but getting:
```
Error: Response Status : 400
     at IncomingMessage.<anonymous> (/........./node_modules/paypal-rest-sdk/lib/client.js:116:23)
```

Will investigate to see if it's something I'm doing.

**Comment by knightcode** [comment]
As far as I can tell, I'm doing everything I should be. The future payment authorization worked for a Sandbox account I had created, and I confirmed the bearer token is the same set later on the ppConf object above. The iOS App is pre-connecting to the Sandbox network (as far as I can confirm) and then getting the clientMetadataID(), which is also set correctly. The grand total is positive. Still getting 400.

**Comment by avidas** [comment]
Hey @knightcode does the error message give you a paypal debug id? We can use that to look in our internal logs to see what is going on.

Any chance you can try creating the payment with curl request and see if the issue is reproducable? It would be similar to https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#request-2

**Comment by knightcode** [comment]
The only keys defined on the error object I get back are 'response' and 'httpStatusCode' as returned by Object.keys().

`curl` gives me a `401 Unauthorized`

Here's the command I used:

```
curl -v "https://api.paypal.com/v1/payments/payment" -H "Content-Type: application/json" -H "PayPal-Client-Metadata-Id: 7******************************8" -H "Authorization: Bearer A*********************6Vr.H***************************Y" -d '{"intent":"sale", "payer":{"payment_method":"paypal"},"transactions":[{"amount":{"currency":"USD", "total":5.00}, "description":""}] }'
```
The period in the Bearer token seems to differ from the example to which you referred me.

**Comment by avidas** [comment]
Try setting NODE_ENV=development to see if the debug id is provided for the sdk.

For curl, are you able to use it to create any payment? Was there a PayPal-Debug-Id Header?

More helpful docs on https://developer.paypal.com/webapps/developer/docs/integration/web/accept-paypal-payment/ . One other common reason for 401 is sandbox vs live credentials.

**Comment by knightcode** [comment]
Ok, that link used "api.sandbox.paypal.com" instead of the "api.paypal.com" that was used in the first example to which you referred me. So I'm not getting the 401 anymore.

The curl response I'm getting now:
```
{"name":"VALIDATION_ERROR","details":[{"field":"redirect_urls","issue":"This field required when payment_method is 'paypal'"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"990cc08a2da09"}
```

My next stop will be to try and set the redirect_urls, but this seems like it should be unnecessary when I've already got a future payment authorization token.

NODE_ENV is, was, and has been set as 'development' here.

**Comment by knightcode** [comment]
I added redirect_urls to the charge json object as seen in: https://github.com/paypal/PayPal-node-SDK/blob/master/samples/configuration/multiple_config.js

Still getting a `400` from the node SDK.

api.sandbox.paypal.com is always sending a 401 Unauthorized now when using `curl`, with and without the redirect_urls set in the data payload.

**Comment by ppmtscory** [comment]
@knightcode The validation error for redirect_urls has to do with using the same account as the receiver of funds as you are for the sender of funds.  Please ensure that you are using 2 separate accounts to test with (a merchant and a buyer).

**Comment by knightcode** [comment]
That's odd error feedback, but thank you.

I'm a bit confused what the Sandbox testers created in our Merchant account are supposed to be then. All requests thus far have been coming from them, especially in Sandbox mode. Are you saying I have to create ANOTHER merchant account, create Sandbox users in there, and then make requests from those users back to the real merchant account????

**Comment by ppmtscory** [comment]
@knightcode The layout is as such...

developer.paypal.com login account (this is a Live PP account)
|_ sandbox accounts created inside here (can create multiple accounts)
   |_ one account will be a merchant account (the default is the -facilitator account)
   |_ one account will be a buyer account (you'll need to create this account)

As it stands right now, you have the "-facilitator" account that you've linked to your App you created and have the Client ID and Secret.  Since you are using the credentials for this account in your code, you are not able to login to PayPal and give consent with this account.  Therefore, when you login to developer.paypal.com and go into your list of accounts you should have a "xxx-facilitator@xxx.com" account that's currently being used to receive money.  You also should have another account listed ("xxxx@xxxxx.com") and this account is what you will use to login on the PayPal screen to provide consent for Future Payments.  If you do not have this second account in the list, then you'll need to click the Create button on that page to create a buyer sandbox account.

As long as you do that, then you will be able to process the payment afterwards because the account that provided consent is *not* the same account that's set to receive the payment.

**Comment by knightcode** [comment]
I had already done this. The "-facilitator" account is there, as is "-buyer". Additionally, I had created two other test accounts. It's one of these additional test accounts from which all the requests above have been made. The bearer token came from its login credentials being entered in the app, sent up to our server, and obtained from `paypal.generateToken`. And that token was copied to the `curl` calls.

The client and secret given to `paypal.configure` seem to be listed in a different section of the Paypal Dashboard, and I don't see any corresponding client/secret data for the test users. Being that I'm not the owner of our merchant account, I don't know or, at least, haven't set a password on the "-facilitator" account. So it's really unlikely this is the issue.

**Comment by ppmtscory** [comment]
Correct, the Client ID/Secret are listed in a different section of the Dashboard.  Those are assigned to the -facilitator account by default and would only be assigned to a different sandbox account if you selected that email/account during the App creation.

Looking up that previous debug ID in our logs (990cc08a2da09) and the 'merchant' account (the account running the API calls and receiving money) being used is jose-facilitator@xxxxxx.com.  The 'buyer' account (the account used to login to the PayPal page in the App to give Future Payment consent) is jose-facilitator@xxxxxx.com.  This is what's causing your error.  Please run another test and when you are presented with the page to login to PayPal through the Future Payments flow, please enter a different login than the jose-facilitator account.  Once you do this, you should not see the validation error for redirect_urls.

**Comment by knightcode** [comment]
I created a new sandbox account, and got a future auth bearer token for it from our app. I also deleted and recreated a bearer token for the existing sandbox account used for everything else in the above discussion. 

Both still failed with a `Response Status : 400` error when using the node SDK on our server, even with the update charge object containing fake redirect_urls, as shown below. The only keys on the error object for both transactions were `response` and `httpStatusCode` using `Object.keys`.

```
charge = {
          intent: "sale",
          payer: {payment_method: "paypal"},
          transactions: [{
            amount: {currency: "USD", total: order.grandTotal / 100.0},
            description: ""
            }],
          redirect_urls: {
            return_url: "http://return.url",
            cancel_url: "http://cancel.url"
          }
      };
```

However, for both transactions that failed, trying a `curl` with the new bearer token and client metadata ID reported from the iOS SDK did succeed. The fake redirect urls were necessary for success. Example command:
```
curl -v "https://api.sandbox.paypal.com/v1/payments/payment" -H "Content-Type: application/json" -H "PayPal-Client-Metadata-Id: ***************" -H "Authorization: Bearer **************************" -d '{"intent":"sale", "payer":{"payment_method":"paypal"},"transactions":[{"amount":{"currency":"USD", "total":5.00}, "description":""}], "redirect_urls":{"return_url":"http://return.url", "cancel_url":"http://cancel.url"} }'
```

**Comment by ppmtscory** [comment]
@knightcode Can you please provide a debug ID for the failures with the Node SDK?

**Comment by knightcode** [comment]
The error doesn't seem to conform to the documentation. This is what comes back:
```
obj
|- httpStatusCode: 400
|- response
   |- httpStatusCode: 400
   |- error: "invalid_request"
   |- error_description: "Invalid refresh token"
```

**Comment by ppmtscory** [comment]
Since you don't use a refresh token for a payment request, this seems to be a different error.  Are you attempting to generate an access token from a refresh token?  If that's the case, then you need to ensure that you are passing through the correct refresh token to be used.  You can also test this with a simple [curl command](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#refresh-an-access-token).  If you are able to generate an access token from a refresh token that you have stored, via curl, then that will validate that the refresh token is good.  You should then be able to use that refresh token to generate a new access token via the SDK.

**Comment by knightcode** [comment]
I'm following [this sample](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/create_future_payment.js). It passes the refresh_token to `paypal.payment.create` to charge the customer. Is this sample old? Does that call not get a new access token for me?

**Comment by ppmtscory** [comment]
I will confirm functionality with @avidas and one of us will get back to you.

**Comment by avidas** [comment]
@knightcode That sample should work, I was just testing and it worked fine on sandbox. Are you sure that your client_id, client_secret and mode are the same for your node sdk configuration and ios sdk configuration? 

Once you set the authorization_code in the sample, run the sample with "NODE_ENV=development node create_future_payment.js" It should print debug id in the logs, and we can use that to look more into the 400s

**Comment by knightcode** [comment]
@avidas I'll do that here when I get a second, but you seem to be suggesting I need an authorization_code for every transaction despite the comment in that sample that says the refresh token has a long shelf life and can be stored in a database. That suggests I should somehow be able to return to lines 24-52 at some future time and create a payment just using the refresh token and client ID. 

That would be test I'd like to conduct.

If that's not intended, what API call do I make to get a new access token using the refresh_token? I can't seem to find documentation on that for the node SDK.

**Comment by avidas** [comment]
Hey @knightcode, sorry if my message was confusing but you only need to exchange authorization code for refresh token once per customer. You can charge the customer using that refresh token at a later time. 

That particular sample shows the full end to end flow for the first time the customer has granted consent, to creating a payment. Later times, you can ignore the exchange auth for refresh step and directly use the refresh token to create the payment. Under the hood, the sdk does the work for exchanging the refresh token for an access token and creating the payment.

**Comment by avidas** [comment]
# Using the refresh token to create payments later. Tested this and worked fine too.


"use strict";
var paypal = require('../../');
require('../configure');

var future_payment_config = {'correlation_id': 'test df', 'refresh_token': '<TOKEN>'};

//Set up payment details
var create_payment_json = {
    "intent": "sale",
    "payer": {
        "payment_method": "paypal"
    },
    "transactions": [{
        "amount": {
            "currency": "USD",
            "total": "1.00"
        },
        "description": "This is the payment description."
    }]
};

//Create future payment
paypal.payment.create(create_payment_json, future_payment_config, function (error, payment) {
    if (error) {
        console.log(error.response);
        throw error;
    } else {
        console.log("Create Payment Response");
        console.log(payment);
    }
});

**Comment by knightcode** [comment]
@avidas Finally, tried this script verbatim aside from clientID and refresh_token. No change for me. No debug id. It just says invalid refresh token. This is the token I had gotten back from the test account:
```
Bearer A015jeUtl5OQOkh6ARQGxKXVYrzZmttdQpKftQMxM39MnLs
```
I tried it both with and without the "Bearer " prefix.

**Comment by knightcode** [comment]
the client seems to be printing some code to the console. Maybe a debug id? Here are three I got:
```
eaaaacb0fce81
67b099d57087e
8d403e8477876
```

**Comment by knightcode** [comment]
@avidas checking in. Anything?

**Comment by avidas** [comment]
@knightcode thanks for the debug_ids. We will take a look here and get back to you.

**Comment by ppmtscory** [comment]
@knightcode It appears that you may be confusing the access token (Bearer token) with the refresh token.  When using the refresh token, I'm not able to reproduce but when I use the Bearer access token, then I get the same error as you are getting.  Since you are mentioning the Bearer token, I can only assume that this may be what's happening.

When you exchange your auth code for tokens, you receive both a refresh token and a Bearer access token in the response.  Please validate that you are using the refresh_token for these sample scripts and NOT the Bearer access token.  To be perfectly clear - when you are using curl commands (which you said were successful) you DO use the Bearer access token.  However, when using this sample of the SDK, you DO NOT use the Bearer access token but rather the refresh token and the SDK will generate the access token automatically to use.

**Comment by knightcode** [comment]
@avidas @ppmtscory The bearer token to which I refer above is the value assigned to the `rt` variable in the code snippet below taken from the aforementioned sample I'm following. Please, confirm that I'm getting passed the correct value.

```
paypal.generateToken(auth_code, function (error, rt) {
    if (error) {
        console.log(error);
        console.log(error.response);
    }  else {
        //Refresh token has long shelf life. It is recommended to store this in a database
        //for future payments
        console.log(rt);
        var refresh_token = rt;

        var future_payment_config = {'correlation_id': 'Correlation ID from mobile sdk', 'refresh_token': refresh_token};
```

**Comment by ppmtscory** [comment]
You'd mentioned that the token you got back with the test account had "Bearer" in front of it.  With that sample code, when you run the generate token with the Auth code, it does not return "Bearer xxxxxx".  It should just return the refresh token that's needed for the script, without the "Bearer" because the Bearer token is the access token.  Below is what I'm getting back for the refresh token with that script (with some X's for security purposes).  This is what's assigned to the rt variable.

5xy6g3ZRx7lg5IOx-86eu6CKelGFbSbfXrhUnIdwfexNq9LxxxxxxxxxxxxxxxkqUK5cJm1hkkqzFb7LJm43pH-9V3Q

**Comment by knightcode** [comment]
Just tried again and received another Bearer token. Debug ID: `ecdc31e23b066`

I printed each value of `arguments` in the callback, too. It was just the two.

The input I supplied was an object with the properties as follows:
```
code=AuthorizationCodeForNoNetworkEnvironment, 
environment=mock,
product_name=PayPal iOS SDK,
paypal_sdk_version=2.9.0,
platform=iOS,
response_type=authorization_code,
mode=sandbox,
schema=https,
host=api.sandbox.paypal.com,
port=,
openid_connect_schema=https,
openid_connect_host=api.sandbox.paypal.com,
openid_connect_port=, authorize_url=https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize,
logout_url=https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/endsession,
,
client_id=ARFZXXXXXXXXXJzGwCbO_XXXXXXXXXXXXXXXXXX_TDwNXXXXfd4zz,
client_secret=EJEOlRDhpxHld4zjxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxJLiJSlGs61Ejdy
```

**Comment by ppmtscory** [comment]
You're using two different environments....mock for the iOS SDK and then sandbox for the Node SDK.  You'll need to use sandbox for the iOS SDK to generate the appropriate auth token to then input into the node samples.  Remember to use the same sandbox client ID for the iOS SDK that you are using in the node SDK.

**Comment by knightcode** [comment]
Fixed that on the client. Same result on the server. Got a Bearer token again.

Debug ID from iOS Client: `c05672da2d1af`
Debug ID from generateToken: `0d9e0216561dc`

Input for `generateToken` is:
```
code=EDvB-984vVzqpyulnKEgXB2nrv8Sqk-pvXXCXXXXXXXXXXXXXXXXXXn3lchm9wmHrsfh_XXXXXXXXXXXXXXXXX-VFJLghcQLfc_tPXXXXXXXXXXy8X4-NSyU_XXXXXXXXX,
environment=sandbox,
product_name=PayPal iOS SDK,
paypal_sdk_version=2.9.0,
platform=iOS,
response_type=authorization_code
```

**Comment by ppmtscory** [comment]
@knightcode You are getting a different error this time according to those debug ID's.  Let me examine our logs quick and I will get back to you.

**Comment by ppmtscory** [comment]
@knightcode I am seeing some errors with your iOS client debug ID that I'd like to get more clarification on.  I'll be off and on all day but do you have Skype?  If so we could try to hash this out step by step.  Please do not put your skype name here but create a ticket at www.paypal.com/mts with your skype name and then let me know the ticket number here.

**Comment by knightcode** [comment]
#150326-000235

**Comment by ppmtscory** [comment]
Thanks @knightcode, I've sent you a contact request.

**Comment by knightcode** [comment]
Solved:

I don't know if this is universally the case for all mobile SDKs, but the iOS SDK produces a dictionary as follows (printing it to the console with winston flattened the hierarchy, as I copied above):
```
client
 |- environment = 
 |- paypal_sdk_version = 
 |- platform = iOS
 |- product_name = "PayPal iOS SDK"
response
|- code = XXXXXXXXXXXX
|- response_type = "authorization_code"
```

`generateToken` requires an object with the property, `authorization_code` , set. So marshaling all the data from SDK to SDK wasn't the way to go. The following lines fixed it for me:
```
if (data.response && data.response.code) {
    data.authorization_code = data.response.code;
}
paypal.generateToken(data, function (err, rt) {
    ....
}
```

If all the mobile SDKs produce the same data structure, it'd be worth a note in the sample or a note in the mobile SDK that only `response.code` needs to be saved. It also seems like `generateToken` should complain when given a dump from a mobile SDK... if it's too difficult to handle appropriately.
