### ISSUE TITLE
utils.merge

### ISSUE THREAD

**Issue by skoppe** [paypal/PayPal-node-SDK#72]
The merge-function doesn't work correctly with following input:
```
utils.merge({},{a:{b:'c'}});
```
it will return {a:undefined};

Add this in begin of function
```
if (!obj1) return obj2;
```

And it also allows you to get rid of the ugly try..catch

**Comment by avidas** [comment]
Hey @skoppe , mind putting this in the form of a pull request?

**Comment by skoppe** [comment]
Nevermind, on master somebody already fixed that.
