### ISSUE TITLE
Which Webhook to use for paid Invoices?

### ISSUE THREAD

**Issue by bf** [paypal/PayPal-node-SDK#76]
Based on your documentation about REST webhooks at https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/ I cannot really see how it is possible to implement that a webhook is called as soon as one of my customers has paid an invoice. 

Am I overlooking something or do I need to use IPN for this use case?

**Comment by poaaaaa** [comment]
![img_1059](https://cloud.githubusercontent.com/assets/11446572/6771561/621b1a46-d0d9-11e4-82f0-8a339bd010b8.JPG)

**Comment by bf** [comment]
Sorry, but I am not sure what you mean by showing off a receipt which seems to include your personal IBAN.

When I am looking at the event types available for webhooks, I see identifiers like `PAYMENT.SALE.*`,  `PAYMENT.CAPTURE.*` and  `PAYMENT.AUTHORIZATION.*`. I am wondering if the `PAYMENT.SALE.COMPLETED` event also applies to invoices created through the REST API which are paid by the user through the Paypal website.

**Comment by bf** [comment]
I've now solved the issue through trial and error. It seems invoice receipts are only available via Paypal IPN messages, which are a bit tricky to set up so everything works.
