### ISSUE TITLE
`payer` and `shipping_address` is missing from Billing Agreement object

### ISSUE THREAD

**Issue by gregwym** [paypal/PayPal-node-SDK#78]
Hi Paypal team, 

Neither `paypal.billingAgreement.create()` nor `paypal.billingAgreement.get()` returns the `payer` or `shipping_address` information. We relay on these info to providing shipping for our subscribers. 

Another missing property is `id` in the response of `paypal.billingAgreement.create()`. I have to merge the billing agreement object with the response of `paypal.billingAgreement.execute()` to obtain the ID. 

Thanks, 
Greg

**Comment by gregwym** [comment]
I have found a SO question without answer. http://stackoverflow.com/questions/27030437/retrieving-shipping-address-and-user-information-from-billing-agreement-via-payp

**Comment by avidas** [comment]
Hey, this would be relevant https://github.com/paypal/PayPal-PHP-SDK/issues/155

**Comment by gregwym** [comment]
Hi @avidas, thanks for the quick response. Is there an ETA for the update?

**Comment by jziaja** [comment]
@gregwym, I provided an update on the other thread, which is what we're using to track this API bug and provide further guidance.
