### ISSUE TITLE
Getting a Access-Control-Allow-Origin error

### ISSUE THREAD

**Issue by Shivaraman-iyer** [paypal/PayPal-node-SDK#79]
While redirecting to the sandbox account from my local server I am getting :

XMLHttpRequest cannot load https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-0JR727016T795182U. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Any clue as to what might be the reason for this would be really helpful.

**Comment by avidas** [comment]
Have you tried adding the header 'Access-Control-Allow-Origin' server side? e.g. http://stackoverflow.com/questions/17124600/how-can-i-add-cors-headers-to-a-static-connect-server/17124775#17124775

**Comment by Shivaraman-iyer** [comment]
I tried doing that, didn't seem to work. But, I now sent the info to the front end and then redirected the page there and it worked.

**Comment by jayna09** [comment]
Hello @shivaraman-aiyer, How did you solve this? I am facing same issue.
