### ISSUE TITLE
Rely on `paymentId` query parameter in return URL?

### ISSUE THREAD

**Issue by mattgoucher** [paypal/PayPal-node-SDK#80]
When I execute a payment, can/should I use the `paymentId` and the `payer_id` that are sent back as query string parameters on the success URL? Or, should I be storing the paymentId after the `payment.create` was successful?

Where the approval_url's are formed like this:
`http://test.com/complete?&paymentId=...&token=...&PayerID=...`

**Comment by avidas** [comment]
Hey @mattgoucher, the paymentId parameter on approval_url and paymentId after the payment.create call are the same. Your success redirect handler can just call payment.execute with the paymentId and PayerID from the approval_url.

You only need to store the paymentId after the payment.create was successful if you want to track how many created payments result in redirect to success endpoint.

**Comment by jaypatel512** [comment]
Closing the issue as @avidas response is correct. Use the PaymentID from query parameters. No need to store paymentId on create.

**Comment by mattgoucher** [comment]
Thanks guys!
