### ISSUE TITLE
Payment Definition names are exchanged in Billing Agreement. 

### ISSUE THREAD

**Issue by gregwym** [paypal/PayPal-node-SDK#82]
I defined two payment definitions in the Billing Plan. One is TRIAL another is REGULAR. Their names appear to be correct. 
After created the Billing Agreement with the given Billing Plan, the payment definition names are exchanged.

**Comment by avidas** [comment]
@gregwym could you post the exact calls you made, and the responses received that shows the definition names were reversed? Please don't post any payment information such as credit card numbers or client secret.

**Comment by avidas** [comment]
Any updates @gregwym ?

**Comment by gregwym** [comment]
Hi @avidas, I just tried again with the sandbox and cannot reproduce the issue any more. Thanks for following up! I will update if I see this behaviour again.
