### ISSUE TITLE
XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by nodu** [paypal/PayPal-node-SDK#83]
Hi I've been trying to integrate this into my webapp.  I've followed the great guide found here: https://devblog.paypal.com/building-a-web-app-with-node-js-the-paypal-sdk-part-2/

For the life of me,  I cannot get rid of this error: 
    `XMLHttpRequest cannot load https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-0LF19022L82747826. The request was redirected to 'https://www.sandbox.paypal.com/hk/cgi-bin/merchantpaymentweb?cmd=_flow&SESS…e0b7e69bf0224adecfb0124e9b61f737ba21b08198ecd47ed44bac94cd6fd721232afa4155', which is disallowed for cross-origin requests that require preflight.`

I've tried adding the cors package, no success.
I've tried modifying the headers on the request, no success.

I'm not sure the direction forward, any help would be greatly appreciated!

**Comment by avidas** [comment]
Hey, @nodu can you share your node/express app server configurations and what headers you are modifying? This could be related to [this issue](https://github.com/paypal/PayPal-node-SDK/issues/79) or [this one](http://stackoverflow.com/questions/28036696/the-request-was-redirected-to-https-com-site-login-which-is-disallowed-f)

**Comment by nodu** [comment]
Hi @avidas, thanks for replying.  OK, I'm making an ajax POST via superagent to my server http://localhost:8081/create, the server then runs the same code in devblog.paypal for the same /create action. I've taken out all header modifications as none of them seemed to work and I'm still getting the same error.  Where should I add which headers?  I've tried all the possible configurations several times, but must be missing the correct one!

**Comment by avidas** [comment]
@nodu , have you just tried out the samples from https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/create_with_paypal.js and https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payment/execute.js ? Together they show how to create a payment with paypal (then you have to visit the approval_url and approve the payment) and then execute the payment. I would suggest doing those with your client_id/secret config and see if you are getting proper responses. If you do, it is likely issue with app/browser settings and not the sdk.

**Comment by avidas** [comment]
Closing as most likely unrelated to sdk, reopen if necessary.
