### ISSUE TITLE
first_name in payer_info is empty string

### ISSUE THREAD

**Issue by night** [paypal/PayPal-node-SDK#85]
In the live API (I cannot reproduce this in sandbox), when transactions are executed (calling ``/v1/payments/payment/<Payment-Id>/execute``) the returned response of payer.payer_info.first_name is "" (empty string) in some payments.

Here is a debug_id from a call to this endpoint where this issue occurred: 01d152cc27f78

**Comment by avidas** [comment]
@night update, we filled PPTIPS-3489 (internal issue id) and are trying to track down the originating service which produces empty first name value. Thank you for providing the debug_id.

**Comment by ppmtscory** [comment]
@night our apologies on the delay but this should be resolved at this point.  I'm unable to reproduce an issue where first name isn't populated but should be.  Please do not hesitate to either reopen this issue or create a new issue if you should run into this again.
