### ISSUE TITLE
error: 'invalid_client' (401)

### ISSUE THREAD

**Issue by misterch0c** [paypal/PayPal-node-SDK#87]
```
paypal-debug-id: 728fd8193642e
null
token null
{ [Error: Response Status : 401]
  response: 
   { error: 'invalid_client',
     error_description: 'The client credentials are invalid',
     httpStatusCode: 401 },
  response_stringified: '{"error":"invalid_client","error_description":"The client credentials are invalid","httpStatusCode":401}',
  httpStatusCode: 401 }

```
I'm trying to make a payment using the example code. I put console.log('token '+token); line 81 in api.js and console.log(res); line 69. So as you can see the token is not see and res is null on the POST request. I checked my config and it seem to be passed proberly

And this is payload and http_options which are passed to client.invoke
```
grant_type=client_credentials
{ schema: 'https',
  host: 'api.sandbox.paypal.com',
  port: '',
  headers: 
   { Authorization: 'Basic dW5kZWZpbmVkOnVuZGVmaW5lZA==',
     Accept: 'application/json',
     'Content-Type': 'application/x-www-form-urlencoded' } }
```

**Comment by avidas** [comment]
Hey @misterch0c , is this different from the behavior you experience when you [create a token](https://developer.paypal.com/docs/integration/direct/make-your-first-call/) and [make a request via curl](https://developer.paypal.com/docs/integration/web/accept-paypal-payment/)?

**Comment by misterch0c** [comment]
I fixed it but sorry I don't remember how :/
