### ISSUE TITLE
Live mode charge from future payment refresh token: "Invalid JSON Response Received" with http status 401

### ISSUE THREAD

**Issue by knightcode** [paypal/PayPal-node-SDK#89]
I had previously spent some time on here getting this code to work for sandbox, and it still does work there. But when trying to create a create charge in production, I'm getting the following error: 

```
Error: Invalid JSON Response Received
    at IncomingMessage.<anonymous> (/home/ubuntu/savorycatering/node_modules/paypal-rest-sdk/lib/client.js:105:23)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)
```

My guess is that it's not authenticating with our production client ID and secret. But, in any case, could you first check for an error status code and report a more helpful error?

My question is, with the code below, if I'm passing a conf object to `paypal.payment.create`, does it ignore the previous call to `paypal.configure`? Or if at some point in the past, I had passed in the sandbox clientID and secret, would that override those keys set in `paypal.configure`?

At launch:
```
var paypal = require("paypal-rest-sdk");
paypal.configure({
  mode: PAYPAL_MODE,
  client_id: process.env.PAYPAL_CLIENT_ID,
  client_secret: process.env.PAYPAL_SECRET
});
```
Later...
```
ppConf = {
          correlation_id: payment.cardID,
          refresh_token: paymentAuthID
      };

if (isDebugUser) {
  ppConf.mode = "sandbox";
  ppConf.client_id =  ...
  ppConf.client_secret = ...
} else {
  ppConf.mode = "live"
}

paypal.payment.create(charge, ppConf, function (err/*, payment*/) {
```

**Comment by avidas** [comment]
Hey @knightcode , do you have any [debug-ids](https://github.com/paypal/PayPal-node-SDK#debugging) that you could provide?

**Comment by knightcode** [comment]
I don't. I can't reproduce the problem in sandbox mode.

**Comment by avidas** [comment]
@knightcode to answer your question about configuration, if you pass a conf object to paypal.payment.create, those configuration parameters should be overriding the previous call to paypal.configure, but the intent is for that to happen within the scope of that particular paypal.payment.create, not to change those settings for further subsequent calls.

What version of the sdk are you using?

**Comment by knightcode** [comment]
@avidas Ok, cool. Well that checks out since we just got another attempt that failed even with the above change. 

We're using 1.5.2

**Comment by knightcode** [comment]
@avidas This is still occurring. I confirmed that the Live client id and secret are being set correctly on the server and are those that appear in our Merchant account. I don't know what else is wrong. Is there any other reason we'd get a 401 back? Is there no chance that the SDK will be updated to produce a more helpful error?

**Comment by knightcode** [comment]
@avidas The iOS SDK is properly calling `PayPalMobile.preconnectWithEnvironment(PayPalEnvironmentProduction)` ("live"), so that the subsequent call to `PayPalMobile.clientMetadataID()` is getting an ID from the production environment if that matters. So all 4 of the refresh_token, correlation_id, client_id, and client_secret are production values. 

It still works flawlessly in sandbox.

**Comment by knightcode** [comment]
debug id `f1b01bab16a7e`

**Comment by avidas** [comment]
Hey thanks for providing the debug id. For the error, have you tried console logging the error.response? It generally has the error details.

**Comment by knightcode** [comment]
seems to be the empty string.

**Comment by knightcode** [comment]
@avidas anything?

**Comment by avidas** [comment]
Hey have not had a chance to debug this yet, will try to take a look soon.

**Comment by avidas** [comment]
Hey @knightcode for debugging purposes it would really help if you could use the authorization code you get from the mobile sdk to obtain a refresh token and then make a payment using [curl calls](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md). This would help us determine if this is an accounts issue or an sdk issue.

**Comment by avidas** [comment]
Also https://developer.paypal.com/developer/applications is worth checking and look under "My apps" and "account eligibility" to check that your particular account can receive future payments.
