### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by madextreme** [paypal/PayPal-node-SDK#92]
Hi

Sometimes when calling payment.create or payment.execute, I'm starting to get error with the following message "SELF_SIGNED_CERT_IN_CHAIN".

Here is the error stack
```
"level": "error", 
"message": "  Error: SELF_SIGNED_CERT_IN_CHAIN
    at SecurePair.<anonymous> (tls.js:1381:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10) 
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)  
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)" 
```

My more detailed description on stackoverflow is here
http://stackoverflow.com/questions/30684344/self-signed-cert-in-chain-heroku-nodejs-with-paypal-integration

Can you please help?

Thanks
Gevorg

**Comment by tomwhipple** [comment]
Can you quantify the "sometimes"?

Also, will you confirm that you are connecting to live (not sandbox)?

**Comment by madextreme** [comment]
@tomwhipple 

Unfortunately I wasn't able to reproduce that when I wanted. The app is hosted on heroku and is restarted automatically time to time, and sometimes the SELF_SIGNED_CERT_IN_CHAIN error starts to happen after SDK method call.
I went through SDK code, and I think the issue happens at level of "https" module.

I'v added process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; in my app, so after that the issues hasn't happened any more. But I'm not sure If that's a good way of solving the issue.
http://stackoverflow.com/a/21961005/1675860

Heroku support answered following:

> Now, back to the PayPal API issue – my suspicion is that one of these endpoints is returning a badly configured key:

> api.paypal.com. 300 IN A 173.0.84.98
> api.paypal.com. 300 IN A 173.0.88.98
> api.paypal.com. 300 IN A 173.0.92.23

> Try sending your request to each of them in turn and see if you can get the error consistently from > one of them individually and not the others.


I've tried to set custom "host" value in sdk to IP but saw that in any case It's overwritten by utils.getDefaultApiEndpoint(config.mode) function call.
https://github.com/paypal/PayPal-node-SDK/blob/master/lib/api.js#L58

Maybe It's better to have 
config.host || utils.getDefaultApiEndpoint(config.mode) || configuration.default_options.host,

So if the config.host is specified It's not overwritten by "api.paypal.com" or "api.sandbox.paypal.com"

So that's it so far.

**Comment by tomwhipple** [comment]
Hmm. I've run a couple of checks on those IPs and it looks like they are all returning identical certificate chains. Please keep us updated if this problem persists.

But, setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` opens a man-in-the-middle vulnerability.

**Comment by madextreme** [comment]
@tomwhipple Ok, thanks for help. Will try to dig further :)

**Comment by avidas** [comment]
@madextreme about setting a custom "host" value in the sdk, the "mode" configuration is given precedence so that if we see a config.mode present and equal live or sandbox, we just pick "api.paypal.com" or "api.sandbox.paypal.com". If config.mode is not provided and config.host is provided, then config.host will be used. Try removing mode from your config if you are trying to set a custom host.

**Comment by avidas** [comment]
@madextreme has this happened since?

**Comment by madextreme** [comment]
@avidas Hi
I've ended up with NODE_TLS_REJECT_UNAUTHORIZED  for now.
For more detailed investigation I think I need to setup a new instance of production config and try to reproduce the issue.

Maybe we should close this issue, and reopen if that will happen again for someone else or I'll find a way to reproduce that?

Thanks

**Comment by avidas** [comment]
@madextreme sounds good, feel free to reopen if necessary.
