### ISSUE TITLE
Support for new PayPal PLUS Creditcard and ELV

### ISSUE THREAD

**Issue by sajov** [paypal/PayPal-node-SDK#93]
are there any plans ?

**Comment by avidas** [comment]
Hey @sajov , the PayPal node SDK is representative of the REST apis that we have on https://developer.paypal.com/docs/api/ . If this is an additional feature that is going to be supported by the REST APIs, we will integrate support into the SDK. If it is something that is already supported by the REST APIs, it should be supported by the SDK already.
