### ISSUE TITLE
Set withCredentials=false

### ISSUE THREAD

**Issue by AW-UC** [paypal/PayPal-node-SDK#94]
Please set `withCredentials: false` or provide an option for it. As of now, it is undefined. Thus, `http-browserify` sets it to true here: https://github.com/substack/http-browserify/blob/master/lib/request.js#18. In my app, I cannot make any requests because of this. I allways recieve:

    XMLHttpRequest cannot load https://api.sandbox.paypal.com/v1/oauth2/token.
    A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true.
    Origin 'http://localhost:4200' is therefore not allowed access.

**Comment by avidas** [comment]
Hey @AW-UC , this happens when you use the library on the client side?

**Comment by AW-UC** [comment]
exactly. I installed the SDK via [ember-browserify] (https://github.com/ef4/ember-browserify) in my [ember-cli] (https://github.com/ember-cli/ember-cli) app. The Ember CLI app works as a frontend for a Rails API. Of course, I could use the Rails API for doing the Paypal stuff, but I would prefer to do it on the client side.
I know that I can pass `http_options` to `invoke` and `executeHttp`, but there seems to be no way to do that with `generateToken` etc.

**Comment by AW-UC** [comment]
I opened a PR. This might be caused by using `broserify` in the first place. There is another issue, that I fixed with https://github.com/paypal/PayPal-node-SDK/pull/95.

**Comment by avidas** [comment]
Cool, browerify like use cases have not been a priority for this repo, and enhancements like this are definitely welcome. Thanks for the PR!
