### ISSUE TITLE
Include in-context checkout

### ISSUE THREAD

**Issue by AW-UC** [paypal/PayPal-node-SDK#97]
An adapted http://www.paypalobjects.com/api/checkout.js should definately be included as an experimental feature. The redirections are aweful.

**Comment by AW-UC** [comment]
Ok, I see this is more a limitation of the REST API itself. [Embedded](https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-embeddedPayment-curl-etc/) and [adaptive](https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/) payments are just not included at all. Sadely, I seems that integration is not going to happen in the closer future.

**Comment by avidas** [comment]
@AW-UC That is currently the case. For embedded and adaptive apis, the current best way would be to use the classic apis.
