### ISSUE TITLE
Not able to integrate Paypal-node-sdk in webapp

### ISSUE THREAD

**Issue by mukulgupta2507** [paypal/PayPal-node-SDK#99]
Hi,

I was following this tutorial for integrating PayPal-node-SDK in my project for Pay with PayPal option. 
http://devblog.paypal.com/building-a-web-app-with-node-js-the-paypal-sdk-part-3/

I'm getting following error:
```
XMLHttpRequest cannot load https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=someToken. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.
```

Can anyone please help me out to resolve this issue? I'm using MEAN stack for my project.

Thanks

**Comment by avidas** [comment]
@mukulgupta2507 what version of the sdk are you using? These [issue](https://github.com/paypal/PayPal-node-SDK/issues/79) and [this one](http://stackoverflow.com/questions/28036696/the-request-was-redirected-to-https-com-site-login-which-is-disallowed-f) seems to be related as well.

**Comment by mukulgupta2507** [comment]
@avidas Thanks for the useful pointers. I'm able to solve the issue.

**Comment by rgins16** [comment]
@mukulgupta2507 If you don't mind, could you explain how you solved your issue?

**Comment by sairamchinna** [comment]
@mukulgupta2507  if i enable the cros for all also same issue am getting, could you explain please what are the steps have you followed.?
